### ISSUE TITLE
splitpath loses last character

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [JuliaWeb/HTTP.jl#1]
I just found out you're trying to revive Julia's webstack. Thank you for the effort. ;)

I guess I'll start helping out by finding bugs, since I seem to have a talent for that. It looks like splitpath fails to capture the last path character:

julia> uri = HTTP.URI("http://www.example.com/blah/blub?q=blub")
HTTP.URI("http://www.example.com/blah/blub?q=blub")

julia> HTTP.splitpath(uri)
2-element Array{String,1}:
 "blah"
 "blu"

**Comment by quinnj** [comment]
Woohoo, first bug! I appreciate the feedback; definitely take things for a spin and let me know anything else you find. I'm finishing up some testing on asynchronous response streaming, so that would be good to get tested.

**Comment by quinnj** [comment]
FWIW, I just committed some changes to make sure we can handle all sorts of request bodies (String, Vector{UInt8}, IO-types, etc.). We can also support "streaming" request bodies by starting an `@async HTTP.post(...; body=f)`, where `f` is a `HTTP.FIFOBuffer`. You can then continue writing chunks to `f`, and then close it by doing `HTTP.eof!(f)`. Check out the tests in `test/client.jl` to see more examples.
