### ISSUE TITLE
Documentation of Exceptions

### ISSUE THREAD

**Issue by samoconnor** [JuliaWeb/HTTP.jl#100]
I'm trying to figure out how to deal with exception handling for [`HTTP.request()` in AWSCore.jl](https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/http.jl#L32).

I see that there are [a number of exception types defined in client.jl](https://github.com/JuliaWeb/HTTP.jl/blob/master/src/client.jl#L90) and [some inline notes on other possible exceptions](https://github.com/JuliaWeb/HTTP.jl/blob/8b1ce4843f4c6cbea6ef6e1bd928717811a8c4a9/src/client.jl#L174).

It would be really useful to have a description [in the documentation](https://juliaweb.github.io/HTTP.jl/latest/index.html) of the possible exceptions for each function, what they mean, and documentation of the fields of the Exception structs.

**Comment by samoconnor** [comment]
Hi @quinnj,

I'm pretty happy with the compact state of [AWSCore.jl/src/http.jl](https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/http.jl#L18) with HTTP.jl [vs Requests.jl](https://github.com/JuliaCloud/AWSCore.jl/blob/v0.2.3/src/http.jl#L53).

What I've come up with for error handling is that HTTP.request() can throw: `HTTP.HTTPError` (including subtypes) or `HTTP.StatusError`. Are there any others?

My code has [a handler for `MbedTLS.MbedException`](https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/http.jl#L37) so I guess I must have seen this in my earlier attempt to port to HTTP.jl. Do I still need to catch this?

**Comment by quinnj** [comment]
You shouldn't need a handler for `MbedTLS.MbedException`; with the improved retry logic, hopefully we don't see those kinds of errors as much, but if there's a legit error, it'd manifest as an `HTTP.ConnectError` now.
