### ISSUE TITLE
Asserting header type to be Dict{String, String} is a bit annoying

### ISSUE THREAD

**Issue by KristofferC** [JuliaWeb/HTTP.jl#102]
Maybe I want to give the headers as `Dict{Symbol, String}` or I get them from somewhere and they happen to be `Dict{AbstractString, AbstractString}`. As long as it is possible to convert them to `Dict{String, String}` I think it should be ok.

**Comment by quinnj** [comment]
Good call. Updated.

**Comment by samoconnor** [comment]
A remaining minor concern is that the standard allows multiple repeated headers with the same name, and requires that their order is preserved. See https://stackoverflow.com/a/4371395

Perhaps `Vector{Pair}` should be allowed.

Why not just allow any `headers` where `[String(k) => String(v) for (k, v) in headers]` is valid?
e.g.
```
function f(foo, bar, headers::Vector{Pair{String,String}})
    ...
end

function f(foo, bar, headers) = f(foo, bar, [String(k) => String(v) for (k, v) in headers]
```
