### ISSUE TITLE
Verbose logging, but without reponse bodies

### ISSUE THREAD

**Issue by Keno** [JuliaWeb/HTTP.jl#105]
I like the `verbose` request logging, but my response bodies are binary, so dumping them in the terminal messes up all kinds of things. Would it be possible to split up the verbosity option a bit to get most of the verbosity without dumping response bodies to the terminal?

**Comment by quinnj** [comment]
Yeah, I figured we'd need more nuanced logging at some point. Shouldn't be too hard to add. We could also possibly use the same logic we have in `show` which detects binary, etc.

**Comment by quinnj** [comment]
kk, I added a `logbody` keyword arg. It's pretty easy to add options like this instead of fiddling w/ a new `verbose=REALLY_VERBOSE` config for now. We'll probably want more nuanced logging, but this is simpler for now. Usage is
```julia
HTTP.get(url; logbody=false)
```

**Comment by samoconnor** [comment]
This is broken. See #131
