### ISSUE TITLE
Documentation about interactive threadpool

### ISSUE THREAD

**Issue by AtsushiSakai** [JuliaWeb/HTTP.jl#1051]
I think interactive thread pool of Julia 1.9 is useful for web server users.
Based on this reply https://discourse.julialang.org/t/web-server-with-latency-sensitive-and-compute-heavy-task-separate-thread-pools/93949/3
HTTP.jl already supports it.

But, I couldn't find a document about it. Should we state it in the doc?

 - Julia 1.9.0
 - HTTP.jl latest

**Comment by quinnj** [comment]
Yeah, that's a good idea. Mind making a PR?
