### ISSUE TITLE
Outdated references to OpenSSL / MbedTLS

### ISSUE THREAD

**Issue by ericphanson** [JuliaWeb/HTTP.jl#1081]
https://github.com/JuliaWeb/HTTP.jl/blob/10182c0380e3c370a788cb48efafdf3fff4bbd43/src/HTTP.jl#L193-L194

since #1039 changed the default to OpenSSL

**Comment by quinnj** [comment]
will be fixed in https://github.com/JuliaWeb/HTTP.jl/pull/1079
