### ISSUE TITLE
HTTP.host() result has port appended 

### ISSUE THREAD

**Issue by samoconnor** [JuliaWeb/HTTP.jl#112]
```juia
julia> u = "https://batch.ap-southeast-2.amazonaws.com/v1/describecomputeenvironments"

julia> using URIParser
julia> URI(u).host
"batch.ap-southeast-2.amazonaws.com" 🙂

julia> using HTTP
julia> HTTP.host(HTTP.URI(u))
"batch.ap-southeast-2.amazonaws.com:443" ☹️
julia> HTTP.port(HTTP.URI(u))
"443"
```

This breaks AWS signature generation for AWSBatch (any probably for other AWS REST services): https://github.com/JuliaCloud/AWSSDK.jl/issues/3
(Thanks @rofinn for reporting this!)

To me it seems clear that the URI specification treats `host` and `port` as seperate components of the URI, so I think the `URI` module should seperate them.

The HTTP header `Host:` is allowed to include a port number, but it does not have to include it if it is the default (80 for HTTP or 433 for HTTPS).

**Comment by quinnj** [comment]
You can use `HTTP.hostname` to get host w/o port. It's in the docs for `HTTP.URI`

```julia
help?> HTTP.URI
  HTTP.URL(host; userinfo="", path="", query="", fragment="", isconnect=false)
  HTTP.URI(; scheme="", hostname="", port="", ...)
  HTTP.URI(str; isconnect=false)
  parse(HTTP.URI, str::String; isconnect=false)

  A type representing a valid uri. Can be constructed from distinct parts using the various supported keyword arguments. With a raw, already-encoded uri string, use
  parse(HTTP.URI, str) to parse the HTTP.URI directly. The HTTP.URI constructors will automatically escape any provided query arguments, typically provided as
  "key"=>"value"::Pair or Dict("key"=>"value"). Note that multiple values for a single query key can provided like Dict("key"=>["value1", "value2"]).

  For efficiency, the internal representation is stored as a set of offsets and lengths to the various uri components. To access and return these components as strings, use the
  various accessor methods:

    •    HTTP.scheme: returns the scheme (if any) associated with the uri

    •    HTTP.userinfo: returns the userinfo (if any) associated with the uri

    •    HTTP.hostname: returns the hostname only of the uri

    •    HTTP.port: returns the port of the uri; will return "80" or "443" by default if the scheme is "http" or "https", respectively

    •    HTTP.host: returns the "hostname:port" combination

    •    HTTP.path: returns the path for a uri

    •    HTTP.query: returns the query for a uri

    •    HTTP.fragment: returns the fragment for a uri

    •    HTTP.resource: returns the path-query-fragment combination
```
When I was researching this, according to most specs/usages, host typically _does_ include port, whereas "hostname" is more typical for referring to just the host w/o port.

**Comment by samoconnor** [comment]
Thanks for the pointer to `hostname()`  doc!

My understanding is that `hostname` has been obsoleted (the [Modifications](https://tools.ietf.org/html/rfc3986#appendix-D.2) section of the RFC lists `hostname` as an "obsolete rule").

The RFC treats  [`host`](https://tools.ietf.org/html/rfc3986#section-3.2.2) and [`port`](https://tools.ietf.org/html/rfc3986#section-3.2.3) as seperate things.

It also says _"URI producers and normalizers should omit the port component and its ':' delimiter if port is empty or if its value would be the same as that of the scheme's default."_. This would suggest that HTTP.URI behaviour of returning "433" for `port` for HTTPS URI's isn't right, and that neither the `host` or `hostname` functions should have "433" appended for HTTPS URIs.

I would suggest removing the current `HTTP.host` function and renaming `HTTP.hostname` to `HTTP.host`. This would maintain compatibility with `URIParser`, and would seem to be more in line with the language of the RFC.

**Comment by quinnj** [comment]
Thanks for doing the research on this. Just pushed the fix to not append port when not necessary.

**Comment by samoconnor** [comment]
I think the "`:`" is missing:
https://github.com/JuliaWeb/HTTP.jl/commit/e9f268cd8d75d994a092671323fbdd895238f441#diff-88a4a3749698b7e5272a666fdade14bcR121
