### ISSUE TITLE
Warning: Verbosity logging macros are deprecated as they are not compatible with juliac-compiled programs

### ISSUE THREAD

**Issue by Heptazhou** [JuliaWeb/HTTP.jl#1189]
This is annoying:
```
┌ Warning: Verbosity logging macros are deprecated as they are not compatible with juliac-compiled programs
│   caller = ip:0x0
└ @ Core :-1
```

Found <https://github.com/JuliaLogging/LoggingExtras.jl/pull/94>, which I suppose is the cause.

**Comment by SimonDanisch** [comment]
This isn't only annoying, this slows down websocket traffic by ~10-100x ...
WGLMakie's CI time went from 25min to over 90min.
Should we just use `@debug` instead, or what's the idea?
@quinnj, seems like you actually introduced that deprecation, do you have an idea how to fix this?

**Comment by SimonDanisch** [comment]
This is the line that comes up in the profile: https://github.com/JuliaWeb/HTTP.jl/blob/master/src/WebSockets.jl#L514

**Comment by dhanak** [comment]
Nope, the issue still persists in v1.10.9, see https://github.com/JuliaWeb/HTTP.jl/pull/1190#issuecomment-2464562582
