### ISSUE TITLE
Base.eof(::FIFOBuffer) should block to wait for more data.

### ISSUE THREAD

**Issue by samoconnor** [JuliaWeb/HTTP.jl#120]
The spec for `Base.eof` says [_"If the stream is not yet exhausted, this function will block to wait for more data if necessary, and then return false."_](https://docs.julialang.org/en/stable/stdlib/io-network/#Base.eof).

The current implementation of `Base.eof(::FIFOBuffer)` does not block: https://github.com/JuliaWeb/HTTP.jl/blob/779fe74fd3ce1949df4dddc0a039dd21fe46322f/src/fifobuffer.jl#L99

The problem is that stream consumers who do `while !eof(io) ...` rely on the blocking behaviour to avoid spinning at 100% cpu while waiting for data. e.g.: [`base/io.jl`](https://github.com/JuliaLang/julia/blob/44a4a89a8f80e567ffe36ffeb016ae01006e5ec2/base/io.jl#L430)
```julia
function write(to::IO, from::IO)
    while !eof(from)
        write(to, readavailable(from))
    end
end
```

Context of the discovery of this issue: #110

**Comment by KristofferC** [comment]
Can be closed?

**Comment by samoconnor** [comment]
This has not been fixed as far as I know.
However, FIFOBuffer is no longer used internally by HTTP.jl
