### ISSUE TITLE
Cannot precompile (connection refused)

### ISSUE THREAD

**Issue by fmarotta** [JuliaWeb/HTTP.jl#1204]
- Julia 1.10.3
 - HTTP.jl 1.10.11 to 1.10.13
 - MbedTLS.jl 1.1.9
- OS: Rocky Linux 8.10

Hi, the package fails to precompile with the following `ERROR: LoadError: HTTP.ConnectError for url = https://localhost:57813: IOError: connect: connection refused (ECONNREFUSED)`. Precompilation works fine for 1.10.10. I think v1.10.11 started to use `PrecompileTools`, but it may be a red herring. Also, everything works in my arch linux laptop with Julia 1.9.4.

**Comment by IanButterworth** [comment]
We should make the workload soft error irrespective of if we can fix this specific case.
