### ISSUE TITLE
Base.read(::FIFOBuffer) should block to wait for more data until eof.

### ISSUE THREAD

**Issue by samoconnor** [JuliaWeb/HTTP.jl#121]
The [spec for `Base.read(::IO, ::Int)`](https://docs.julialang.org/en/stable/stdlib/io-network/#Base.read) says: _"[By default] this function will block repeatedly trying to read all requested bytes, until an error or end-of-file occurs."_
 
For `Base.BufferStream` and `Base.TCPSocket`, `read()` behaves as specified and blocks to wait ffor more data (see https://github.com/JuliaLang/julia/issues/24526).

The current implementation of `Base.read(::FIFOBuffer)` is just an alias for `readavailable`: 
https://github.com/JuliaWeb/HTTP.jl/blob/8a48266265fec4fdd53f503ee7a94f111227a68e/src/fifobuffer.jl#L89

`readavailable` blocks only when the buffer is empty, not until end of file as `read` should do.

Context of the discovery of this issue: #110

**Comment by quinnj** [comment]
The FIFOBuffer method you reference isn't the same as the docs you referenced from Base. The corresponding Base docs are
```
read(s::IO, nb=typemax(Int))
Read at most nb bytes from s, returning a Vector{UInt8} of the bytes read.
```
which I think FIFOBuffer adheres to (though obviously is lacking in details about blocking/non-blocking)

**Comment by samoconnor** [comment]
Sorry, typo, the doc I referenced is for `Base.read(:: IOStream, ::Int)`.

It seems to me that if `FIFOBuffer` is intended to be a stream for communicating between tasks, it should follow the pattern set for this by Base. i.e. follow the doc for `Base.read(:: IOStream, ::Int)` and the behaviour of `BufferStream`.
