### ISSUE TITLE
FIFOBuffer method semantics differ depending on calling task.

### ISSUE THREAD

**Issue by samoconnor** [JuliaWeb/HTTP.jl#122]
The doc says _"when reading from a `FIFOBuffer`, if accessed from the main task, it will not block if there are no bytes available to read, instead returning an empty `UInt8[]`.
If being read from asynchronously, however, reading will block until additional bytes have been written."_.

I am concerned that this is a potential source of bugs that are difficult to track down.
Users may write some code where, at the time of writing, the `FIFOBuffer` is read from the same task that created it, and therefore sees non-blocking read behaviour. However, if the reading part of the code is made `@async` later for unrelated reasons the behaviour will change to blocking. e.g. the `@timeout` macro uses a task internally. So, if the user calls some convenience macro or function that internally uses a task they'll get unexpected behaviour.

Another possibility is that the user passes a result `FIFOBuffer` to something like `parse_yaml_from_stream(::IO) -> Dict`. The user may have no idea if this function uses a task internally or not. Or, the yaml library may change from using a task to not using a task.

The blocking behaviour should be consistent irrespective of the calling task.

Note that the branch referenced in https://github.com/JuliaWeb/HTTP.jl/issues/110 removes the task-specific blocking behaviour and still passes the test suite.

**Comment by KristofferC** [comment]
Can be closed?

**Comment by samoconnor** [comment]
This has not been fixed as far as I know.
However, FIFOBuffer is no longer used internally by HTTP.jl

**Comment by samoconnor** [comment]
@quinnj, do you have an appetite for fixing this and #120 ? or for moving FIFOBuffer to a seperate package? or submitting it as a PR for https://github.com/BioJulia/BufferedStreams.jl ?
