### ISSUE TITLE
Default timeouts are incorrectly documented (and maybe dangerous per #114) 

### ISSUE THREAD

**Issue by samoconnor** [JuliaWeb/HTTP.jl#123]
In `client.jl` and `types.jl` the default connect and read timeouts are [specified as 10 s and 9 s](https://github.com/JuliaWeb/HTTP.jl/search?utf8=✓&q=10.0+seconds&type=).

The code currently uses 15 seconds as the default:
https://github.com/JuliaWeb/HTTP.jl/blob/0bb79a7fbca632197c719efa43dc084a35f6a41a/src/client.jl#L63

Perhaps in the light of #114 it would be better for the default timeout to be `Inf` (which would result in the usual timeouts of the underlying TCP connection taking effect).

**Comment by xgdgsc** [comment]
What's the default timeout for now? Didin' t find in doc or code myself. Is it 0?

**Comment by quinnj** [comment]
```julia
function request(::Type{TimeoutLayer{Next}}, io::IO, req, body;
                 readtimeout::Int=60, kw...) where Next
```
so 60 seconds
