### ISSUE TITLE
Websockets?

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HTTP.jl#134]
Does this package support WebSockets.jl?

I am considering porting https://github.com/EricForgy/Pages.jl over from HttpServer.jl, but I need WebSockets.

Thanks :)

**Comment by EricForgy** [comment]
I see this is a duplicate of #54 

PS: Kind of bummed to see the lack of responses to prior issues. Seems this package does not have a lot of love from JuliaWeb 😅

**Comment by quinnj** [comment]
It's been discussed, but haven't had any traction yet. @hustf has done a lot of similar work lately in reviving the Websockets.jl package and we've discussed integrating HTTP.jl and Websockets.jl. I've opened https://github.com/JuliaWeb/WebSockets.jl/issues/84 to track progress officially.
