### ISSUE TITLE
Router Plans, Path Params

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [JuliaWeb/HTTP.jl#137]
Hey, I'm recently back to trying around with Julia and especially this package and I'm wondering what the plans for the Router are. I tried deciphering the register!-method, but some of it still looked a bit arcane to me.
Specifically, are there any plans to support path parameters, like:
/users/{name}
to extract a user-name from the path?
Or does it already exist and I just can't figure it out?

**Comment by Nosferican** [comment]
This should be closed.
