### ISSUE TITLE
How do I set cookies?

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [JuliaWeb/HTTP.jl#138]
Sorry to bother again, but ever since using this library (or Julia, actually), I seem to get stuck with the simplest of things. I tried passing an Array of Cookies in the Response constructor and push!-ing it to an existing Response's cookie-field, but it just does not seem to send any or even show any cookie-Headers when printing the Response.

**Comment by samoconnor** [comment]
@quinnj you're more familiar with the cookie API, can you help with this?

**Comment by samoconnor** [comment]
@TheOnlySilverClaw 

As far as I understand, on the client side you can pass [`cookies=true` to the request function](https://juliaweb.github.io/HTTP.jl/latest/index.html#Requests-1). The client will then store received cookies and send them back to the server as needed.

I don't think there is any specific cookie support on the server side.
However, I believe you can do something like [setheader(my_response, "Set-Cookie" => "cookie-name=cookie-value")](https://juliaweb.github.io/HTTP.jl/latest/index.html#HTTP.Messages.setheader).

https://github.com/JuliaWeb/HTTP.jl/blob/cb2cef20a24eac7d879c26b86f1bd8f2e7bc61ec/src/Servers.jl#L25-L27
