### ISSUE TITLE
~4 x header parsing slowdown vs HttpParser.jl

### ISSUE THREAD

**Issue by samoconnor** [JuliaWeb/HTTP.jl#146]
The table below is produced by [`test/benchmark.jl`](https://github.com/JuliaWeb/HTTP.jl/blob/master/test/benchmark.jl)

- setup = Transaction, Request and Stream constructor time.
- head = header parsing time (`startread(::Stream)`)
- body = body parsing time. (`while !eof(::Stream) readavailable(::Stream)`)
- close = cleanup time (`closeread(::Stream)`)
- joyent_head = [HttpParser.jl](https://github.com/JuliaWeb/HttpParser.jl) header parsing time [(`Parser()`,  `http_parser_init()`, & `http_parser_execute()`)](https://github.com/JuliaWeb/HTTP.jl/blob/master/test/http_parser_benchmark.jl#L89).
- jl_slower = head / joyent_head

|     Response |        setup |         head |         body |        close |  joyent_head |    jl slower |
| ------------:| ------------:| ------------:| ------------:| ------------:| ------------:| ------------:|
|     github:  |     1.881 μs |    87.102 μs |     3.776 μs |    14.967 μs |    20.238 μs |        x 4.3 |
|  wikipedia:  |     2.304 μs |    66.559 μs |     0.248 μs |     3.376 μs |    20.396 μs |        x 3.3 |
|    netflix:  |     1.873 μs |   110.237 μs |     3.413 μs |    16.789 μs |    21.727 μs |        x 5.1 |
|    twitter:  |     4.411 μs |   173.006 μs |     0.318 μs |     13.82 μs |    22.683 μs |        x 7.6 |
|     akamai:  |     1.066 μs |    21.532 μs |     0.242 μs |      5.17 μs |    10.706 μs |        x 2.0 |
|    nytimes:  |     3.435 μs |   119.494 μs |     0.304 μs |    13.175 μs |    23.834 μs |        x 5.0 |

**Comment by samoconnor** [comment]
After ccb709157a5ca65947ecc86da054b8486baa666c, HTTP.jl is ~1.4 x faster.

|     Response |        setup |         head |         body |        close |  joyent_head |    jl faster |
| ------------:| ------------:| ------------:| ------------:| ------------:| ------------:| ------------:|
|     github:  |    122.26 μs |     28.24 μs |      54.4 μs |     18.08 μs |     34.85 μs |        x 1.2 |
|  wikipedia:  |      7.78 μs |     15.38 μs |      11.6 μs |       4.0 μs |      22.4 μs |        x 1.5 |
|    netflix:  |    123.02 μs |     29.46 μs |     65.81 μs |     20.01 μs |     36.94 μs |        x 1.3 |
|    twitter:  |     29.85 μs |     16.22 μs |     11.84 μs |     15.34 μs |     22.54 μs |        x 1.4 |
|     akamai:  |      1.86 μs |      5.67 μs |      6.67 μs |      5.71 μs |     14.41 μs |        x 2.5 |
|    nytimes:  |      19.2 μs |     15.99 μs |     17.24 μs |     12.89 μs |     23.65 μs |        x 1.5 |

**Comment by quinnj** [comment]
Nice!

**Comment by jingpengw** [comment]
cool!!
