### ISSUE TITLE
HTTP.ParsingError: invalid HTTP request target, es_dead, 0

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HTTP.jl#149]
![image](https://user-images.githubusercontent.com/8954730/35113268-6e031c4c-fcb3-11e7-8684-ca61c0084a1f.png)

Then I open the browser at `http://localhost:8000` and it displays

```
HTTP.ParsingError: invalid HTTP request target, es_dead, 0
```

**Comment by samoconnor** [comment]
Hi @EricForgy,
I'll need to see what caused the parsing error. Can you set `DEBUG_LEVEL=3` and post the log?
Also, whenever you post output logs, it would be preferable to paste the text into \`\`\` tags rather than posting a screenshot.

**Comment by samoconnor** [comment]
I see the problem: a6e4d1e049af81b7372ca44da5288a79c4fed076

**Comment by samoconnor** [comment]
I've also improved the parse error message 88f086a1a3920315d666b48ae720004600f4391f
```
HTTP.ParsingError: invalid HTTP request target, es_dead, 0
"Hello World!"
            ^
```

**Comment by EricForgy** [comment]
Awesome! Thank you 😊
