### ISSUE TITLE
Example not working?

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HTTP.jl#150]
```
julia> using HTTP

julia>      HTTP.listen() do request::HTTP.Request
                @show header(request, "Content-Type")
                @show payload(request)
                return HTTP.Response(404)
            end
I- Listening on: 127.0.0.1:8081
I- Accept:  �    0↑     0↓    127.0.0.1:8081:8081 ≣16
I- Accept:  �    0↑     0↓    127.0.0.1:8081:8081 ≣16
I- Accept:  �    0↑     0↓    127.0.0.1:8081:8081 ≣16
E- UndefVarError(:header)
E- UndefVarError(:header)
I- Closed:  �    0↑     0↓�   127.0.0.1:8081:8081 ≣16 inactive 17.3s
I- Closed:  �    0↑     0↓�   127.0.0.1:8081:8081 ≣16 inactive 17.3s```
```

When I open the browser, it says `UndefVarError: header not defined`.

**Comment by samoconnor** [comment]
HTTP.header?

**Comment by EricForgy** [comment]
I am not sure what the expected behavior is, but yeah, that looks like an issue. Should I submit a PR for the docs?

**Comment by samoconnor** [comment]
Perhaps its best to spend some time figuring it out and getting your code working, then submitting a PR for whatever doc problems you find all in one go?

**Comment by EricForgy** [comment]
That makes sense 👍 😊

**Comment by EricForgy** [comment]
```
     HTTP.listen() do http::HTTP.Stream 
         @show http.message 
         @show header(http, "Content-Type") 
         while !eof(http) 
             println("body data: ", String(readavailable(http))) 
         end 
         setstatus(http, 404) 
         setheader(http, "Foo-Header" => "bar") 
         startwrite(http) 
         write(http, "response body") 
         write(http, "more response body") 
     end 
```

I guess now `startwrite` should be `HTTP.IOExtras.startwrite`. Is it better to `using IOExtras` so we can make that `HTTP.startwrite`?

**Comment by samoconnor** [comment]
In the other examples in HTTP.jl we do `using HTTP.IOExtras` so we can say just `startwrite`. 
https://github.com/JuliaWeb/HTTP.jl/blob/88f086a1a3920315d666b48ae720004600f4391f/src/HTTP.jl#L236-L250

**Comment by EricForgy** [comment]
```
using HTTP.IOExtras 
  
 HTTP.open("GET", "https://tinyurl.com/bach-cello-suite-1-ogg") do http 
     n = 0 
     r = startread(http) 
     l = parse(Int, header(r, "Content-Length")) 
     open(`vlc -q --play-and-exit --intf dummy -`, "w") do vlc 
         while !eof(http) 
             bytes = readavailable(http) 
             write(vlc, bytes) 
             n += length(bytes) 
             println("streamed \$n-bytes \$((100*n)÷l)%\\u1b[1A") 
         end 
     end 
 end 
```

The above won't work because you also need `using HTTP` and the `header` should be `HTTP.header` at which point, it feels better (to me) to just do 

```
using HTTP
  
 HTTP.open("GET", "https://tinyurl.com/bach-cello-suite-1-ogg") do http 
     n = 0 
     r = HTTP.startread(http) 
     l = HTTP.parse(Int, HTTP.header(r, "Content-Length")) 
     open(`vlc -q --play-and-exit --intf dummy -`, "w") do vlc 
         while !eof(http) 
             bytes = readavailable(http) 
             write(vlc, bytes) 
             n += length(bytes) 
             println("streamed \$n-bytes \$((100*n)÷l)%\\u1b[1A") 
         end 
     end 
 end 
```

Hmm...

**Comment by samoconnor** [comment]
> you also need using HTTP

I think its safe to assume in the doc for package `HTTP` that the user has done `using HTTP`.

`HTTP.parse` makes no sense as a way to call `Base.parse` to convert a `String` to an `Int.

`startread`, `startwrite`, `closeread` and `closewrite` are intended to eventually be in the global namespace. I think for now we should either export them from HTTP, or the examples should include `using HTTP.IOExtras`.

**Comment by EricForgy** [comment]
Would you be open to a PR that exports `[start|close][read|write]` from HTTP? For noobs like me, I think I prefer not to have to run `using` more than once for a single package before I can see a simple example.

**Comment by EricForgy** [comment]
Docs refer to `HTTP.KILL`, but it is `HTTP.Servers.KILL`

**Comment by samoconnor** [comment]
I think it might be cleanest to remove the `HTTP.Servers.Server` and `HTTP.Servers.serve` docs and leave the functions for now for backwards compatibility. The handlers stuff may need to be tweaked a little to fit with `HTTP.listen`'s `f(::Request) -> ::Response` pattern. I believe that the handlers stuff uses a pattern like `f(::Request, ::Response) -> ::Response` 

@quinnj  is there a feature that `HTTP.Servers.Server` or `HTTP.Servers.serve` has that `listen` doesn't that I'm forgetting about?

( GitHub.jl is now using `listen` : https://github.com/JuliaWeb/GitHub.jl/pull/102/files#diff-91d13e6f489f508c1d1e0f88f1e6bbb8R126 )
