### ISSUE TITLE
HTTP.WebSockets served from the same port

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HTTP.jl#156]
This is more of a feature request that I will try myself, but thought I'd go ahead and create an issue first.

Now, we have `HTTP.Servers.Server.listen` and `HTTP.WebSockets.listen`. It would be nice to have a `listen` that works with both HTTP and WS on the same port.

I think it is as simple as taking the guts from `Server.listen` and `WebSockets.listen` and creating a new `listen` that is dispatched on if given both an HTTP handler and a WS handler (or some other flag).

**Comment by samoconnor** [comment]
Try this out: https://github.com/JuliaWeb/HTTP.jl/commit/56f628bd379dfd7b50344695ae8dbdde42730217
I've split the guts from `WebSockets.listen` into a new `WebSockets.upgrade`...

server:
```julia
HTTP.listen() do http
   if http.message.target == "/hello"
       write(http, "Hello!")
   elseif http.message.target == "/ws"
       HTTP.WebSockets.upgrade(http) do ws
           while !eof(ws);
               print(String(readavailable(ws)))
           end
       end
   end
end
```

client:
```julia
HTTP.request("GET", "http://localhost:8081/hello")

io = BufferStream()
@async HTTP.WebSockets.open("ws://localhost:8081/ws"; verbose=true) do ws
    write(ws, io)
 end
write(io, "foo")
```

**Comment by EricForgy** [comment]
Awesome. Will give it a try.

Would it make sense to add `ws` and `wss` as `Scheme`s ?

https://github.com/JuliaWeb/HTTP.jl/blob/621e25f447cd8493a7cc4d88dcc020fca0047523/src/Servers.jl#L62-L64

**Comment by samoconnor** [comment]
> Would it make sense to add ws and wss as Schemes ?

No, I don't think so. I don't think the concept of `scheme` is relevant to the server API: `HTTP.listen([host="localhost" [, port=8081]]; ssl=false, ...) do ::HTTP.Stream ...`.
The server just listens on a certain port, with or without encryption.

**Comment by EricForgy** [comment]
I'm spinning my wheels and think I see a problem...

To have HTTP and WS handled by the same port, then we need a `listen` that takes an `http::HTTP.Stream` in the `do` and switches behavior depending on whether there is a WS upgrade.

If there is an upgrade, then we can use the new `HTTP.WebSockets.upgrade`. No problem (I think - I'll climb that mountain when I get there 😅)

If there is not an upgrade, then I want to use `HTTP.handle(router::HTTP.Router,request::HTTP.Request)`.

BUT... we don't have `request::HTTP.Request`. We have  `http::HTTP.Stream`. So I try

```
HTTP.handle(router,http.message)
```

This runs, but then `listen` goes through

- `handle_connection`
- `handle_transaction`
- `handle_stream`

`handle_stream` then checks to see if my original handler is applicable to streams.

https://github.com/JuliaWeb/HTTP.jl/blob/master/src/Servers.jl#L455-L459

```
       if applicable(f, http)
            f(http)
        else
            handle_request(f, http)
        end
```

We want to trigger `handle_request`, but our handler `req -> res` actually does except a stream and errors because it is expecting a request.

The way to get `listen` to trigger `handle_request` is to specify 

```
HTTP.listen(ip"127.0.0.1",p) do request::HTTP.Request
```

but we need

```
HTTP.listen(ip"127.0.0.1",p) do http::HTTP.Stream
```

in order to handle HTTP and WS on the same port.

Am I making any sense? 😅 

By now I've tried a ton of things including writing an `HTTP.handle(r::HTTP.Router,s::HTTP.Stream)` and writing handlers (functors?) that convert a function `(req) -> (res)` => `(http) -> (resp)`, but I'm at the limit of my abilities and everything I try seems convoluted.

Any ideas?

Note: HttpServer.jl let me write a `WebSocketHandler` and `HttpHandler` and feed this into the equivalent of `listen`. I think we might need something similar here.

**Comment by samoconnor** [comment]
Why not just call `HTTP.Servers.handle_request(f::Function, http::Stream)` from your `HTTP.listen() do ::Stream ...` function. The `f` you pass to `handle_request` is `f(::HTTP.Request) -> HTTP.Response`, so you should be able to call `HTTP.handle(router::HTTP.Router,request::HTTP.Request)` from there... Am I missing something?

**Comment by EricForgy** [comment]
I'll try, but could you spell it out a little more for me? 😅 

I'm been staring at this so long, I'm delirious at this point.

**Comment by EricForgy** [comment]
I am probably missing something. I can't put `HTTP.handle` in my `f` because it needs to know the route to determine `f` first 😅 

If I had a method that given a `HTTP.Router` and a `HTTP.Stream` gave me the corresponding `f`, then I could use `HTTP.handle_request(f,http)` 🤔

**Comment by EricForgy** [comment]
I got it! 🎉 

I split `handle(r::Router, req)` into one method that gets the handle and then the next method that calls it.

```
function gethandler(r::Router, req)
    # get the url/path of the request
    m = Val(Symbol(req.method))
    # get scheme, host, split path into strings and get Vals
    uri = HTTP.URI(req.target)
    s = get(SCHEMES, uri.scheme, EMPTYVAL)
    h = Val(Symbol(uri.host))
    p = uri.path
    segments = split(p, '/'; keep=false)
    # dispatch to the most specific handler, given the path
    vals = (get(r.segments, s, EMPTYVAL) for s in segments)
    return r.func(m, s, h, vals...).func
end

function handle(r::Router, req)
    handler = gethandler(r,req)
    # pass the request to the handler and return
    return handle(handler, req, vals...)
end
```

Then I renamed `handle_request` to `HTTP.handle` so it is just another `handle` method we can use outside `HTTP.Servers`.

The final `listen` looks like this:

```
Base.convert(::Type{HTTP.Response},s::String) = HTTP.Response(200,s)

function start(p = 8000)
    global port = p
    HTTP.listen(ip"127.0.0.1",p) do http
        println(http.message.target)
        if is_upgrade(http.message)
            println("Upgraded websocket")
        else
            handler = HTTP.handler(router,http.message)
            HTTP.handle(handler,http)
        end
    end
end
```

Oh yeah, I also added a `convert` method that I think makes sense and I needed to get this to work 😅  

What do you think? 🙏
