### ISSUE TITLE
Example API endpoints?

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HTTP.jl#157]
I just noticed `HTTP.Handlers` 😍 

This "handles" a lot of the stuff I implemented in Pages.jl, so once I understand how this works, I can incorporate there. The reason I wrote Pages.jl is that:

1. Mux.jl was too advanced for me at the time and my eyes glazed over when I tried to understand it.
2. I needed API endpoints for a financial modeling Web application.

I trust myself much more with building financial models than writing middleware (I didn't know what middleware meant when I started Pages.jl 😅 )

I'm guessing you are using HTTP.jl on AWS. We're on Azure 😊 That detail aside, would you mind sharing what an example API endpoint implementation would look like using HTTP.jl? Preferably we could see one example without authentication and one with authentication. We'll probably run Julia as a microservice on ASF and not expose it to the internet, but understanding how to do authentication would open the possibility of making it visible.

Thanks! The more I learn about HTTP.jl, the more I like it 👍

**Comment by quinnj** [comment]
[these](https://github.com/JuliaWeb/HTTP.jl/blob/master/test/handlers.jl) are probably the best examples for now, but I agree, we should have a few more docs.

**Comment by EricForgy** [comment]
FYI: Pages.jl has been updated to use `HTTP.Handlers`. Much cleaner I think but the simple interface API remains the same:

```
Endpoint("/examples") do request::HTTP.Request
    readstring(joinpath(dirname(@__FILE__),"examples.html"))
end
```

Now it is pretty much just a little sugar for `HTTP.Handlers`. Next, I'll try to recover the WS functionality for interactivity between Julia and JS.

**Comment by amellnik** [comment]
Here's what I would consider a minimal API example using just HTTP:

```julia
using HTTP, JSON
import HTTP.IOExtras.bytes

# Define a bunch of middleware layers that take the request and response and return
# modified copies
function add_headers(req::HTTP.Request, res::HTTP.Response)
    push!(res.headers, Pair("Access-Control-Allow-Origin", "*"))
    push!(res.headers, Pair("Access-Control-Allow-Methods", "POST, GET"))
    push!(res.headers, Pair("Content-Type", "application/json"))
    return (req, res)
end

function set_status(req::HTTP.Request, res::HTTP.Response)
    res.status = 200
    return (req, res)
end

our_middleware = [add_headers, set_status]

# A endpoint is just like any other middleware but it should probably do things like
# populate the response body
function endpoint1(req::HTTP.Request, res::HTTP.Response)
    res.body = bytes(JSON.json(Dict("Message"=>"Test")))
    return (req, res)
end

# A function to combine layers -- presumably something like this would be added 
# to HTTP or would be left to packages like an updated Mux
function stack(layers)
    return function(req::HTTP.Request)
        res = HTTP.Response()
        for l in layers
            println(typeof(l))
            (req, res) = l(req, res)
        end
        return res
    end
end

router = HTTP.Router()

# Do something like this for each endpoint
HTTP.register!(router, "GET", "/test", stack([our_middleware..., endpoint1]))

s = HTTP.Servers.Server(router) 
HTTP.serve(s, ip"127.0.0.1", 8000; verbose=false)
```

There's at least two big missing pieces -- there's no way for middleware to return a response and ignore the remainder of the stack, and there's also not any way to cleanly capture errors.

**Comment by amellnik** [comment]
Copying two comments @quinnj made on Slack to make sure it doesn't get lost:

----

With HTTP.Handlers, it makes it pretty straightforward to implement your own middleware. for your example (including some headers in every response), you could do something like
```julia
struct ResponseHeaderHandler{H <: HTTP.Handler} <: HTTP.Handler
    handler::H
end
ResponseHeaderHandler(f::Function) = ResponseHeaderHandler(HTTP.HandlerFunction(f))

function HTTP.handle(r::ResponseHeaderHandler, req)
    # first dispatch to inner handler
    res = HTTP.handle(r.handler, req)
    # now that we have a response, let's modify before returning
    push!(res.headers, Pair("Access-Control-Allow-Origin", "*"))
    push!(res.headers, Pair("Access-Control-Allow-Methods", "POST, GET"))
    push!(res.headers, Pair("Content-Type", "application/json"))
    return res
end

HTTP.serve(ip; handler=ResponseHeaderHandler(req -> HTTP.Response(200, "Hello world")))
```

That's hopefully the idea. I experienced some of the same frustration looking thru Mux.jl at one point and thought that surely this could all be simpler.

With `HTTP.Handlers`, it's really about thinking thru the "layers" of your middleware: what should my initial handler be? Some kind of `AuthHandler`? An `HTTP.Router`? Then maybe I want to add some other kind of "filter" handlers, checking for certain headers and returning appropriate responses if conditions aren't meant. At some point in the stack, you'll eventually reach an `HTTP.HandlerFunction` whose definition is entirely

```julia
struct HandlerFunction{F <: Function} <: Handler
    func::F # func(req)
end
handle(h::HandlerFunction, req) = h.func(req)
```
That inner most handler function is what dispatches to business logic, does calculations, etc.
Then you can have "post-response" handlers like the `ResponseHeaderHandler` or a `CookieSetterHandler`

Eventually, we might include a few more "builtin" handlers in HTTP itself, but I've found they often tend to be pretty specific to a particular use-case, so it can be tricky to find ones that really generalize. Hence why we only include `HTTP.HandlerFunction` and `HTTP.Router` at the moment.

**Comment by EricForgy** [comment]
Quick comment:

```julia
function endpoint1(req::HTTP.Request, res::HTTP.Response)
    res.body = bytes(JSON.json(Dict("Message"=>"Test")))
    return (req, res)
end
```

You don't need to include the `HTTP.Response` argument. We removed those from all handlers because the `HTTP.Request` object already contains an `HTTP.Response` field.

**Comment by Nosferican** [comment]
What's the status on this?

**Comment by quinnj** [comment]
The HTTP.Handlers module has a pretty extensive example now for setting up a simple REST server w/ CRUD endpoints, using the handlers framework, extending, etc.
