### ISSUE TITLE
Remove Response argument if not needed

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HTTP.jl#158]
A `HandlerFunction` is of the form `(req,res) -> res`.

If the handler does not depend on `res`, we could do something like `(req,Response()) -> res`, but that feels like a waste to construct an object `Response()` that isn't needed. Is the compiler smart enough to optimize that away or does it really construct a `Response()` object?

In Pages, I imported `handle` and made these changes to make it work in order to avoid an empty `Response()`

```
SCHEMES = HTTP.Handlers.SCHEMES
EMPTYVAL = HTTP.Handlers.EMPTYVAL
HTTP.handle(h::HTTP.HandlerFunction,req::HTTP.Request) = h.func(req)
function HTTP.handle(r::HTTP.Router, req::HTTP.Request)
    # get scheme, host, split path into strings and get Vals
    m = Val(Symbol(req.method))
    # get the url/path of the request
    uri = HTTP.URI(req.target)
    s = get(SCHEMES, uri.scheme, EMPTYVAL)
    h = Val(Symbol(uri.host))
    p = uri.path
    segments = split(p, '/'; keep=false)
    # dispatch to the most specific handler, given the path
    vals = (get(r.segments, s, EMPTYVAL) for s in segments)
    handler = r.func(m, s, h, vals...)
    # pass the request & response to the handler and return
    return HTTP.handle(handler, req)
end
```

If there is no penalty for doing `(req,Response()) -> res`, I can just do this, otherwise, would you be open for a PR of the form above?

**Comment by samoconnor** [comment]
Every Request object already has a Response object attached, see line 188:
https://github.com/JuliaWeb/HTTP.jl/blob/f9837eb563187559260a84cdc5d24aaca72b5bed/src/Messages.jl#L181-L192

`HandlerFunction` should probably be changed to (::Request) -> ::Response.

That would be consistent with the `listen` function:
https://github.com/JuliaWeb/HTTP.jl/blob/f9837eb563187559260a84cdc5d24aaca72b5bed/src/Servers.jl#L273-L277

**Comment by EricForgy** [comment]
Want me to take a stab at a PR?

**Comment by samoconnor** [comment]
Sounds good.
