### ISSUE TITLE
Default User-Agent ?

### ISSUE THREAD

**Issue by oxinabox** [JuliaWeb/HTTP.jl#161]
The Github API requires that the User-Agent be set.
https://developer.github.com/v3/#user-agent-required

It was working for me in 0.5.7 but it is not in master.
Ergo, I suspect something changed.

**Comment by samoconnor** [comment]
It has always seemed to me that a HTTP interface library should not set a User-Agent field by default.

https://tools.ietf.org/html/rfc7230#section-2.1 :
_The term  "user agent" refers to any of the various client programs that
   initiate a request, including (but not limited to) browsers, spiders
   (web-based robots), command-line tools, custom applications, and
   mobile apps._

It doesn't seem that useful for all the different "browsers, web-based robots, command-line tools, custom applications, and mobile apps" that use HTTP.jl to have the same User-Agent header.

https://tools.ietf.org/html/rfc7231#section-5.5.3 :
_[the User-Agent header] is often used by servers to help
   identify the scope of reported interoperability problems, to work
   around or tailor responses to avoid particular user agent
   limitations_

Interoperability problems or user agent limitations are more likely to be at the application level than the HTTP.jl library level.

The GitHub API spec has its own application specific requirements for the User-Agent header value:
https://developer.github.com/v3/#user-agent-required
_We request that you use your GitHub username, or the name of your application, for the User-Agent header value._

This is how GitHub.jl does it : https://github.com/JuliaWeb/GitHub.jl/blob/kc/http2/src/utils/requests.jl#L57

**Comment by oxinabox** [comment]
You are correct.
I was thinking a default header, with the docs suggesting that it be set by the application.
My logic was it would be better to give the server some information:
i.e. that it is a Julia application, and that it is using HTTP.jl,
than no information.
And then tell the users of HTTP.jl to set it with better information.

But perhaps not,
since not forces the user to give good information themselves when it matters.

**Comment by oxinabox** [comment]
for libraries some do and some don't

looking at:
https://github.com/nodejs/node-v0.x-archive/issues/4552
and doing some googling:

 - PHP no
 - Libcurl no
 - node.jl no
 - .Net no
 - Ruby Net::HTTP yes
 - Python urllib  yes
 - Python urllib2 yes

**Comment by oxinabox** [comment]
What might be nice to do, is have a method:
`set_useragent!(useragent)`
which could be call call after loading all your packages
(and should be documented as good practice to use any time you `using HTTP`).

This would set a global in HTTP.jl,
which would insert the user-agent into the headers by default.

This could either override previous values of that global,
or it could prepend(/append) to them.
Either way, the info from the lasts `set_useragent!` would be included in the user-agent sent even by dependencies of the package's dependencies.

Possibly even:
`set_useragent!(PkgName)`
Which would set the user-agent to something like:
`"$PkgName $(Pkg.installed(PkgName)); HTTP.jl  $(Pkg.installed("HTTP")); julia "`
Which might be good so people watching web-servers can identify if a buggy library of a particular version is thrashing them.
Might be over engineered though.
