### ISSUE TITLE
How to identify a WebSocket?

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HTTP.jl#164]
The old `WebSockets.WebSocket` had a field `id`, i.e.

https://github.com/JuliaWeb/WebSockets.jl/blob/master/src/WebSockets.jl#L53

```
type WebSocket
    id::Int
    socket::TCPSock
    state::ReadyState

    function WebSocket(id::Int,socket::TCPSock)
        init_socket(socket)
        new(id, socket, CONNECTED)
    end
end
```

The `id` can be used for communication.

I don't see any way to identify a HTTP.WebSockets.WebSocket.

```
mutable struct WebSocket{T <: IO} <: IO
    io::T
    frame_type::UInt8
    server::Bool
    rxpayload::Vector{UInt8}
    txpayload::Vector{UInt8}
    txclosed::Bool
    rxclosed::Bool
end
```

Am I missing something?

What would be a good way to allow us to identify individual WebSockets in HTTP for communication / chat?

**Comment by samoconnor** [comment]
It seems odd to have an id field in struct WebSocket that is not used anywhere in HTTP/src/WebSockets.jl.
If you need an application-level ID, why not keep all your WebSockets in a `Dict` or a `Vector` keyed by id?

**Comment by EricForgy** [comment]
I thought you might say that and it sounds reasonable to me. Thank you 😊 

PS: I'm learning a lot. Thanks for your patience! 🙌
