### ISSUE TITLE
Verbosity level of error messages

### ISSUE THREAD

**Issue by KristofferC** [JuliaWeb/HTTP.jl#166]
Right now, an error message looks like:

```
I- Accept:  🔗    0↑     0↓    0.0.0.0:16399:16399 ≣16
I- Accept:  🔗    0↑     0↓    0.0.0.0:16399:16399 ≣16
E- IOError(EOFError())
I- Accept:  🔗    0↑     0↓    0.0.0.0:16399:16399 ≣16
```

I would argue `E- IOError(EOFError())` is a bit too terse. What happened? What is the severity etc?

**Comment by samoconnor** [comment]
In Julia v0.7, the "E-" message includes the file and line number.
In the meantime I've tried to make things more descriptive in this commit: 5f49cd6dffa4f8b479b4fa66d0bdb9a3827b3653
Please let me know if this helps.

Also, did the client get a 500 error response in your case?

**Comment by samoconnor** [comment]
See also #189

**Comment by samoconnor** [comment]
Closing in favour of #189. @KristofferC please follow up there if you have any more feedback on this. Thanks.
