### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HTTP.jl#168]
There has been a lot of progress with HTTP after merging https://github.com/JuliaWeb/HTTP.jl/pull/135 and some subsequent clean up.

Several people, e.g. myself, @oxinabox, @ararslan , etc, would like a tag so we can update our packages 😊 

What is left to do before that can happen?

**Comment by quinnj** [comment]
I'm going to make a big push on 0.7 compat tonight to get tests passing and there are a few deprecations to clean up (I have a couple changes locally). If things go smoothly, I think we should be ready for a tag tonight/tomorrow.

@samoconnor, anything else you're working on or want to get in before a new tag?

**Comment by ararslan** [comment]
Anything else to do now that #171 has been merged?

**Comment by quinnj** [comment]
I'm checking out HTTP dependencies tonight and hopefully won't run into too many unrelated compat problems trying to test if we've broken anything too badly.

**Comment by quinnj** [comment]
ok, #175 is the last thing I want to get in before tagging, so pending good CI, I'll merge and tag. If anyone has other issues/concerns, speak now or..........wait till the next release!

**Comment by EricForgy** [comment]
Yay! 🎉
