### ISSUE TITLE
convert(::Type{HTTP.Response},s::String)

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HTTP.jl#177]
Strictly speaking, a handler takes an `HTTP.Request` and returns an `HTTP.Response`. However, it is often convenient to take a `HTTP.Request` and return a `String`.

For my package, I've added this, which is handy:
```
Base.convert(::Type{HTTP.Response},s::String) = HTTP.Response(200,s)
```

Would you guys be open to adding this to HTTP.jl? I can submit a PR.

**Comment by samoconnor** [comment]
Currently we have `Response(bytes) = parse(Response, bytes)`, but I'd be open to `Response(bytes) = Response(200; body=bytes)` (and the matching `convert` method).

**Comment by samoconnor** [comment]
See https://github.com/JuliaWeb/HTTP.jl/blob/4a4e1ac06866d9f58e187ae241be347aad08f5cd/src/Messages.jl#L137

**Comment by EricForgy** [comment]
If I understand, then we just need:

```
Base.convert(::Type{HTTP.Response},s::String) = HTTP.Response(s)
```

Assuming that is the case, I'll go ahead and submit a PR 😊
