### ISSUE TITLE
How to use custom error handling?

### ISSUE THREAD

**Issue by amellnik** [JuliaWeb/HTTP.jl#196]
What's the recommended way to replace the built-in error handler, or more generally, replace one of the Request Execution Layers?

**Comment by samoconnor** [comment]
There is an example [here](https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/http.jl#L17) of creating a custom `const http_stack` which is then passed as the first argument to `request`.

The `HTTP.stack` function is [here](https://github.com/JuliaWeb/HTTP.jl/blob/master/src/HTTP.jl#L539), it has a bunch of kw args to enable/disable various layers. These kw args can also simply be passed to the `request` function. e.g. `HTTP.request("GET", "http://foobar.com"; status_exception=false, retry=false, redirect=false)`

Or you can create a minimal stack by hand like this:
```julia
stack = HTTP.MessageLayer{HTTP.ConnectionPoolLayer{HTTP.StreamLayer}}
```

To create a custom layer, start with something simple like [this](https://github.com/JuliaWeb/HTTP.jl/blob/master/src/CanonicalizeRequest.jl) as an example, then create a stack that includes your new layer:
```julia
stack =
    HTTP.RedirectLayer{
    HTTP.MessageLayer{
    MyModule.MyNewLayer{
    HTTP.RetryLayer{
    HTTP.ConnectionPoolLayer{
    HTTP.StreamLayer}}}}}
```

Can you describe specifically what behaviour you would like to disable/change/add... ?

**Comment by amellnik** [comment]
Thanks!  I'm currently working through a checklist of all the middleware I commonly use in Node to figure out how it can be done in HTTP with the goal of submitting examples to the documentation.  For error handling in an API I usually want to do something more complicated than the default behavior in HTTP which returns a stringed version of the error that was thrown in the response body.  For the WebAssembly conversion project I would return something like 

```json
{
  "error": true,
  "message": "Unable to generate bitcode...",
  "stdio_logs" :"..."
}
```
with the response.

**Comment by samoconnor** [comment]
Note that the layer/stack stuff above applies to the client side.
On the client side, the `StatusError` has a reference to the `HTTP.Response` object.
https://github.com/JuliaWeb/HTTP.jl/blob/b7b8e0f8c5baf1fd39c529fc264cb74284538fe3/src/ExceptionRequest.jl#L35-L38

On the server side, inside your `HTTP.listen() do ... end` block, you can have a `try/catch` that handles whatever application specific error types you have and translates them into a rich `HTTP.Response` JSON or HTML page.

```julia
HTTP.listen() do request::HTTP.Request
    try
        my application code
        return HTTP.Response( ... )
    catch e
        if e isa MyFoo
            return HTTP.Response(404, body = my_pretty_message(e))
        if e isa MyBar
            return HTTP.Response(500, body = get_my_debug_json(e))
        else
            rethrow(e)
        end
    end
end
```

**Comment by amellnik** [comment]
I ended up doing something similar to wrap all my route handlers in a try/catch block: https://github.com/amellnik/Joseki.jl/blob/master/src/Joseki.jl#L22-L40.  I'm working on documentation for this and a few similar items.
