### ISSUE TITLE
Too early query escaping?

### ISSUE THREAD

**Issue by bicycle1885** [JuliaWeb/HTTP.jl#20]
I'm not perfectly sure, but query escaping looks too early to me. For example, the following effectively-equivalent URIs aren't equal in Julia:

```
julia> HTTP.URI("http://example.com?query=foo/bar")
HTTP.URI("http://example.com?query=foo/bar")

julia> HTTP.URI("http://example.com", query=Dict("query"=>"foo/bar"))
HTTP.URI("http://example.com?query=foo%2Fbar")

julia> HTTP.URI("http://example.com?query=foo/bar") == HTTP.URI("http://example.com", query=Dict("query"=>"foo/bar"))
false

```

**Comment by quinnj** [comment]
Here's my line of thinking:

  * In the 1st example, it's assumed that the user is providing a valid url, so no escaping is done, whatever you provide as that 1st string argument is taken as-is; this allows cases where the user wants to manually construct, or perhaps already has, a valid url including query/fragment/whatever
  * In the 2nd case, the user is programmatically passing in a query as a `Dict`, in this case, it's assumed that w/ whatever is provided, is probably not been escaped and so is escaped upon construction.

Does that make sense? Any different behavior here that would make this better? I'm certainly open to suggestions, including including more docs around this.

**Comment by bicycle1885** [comment]
I often copy and paste a URL including a query from a web browser and then use HTTP.jl to get the content. Is this URL will be automatically escaped before sent to a server? If not, users may see weird errors if they are not so familiar with percent escaping. IMHO, it would be better to keep human-readable URLs and escape URLs just before submission.

**Comment by quinnj** [comment]
There's a lot of complexity because different parts of the URL actually require different percent-encoding for different character sets. From browsing other repos/stackoverflow, traditionally it's only the query that poses problems, so currently HTTP.jl only escapes query key-value pairs. From what I can tell, at least in google chrome, the url is always properly encoded.
