### ISSUE TITLE
Not able to form an URI starting with String and query

### ISSUE THREAD

**Issue by stefabat** [JuliaWeb/HTTP.jl#203]
Hi,

since last update I am not able to create an URI starting with a string and a query anymore.

I have a string with the endpoint of the online API, and I have a query which is an array of Pairs.
I would like to generate an object of type URI such that it puts together the pieces.
Since last update, I was able to generate an URL (now deprecated) with the command

url = HTTP.URIs.URL(endpoint; query = query)

where endpoint is a string and query is an array of pairs.

How do I do that now?

Cheers

**Comment by samoconnor** [comment]
You can pass `query=` to `HTTP.request` (or `HTTP.get` etc)
https://github.com/JuliaWeb/HTTP.jl/blob/d0ccc8cc21459654c0c809eb37cdbcd3e27fafe5/src/HTTP.jl#L84-L86

Internally this just does:
https://github.com/JuliaWeb/HTTP.jl/blob/d0ccc8cc21459654c0c809eb37cdbcd3e27fafe5/src/HTTP.jl#L299-L302

So, an alternative would be to do this:
```julia
julia> using HTTP

julia> url = merge(HTTP.URI("http://foobar.com"); query = ["a"=>1, "b"=>2])
HTTP.URI("")

julia> string(url)
"http://foobar.com?a=1&b=2"
```
_Note that `show` seems to be broken for `HTTP.URI`, so I've called `string` in the above example to show the result._

**Comment by samoconnor** [comment]
0f6417b should fix the show/print thing.

**Comment by stefabat** [comment]
Thank you,

the `merge` function is what I was looking for.
Nonetheless, I don't get why it is not exposed to the user the possibility to create the URI with a query passed as an argument (similarly to `merge`).
After all, the query it's a property of the URI and indeed is a member of the `URI struct`.
Using `merge` works just fine, but being used (as far as I understand) only internally, if in the future changes, the user is likely to be unaware of that, leading to a broken package.

I understand that I can pass the query argument to the `request` function, but that doesn't cover all use cases.
E.g., in my case I need to construct first the entire address, sign it in some way (SHA or other) and make a `request` with the signed address as `headers`.
For this reason I need to build the entire URL prior to calling `request`...

Cheers

**Comment by samoconnor** [comment]
Thanks for the feedback @stefabat,
I'd like to understand your use case better, and figure out if there is just a documentation issue here, or if the API is fundamentally failing to apply the principle of least surprise.

A few comments:
 - I wouldn't consider `Base.merge` as an internal function. It is an oversight that it is not mentioned in the documentation. `Base.merge` seems like a reasonable API for adding/updating fields of an immutable struct, but I'm open to suggestions for other function names.
 - You can construct a `URI` by parsing a string like this:
    `HTTP.URI("http://foobar.com")`
 - You can construct a `URI` from components like this:
    `HTTP.URI(scheme = "http", host = "foobar.com", query = mydict)`
 - What you can't currently do is `HTTP.URI("http://foobar.com", query = mydict)`, i.e. a mixture of parsing a string and components specified by kw args. This is partly because it seems odd to be merging things in a constructor (that's what merge is for), and partly because its a bit painful to implement because `URI(str)` and `URI(str, kw...)` are seen as the same signature by Julia.
 - Perhaps isn't necessary for you to use or care about the `HTTP.URI` type at all. The documentation for `HTTP.request`, `HTTP.get` etc doesn't mention `HTTP.URI`, all the examples for the `url` argument are strings. Is there a reason you need to use the `HTTP.URI` type?
 - You could just treat URLs as strings in your code and do
   `url = "http://foobar.com?" * HTTP.escapeuri(["a" => 1, "b" => 2])` -> `"http://foobar.com?a=1&b=2"`
   to create your url with a query string appended.

**Comment by stefabat** [comment]
As far as I understand, `Base.merge` is originally merging collections only, while in `HTTP` it is merging/setting members of structs; in this particular case the `URI` struct.
Therefore, I guess that this behavior has been defined somewhere in `HTTP` by overloading `Base.merge` (BTW, not sure overloading is the right term in Julia, it is more a multiple dispatch "thing").
I might be wrong about this, correct me if that is the case.

I'll wait your answer before posting my particular use case.

Cheers

**Comment by samoconnor** [comment]
> As far as I understand, Base.merge is originally merging collections only

That's mostly true. Base uses `merge` for `AbstractDict` and `NamedTuple`. Is `NamedTuple` a collection with field names? or an anonymous struct? 
I guess in my mind, `HTTP.URI` is fairly close in behaviour to being a special type of `NamedTuple`.
Given that `Base` uses the function `merge` for different abstract types, at some point `Base` should document a generic specification for `merge(a, b)`, at that point my guess is that this usage would fit.

As I said:
> Base.merge seems like a reasonable API for adding/updating fields of an immutable struct, but I'm open to suggestions for other function names.

**Comment by stefabat** [comment]
Ok, now I see your point. I wasn't aware of `NamedTuple` and therefore a bit confused.
In this case then, I would add an entry in documentation about `merge` and how to create an `URI` by starting from a string with the endpoint and the query as a collection.

Now, to my use case, I'll try to be concise.
Bear in mind also that this is the first time I do something like this, thus my approach might also be suboptimal or even "wrong"..

I am implementing a REST API for which I basically have two types of function calls.
1) A private communication where I have to `hexdigest` with SHA using a private key the entire url and send the encoded url as headers
2) A public communication which is just a normal GET request to a particular url

In general, I always have an endpoint and a query for both types.

What I have done is implementing a function `apirequest` wrapping `HTTP.request` in order to handle the response and return only the data as I want it.

Clearly, for every function of the REST API, I have implemented a corresponding one in Julia.
Before last update that broke my API, what I was doing was to create a url as follows

    url = HTTP.URIs.URL(endpoint; query = query)

where `endpoint` is a string and `query` a `Vector` of `Pair`.
In this way, in case of private communications I could `hexdigest` directly inside the functions and create the headers I needed.
This is why I was looking for a way to put together the `endpoint` and the `query` prior to calling `HTTP.request`.
Furthermore, for every API function (both public and private) I was returning a call to my wrapper with the following signature, either passing or not the headers depending on the type of communication

    apirequest(url::HTTP.URIs.URL, headers = [])

To summarize, my biggest problem was to find an elegant way to generate the entire url with the query, without me doing it by hand (basically merging together strings).
Doing it with `merge` is good enough, but because nothing was mentioned about it in the docs, I feared that if `merge` changes behavior at a certain point for any reason, I would have found myself again with a broken API.

A little off-topic question here that you might answer me right away:
All my API calls return JSON data that I was able to parse with the following command

    JSON.parse(resp.body)

where `resp` is an instance of `Response`.
Now that doesn't work anymore and I get a bunch of binary stuff.
I cannot understand what has changed.. Do you have a suggestion on how to properly get JSON data and return it as a `Dict` or a `Vector` of `Dict` ?

Thank you
stefabat

**Comment by samoconnor** [comment]
> Do you have a suggestion on how to properly get JSON data and return it as a Dict or a Vector of Dict ?

`resp.body` is a vector of bytes:
https://github.com/JuliaWeb/HTTP.jl/blob/20c454788f6099d32711abf652efdcc3fcaff66a/src/HTTP.jl#L55-L61

You can do `String(resp.body)` to get a string (and `JSON.parse(String(resp.body))` to parse JSON).
You might also want to submit an issue to JSON.jl requesting a convenience method that allows parsing json from a vector of bytes (the JSON RFC says "JSON text exchanged between systems that are not part of a closed ecosystem MUST be encoded using UTF-8", so it seams reasonable to accept `Vector{UInt8}` as input).

Also, there is a `HTTP.payload` function (not yet documented #204).
With this you can to `JSON.parse(HTTP.payload(resp, String))`.
The `resp.body` will always give you the raw bytes. `payload(resp, String)` currently handles `Content-Type: ISO-8859-1` conversion when needed, and may support transparent "gzip" decompression in future.

**Comment by samoconnor** [comment]
> To summarize, my biggest problem was to find an elegant way to generate the entire url with the query, without me doing it by hand (basically merging together strings).

Does your code access the fields of the `HTTP.URI` struct directly? or does it just construct `URI`s from endpoints and queries for the purpose of passing them to `HTTP.request`?

**Comment by stefabat** [comment]
No, I don't access the fields of `HTTP.URI`, down here a snippet of the signed communication

    function getsomething(api, something)
        ... 
        nonce = string(Int(round(time()*1000,0)))
        unshift!(query,["apikey"=>api.apikey,"nonce"=>nonce])
        url        = URIs.URL(endpoint; query = query)
        apisign = hexdigest("sha512", api.apisecret, string(url))
        return apirequest(url, headers=Dict("apisign"=>apisign))
    end

So the main point of defining `url` is that in the case of private communications I can `hexdigest` `string(url)` and get my `apisign` and in the case of public communication I just call `apirequest(url)` and I have a single implementation for `apirequest` that works for both cases.

Thanks for the JSON answer!

**Comment by stefabat** [comment]
I mean, now `URL` is deprecated and I create `url` using `merge` as discussed above, but the rest is the same.

**Comment by samoconnor** [comment]
Given that you're not using the fields of `URI` yourself (i.e. you don't have a need for a URI parser) I would recommend that you ignore the URI type completely and just use the `String` type to manage your URLs.

```julia
queryurl(url, query) = url * HTTP.escapeuri(query)

julia> url = queryurl("http://foobar.com", Dict(["a" => 1, "b" => 2]))
"http://foobar.comb=2&a=1"

julia> url = myapiurl("http://foobar.com", "do/api/thing", Dict(["a" => 1, "b" => 2]))
"http://foobar.com/do/api/thingb=2&a=1"
```

There is no need for you to create a `URI` object. All of the `HTTP.request` functions accept a `String` url. This way, by not using the `URI` type, you are protected against any future changes to the URI type.

**Comment by samoconnor** [comment]
After all, the RFC says: "A URI is an identifier consisting of a sequence of characters", and, in Julia the simplest way to store a sequence of characters is `String`.

**Comment by samoconnor** [comment]
Since you're doing stuff with JSON, you may find this useful: https://discourse.julialang.org/t/announce-a-different-way-to-read-json-data-lazyjson-jl/9046/2

**Comment by samoconnor** [comment]
#205

**Comment by stefabat** [comment]
All right thanks for the discussion! It was very helpful!
I might go for the `String` approach and avoid `URI` completely.

I'll have a look `LazyJSON` too.

Cheers

**Comment by samoconnor** [comment]
No problem.
Be warned that LazyJSON is new and untested :)
