### ISSUE TITLE
Compatibility check makes latest HTTP tag unusable on anything other than v0.6.2 or >= v0.7.0-DEV.4366

### ISSUE THREAD

**Issue by staticfloat** [JuliaWeb/HTTP.jl#210]
[This line](https://github.com/JuliaWeb/HTTP.jl/commit/6663c5a87d357d8c697eb6c74287ff5e8edeea33#diff-92942c0e13e33a2b673529556f61be3aR16) makes it very difficult to use any packages that use `HTTP` on anything other than 0.6.2.  I can understand wanting to restrict support to a single version of Julia, but it's very user-hostile to break any dependent packages by throwing an error during precompilation.

**Comment by staticfloat** [comment]
To be clear, this also breaks things like `0.6.1` and `0.6.3-pre.0`.

**Comment by samoconnor** [comment]
Thanks for pointing that out @staticfloat, I apologise if my approach to this was a bit clumsy.

Please note that [0.7 is still supported](https://github.com/JuliaWeb/HTTP.jl/commit/6663c5a87d357d8c697eb6c74287ff5e8edeea33#diff-92942c0e13e33a2b673529556f61be3aR1).

0.6.1 and 0.6.0 should still work with the previous tag because REQUIRE [now specifies 0.6.2](https://github.com/JuliaWeb/HTTP.jl/commit/6663c5a87d357d8c697eb6c74287ff5e8edeea33#diff-58476995b642435595799e856c5d2a74R1)

**Comment by samoconnor** [comment]
The intention is to match the versions that are tested on travis.

**Comment by staticfloat** [comment]
I see; the situation is better than I thought then.

Still, is there a reason to throw an `error()`?  Why not just print out a warning, then allow things to continue?

**Comment by samoconnor** [comment]
I guess I figured that anyone working with an unreleased 0.6.3-x would be code-savy enough to tweak that like (any maybe even submit a PR).
I've also noticed that a lot of the user issues I help out with end up being version related so I feel like it's better to unequivocally support a particular set of configurations.

But, I'm happy to change it to a warning. Do you think this would do... ?
```julia
@static if VERSION >= v"0.7.0-DEV.4366"
    ... 0.7 stuff
else if VERSION > v"0.7.0-DEV" || VERSION < v"0.6.2" 
    warn("HTTP.jl has not been tested with Julia version $VERSION")
else
    ... 0.6 stuff
end
```

**Comment by staticfloat** [comment]
> I've also noticed that a lot of the user issues I help out with end up being version related

Yeah, I can sympathize.

> Do you think this would do... ?

Yes, that looks good to me.  I also wouldn't rely on `REQUIRE` too much, as it's pretty common practice to tell users "if a package doesn't do something like you think it should, try to `Pkg.checkout()` and try again", so I would not be surprised at all for you to have a few users on `0.6.0` or `0.6.1` hit the error.  That being said, still having a `warn()` is probably a good idea, although you may want to put it into `__init__()` instead of in the top-level source, so that it is printed out at `using HTTP` time instead of precompilation time.

**Comment by samoconnor** [comment]
> I also wouldn't rely on REQUIRE too much, as it's pretty common practice to tell users "if a package doesn't do something like you think it should, try to Pkg.checkout() and try again", so I would not be surprised at all for you to have a few users on 0.6.0 or 0.6.1 hit the error. 

:)  That's precisely the audience I had in mind. I think we need to herd people towards the latest versions to avoid ending up at "Is that Julia 2.7 ? or 3.5?".
