### ISSUE TITLE
Decode payload body based on message body `Transfer-Encoding`.

### ISSUE THREAD

**Issue by samoconnor** [JuliaWeb/HTTP.jl#217]
> "The Transfer-Encoding header field lists the transfer coding names corresponding to the sequence of transfer codings that have been (or will be) applied to the payload body in order to form the message body."
_https://tools.ietf.org/html/rfc7230#section-3.3.1_

The `Messages.payload` function calls `Messages.decode`, but that function does not yet do anything:

https://github.com/JuliaWeb/HTTP.jl/blob/b602c4ea0cf346b35ae9bea13db2c960eee759de/src/Messages.jl#L386-L389
https://github.com/JuliaWeb/HTTP.jl/blob/b602c4ea0cf346b35ae9bea13db2c960eee759de/src/Messages.jl#L395-L401

**Comment by quinnj** [comment]
Dup of #256
