### ISSUE TITLE
Is proxy support useful?

### ISSUE THREAD

**Issue by samoconnor** [JuliaWeb/HTTP.jl#218]
@ignaciomartin asked about proxy support a while back: https://github.com/JuliaWeb/HTTP.jl/issues/4#issuecomment-311885194

I remember the importance of getting my proxy settings right in Netscape Navigator and tuning my SLIP MTUs in Trumpet Winsock in 1994. But, does anyone need to explicitly configure a proxy in 2018?
In my experience ISP and corporate proxies are usually transparent these days.

Please excuse my ignorance if there is still a use case for configuring a proxy.
If you need this, please describe what you need here and/or submit a PR.

![](http://www.metronet.lib.mi.us/help/OtherHelpTopics/DNS/trumpet1.gif)
![](http://startupbeat.hkej.com/wp-content/uploads/2016/08/internet-24aug.jpg)

**Comment by amellnik** [comment]
Npm, Atom, Bower, Julia (the package manager), Anaconda/pip, wget, curl, docker, rust and many others would all not work on my system if I didn't have `HTTP_PROXY` defined (or provided the settings in a dotfile somewhere).  Judging from the prevalence of StackOverflow and similar questions about proxy configurations I think this is still fairly common.

**Comment by samoconnor** [comment]
See : https://github.com/JuliaWeb/HTTP.jl/pull/219/files

Example below of `proxy="http://127.0.0.1:8888"` option.

This supports HTTP only (not HTTPS) at present.

Is tunneling the a HTTPS connection through a proxy [via the `CONNECT` method](https://github.com/JuliaWeb/Requests.jl/blob/master/src/streaming.jl#L190-L202) a useful feature too?

```julia
julia> HTTP.request("GET", "http://httpbin.org/ip"; verbose=3, proxy="http://127.0.0.1:8888")
DEBUG: a7be 🗑  Deleted:        💀    1↑     1↓    127.0.0.1:8888:0 ≣16 RawFD(-1)
DEBUG: a7be TCP connect: 127.0.0.1:8888...
DEBUG: a7be 🚷  No Retry: GET http://httpbin.org/ip HTTP/1.1, connect: connection refused (ECONNREFUSED) not recoverable,
ERROR: connect: connection refused (ECONNREFUSED)

julia> run(`brew install tinyproxy`)

julia> run(`tinyproxy`)

julia> HTTP.request("GET", "http://httpbin.org/ip"; verbose=3, proxy="http://127.0.0.1:8888")
DEBUG: 2f4a TCP connect: 127.0.0.1:8888...
DEBUG: 2f4a 🔗  New:            🔗    0↑     0↓    127.0.0.1:8888:0 ≣16 RawFD(17)
DEBUG: 2f4a 👁  Start write:T0  🔗    0↑     0↓    127.0.0.1:8888:0 ≣16 RawFD(17)
➡️   "GET http://httpbin.org/ip HTTP/1.1\r\n"
➡️   "Host: httpbin.org\r\n"
➡️   "Content-Length: 0\r\n"
➡️   "\r\n"
DEBUG: 2f4a 👁  Start read: T0  🔗    0↑🔒    0↓    127.0.0.1:8888:0 ≣16 RawFD(17)
DEBUG: eff0 🗣  Write done: T0  🔗    1↑     0↓    127.0.0.1:8888:0 ≣16 RawFD(17)
⬅️   "HTTP/1.1 200 OK\r\n"
    "Via: 1.1 vegur, 1.1 tinyproxy (tinyproxy/1.8.4)\r\n"
    "Access-Control-Allow-Credentials: true\r\n"
    "X-Powered-By: Flask\r\n"
    "Content-Type: application/json\r\n"
    "Date: Thu, 08 Mar 2018 09:12:50 GMT\r\n"
    "X-Processed-Time: 0\r\n"
    "Access-Control-Allow-Origin: *\r\n"
    "Content-Length: 31\r\n"
    "Server: meinheld/0.6.1\r\n"
    "\r\n"
    "{\n"
    "  \"origin\": \"60.224.142.5\"\n"
    "}\n"
♻️   "{\n"
    "  \"origin\": \"60.224.142.5\"\n"
    "}\n"
⬅️   "{\n"
    "  \"origin\": \"60.224.142.5\"\n"
    "}\n"
DEBUG: 2f4a ✉️  Read done:  T0  💀    1↑     1↓    127.0.0.1:8888:0 ≣16 RawFD(-1)
```
_(`src/HTTP.jl:DEBUG_LEVEL = 2`)_

**Comment by samoconnor** [comment]
This example shows proxying a HTTPS url through a HTTP proxy using an [`CONNECT` tunnel](https://tools.ietf.org/html/rfc7231#section-4.3.6).

```julia
julia> HTTP.request("GET", "https://httpbin.org/ip"; proxy="http://127.0.0.1:8888")
DEBUG: f5b5 TCP connect: 127.0.0.1:8888...
DEBUG: f5b5 🔗  New:            🔗    0↑     0↓    127.0.0.1:8888:0 ≣16 RawFD(24)
DEBUG: f5b5 👁  Start write:T0  🔗    0↑     0↓    127.0.0.1:8888:0 ≣16 RawFD(24)
DEBUG: f5b5 📡  CONNECT HTTPS tunnel to httpbin.org:
DEBUG: f5b5 👁  Start read: T0  🔗    0↑🔒    0↓    127.0.0.1:8888:0 ≣16 RawFD(24)
DEBUG: f5b5 👁  Start write:T0  ⏸    0↑     0↓    :8888:0 ≣16 RawFD(24)
DEBUG: f5b5 👁  Start read: T0  ⏸    0↑🔒    0↓    :8888:0 ≣16 RawFD(24)
DEBUG: 219d 🗣  Write done: T0  ⏸    1↑     0↓    :8888:0 ≣16 RawFD(24)
DEBUG: f5b5 ✉️  Read done:  T0  ⏸    1↑     1↓    :8888:0 ≣16 RawFD(24)
HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Connection: keep-alive
Server: meinheld/0.6.1
Date: Thu, 08 Mar 2018 10:55:13 GMT
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Powered-By: Flask
X-Processed-Time: 0
Content-Length: 31
Via: 1.1 vegur

{
  "origin": "60.224.142.5"
}
"""
```

**Comment by frigaardj** [comment]
Is there currently anyway of automatically picking this up from the HTTP_PROXY/HTTPS_PROXY environment variables? This means proxied requests would work out of the box on linux assuming the variables have been set on the OS
