### ISSUE TITLE
HTTP.Router() crashes Julia

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HTTP.jl#226]
Julia 0.6.2 (Windows)
HTTP.jl 0.6.8
MbedTLS.jl 0.5.6

Hi 👋 

I added a line

```julia
router = HTTP.Router()
```

to some code and when I run it, I get the following flash on my screen

```julia
INFO: Recompiling stale cache file C:\Users\Eric\.julia\lib\v0.6\Pages.ji for module Pages.
WARNING: eval from module Handlers to Pages:
Expr(:call, :##661, Expr(:..., :args)::Any)::Any = Expr(:block, Expr(:line, 57, :C:\Users\Eric\.julia\v0.6\HTTP\src\Handlers.jl)::Any, :FourOhFour)::Any
  ** incremental compilation may be broken for this module **
```

then a bunch of stuff spews to the screen, but the REPL crashes before I can read it 😅 

Any ideas?

Update:

I just tried this

```julia
router = HTTP.Router(HTTP.Handlers.FourOhFour)
```

This time it doesn't crash, but I get the following:

```julia
ERROR: LoadError: MethodError: Cannot `convert` an object of type HTTP.Handlers.HandlerFunction{HTTP.Handlers.##1#2} to an object of type Function
This may have arisen from a call to the constructor Function(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] HTTP.Handlers.Router(::HTTP.Handlers.HandlerFunction{HTTP.Handlers.##1#2}) at C:\Users\Eric\.julia\v0.6\HTTP\src\Handlers.jl:61
 [2] include_from_node1(::String) at .\loading.jl:576
 [3] include(::String) at .\sysimg.jl:14
 [4] anonymous at .\<missing>:2
while loading C:\Users\Eric\.julia\v0.6\Pages\src\Pages.jl, in expression starting on line 28
ERROR: Failed to precompile Pages to C:\Users\Eric\.julia\lib\v0.6\Pages.ji.
Stacktrace:
 [1] compilecache(::String) at .\loading.jl:710
 [2] _require(::Symbol) at .\loading.jl:463
 [3] require(::Symbol) at .\loading.jl:405
```

**Comment by EricForgy** [comment]
Still having some problems after my PR. Might as well try to fix everything before merging 😊 

```julia
              _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using HTTP

julia> r = HTTP.Router()
HTTP.Handlers.Router(Dict{String,Val}(), Symbol("##665"), HTTP.Handlers.HandlerFunction{HTTP.Handlers.##3#4}(HTTP.Handlers.#3))

julia> HTTP.handle(r, HTTP.Request())
ERROR: MethodError: objects of type HTTP.Handlers.HandlerFunction{HTTP.Handlers.##3#4} are not callable
Stacktrace:
 [1] gethandler(::HTTP.Handlers.Router, ::HTTP.Messages.Request) at C:\Users\Eric\.julia\v0.6\HTTP\src\Handlers.jl:135
 [2] handle(::HTTP.Handlers.Router, ::HTTP.Messages.Request) at C:\Users\Eric\.julia\v0.6\HTTP\src\Handlers.jl:139
```

**Comment by EricForgy** [comment]
I tried a few different things (with force push so not sure if there are records of my embarassment 😅 ), but this one seems ok to me.

I don't think we need the `@eval`s in there. It is kind of a neat trick that a field `func::Function` of a type can have multiple methods and then dispatch on those 👍😊

**Comment by EricForgy** [comment]
General note 😅 

https://docs.julialang.org/en/stable/manual/performance-tips/#The-dangers-of-abusing-multiple-dispatch-(aka,-more-on-types-with-values-as-parameters)-1

**Comment by EricForgy** [comment]
My best guess for the cause of this problem is that `@eval` means HTTP cannot be precompiled as is and then when I try to precompile Pages, it throws an error and crashes Julia.

**Comment by quinnj** [comment]
I'm not quite sure what's going on here, but there shouldn't be a problem (in principle) to putting `HTTP.Router()` in a precompiled module. I have several other cases where I do that exact thing w/o issue. Is the code on a branch for Pages.jl somewhere? I'd like to check out the branch and look at things on my end.

**Comment by EricForgy** [comment]
Thanks @quinnj 

I was preparing a branch you can have a look at and the problem disappeared 😅 

I have no idea what I was doing wrong before, but it is working fine now 🤔

**Comment by EricForgy** [comment]
I think I am losing my mind 😅 

The issue is back. When I closed this issue, I think I was on the wrong branch of HTTP.jl, but now that I'm on master branch (v0.6.8) of HTTP.jl, Julia is crashing again when I include

```julia
router = HTTP.Router()
``` 

Here is a branch of Pages that crashes on my machine

https://github.com/EricForgy/Pages.jl/tree/router

**Comment by EricForgy** [comment]
I just created a new branch 

https://github.com/EricForgy/Pages.jl/tree/router-only

which is JUST my latest tagged version plus one line:

```julia
router = HTTP.Router()
```

With this one additional line,

```julia
julia> using Pages
```

crashes Julia.

@samoconnor @tk3369

Any ideas?

**Comment by EricForgy** [comment]
Thanks @tk3369

**Comment by EricForgy** [comment]
Hi @samoconnor , @quinnj ,

How are you? Just in case there is some confusion, this issue has nothing to do with Pages.jl.

@tk3369 's [MWE is literally just](https://github.com/tk3369/TestHTTPRouter.jl/blob/master/src/TestHTTPRouter.jl):

```julia
__precompile__()

module TestHTTPRouter

using HTTP

router = HTTP.Router()

end # module
```

This should not crash Julia. Any thoughts?

**Comment by EricForgy** [comment]
I do not understand the reason, but there is a workaround:

```julia
const _ROUTER = Ref{HTTP.Router}()

function __init__()
    _ROUTER[] = HTTP.Router()
    global const router = _ROUTER[]
end
```

@tk3369 Now, we can have some fun with Pages 😊
