### ISSUE TITLE
Weird gzip-related errors

### ISSUE THREAD

**Issue by quinnj** [JuliaWeb/HTTP.jl#23]
@staticfloat @bicycle1885 

I'm seeing some weird gzip-related errors. If I do a request that returns a compressed body and save that out to disk, everything works fine and dandy on OSX, but on linux, I always get 
```
[jacob.quinn]$ gunzip file.gz

gzip: file.gz: invalid compressed data--crc error

gzip: file.gz: invalid compressed data--length error
```
Would you two (and anyone else) be able to try a similar request and see if you run into any issues?

**Comment by staticfloat** [comment]
Sure, what is a good testing URL?

**Comment by bicycle1885** [comment]
Maybe https://httpbin.org/gzip?

**Comment by bicycle1885** [comment]
It works properly on my macOS:
```
julia> res = HTTP.get("https://httpbin.org/gzip")
HTTP.Response:
"""
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 200
Access-Control-Allow-Credentials: true
Date: Fri, 17 Feb 2017 09:51:20 GMT
Content-Type: application/json
Access-Control-Allow-Origin: *
Content-Encoding: gzip
Server: nginx

[compressed HTTP.Response body of 200 bytes]
"""

julia> write("out.gzip", HTTP.body(res))

shell> gzip -cd out.gzip
{
  "gzipped": true,
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8,application/json",
    "Host": "httpbin.org",
    "User-Agent": "HTTP.jl/0.0.0"
  },
  "method": "GET",
  "origin": "134.160.214.62"
}

```

However, I sometimes see null-body responses like below:
```
julia> res = HTTP.get("https://httpbin.org/gzip")
HTTP.Response:
"""
HTTP/1.1 200 OK

"""
julia> write("out.gzip", HTTP.body(res))

shell> gzip -cd out.gzip
gzip: out.gzip: unexpected end of file

```

**Comment by staticfloat** [comment]
Using @bicycle1885's test routine, I ran it ~10 times and never saw any problems on Linux.

**Comment by quinnj** [comment]
Thanks for checking guys. I'm a little worried it has something to do w/ when the user does `stream=true`. It's kind of a weird case where I'm trying to run a script on a server that might be a little flaky. I haven't been able to reproduce locally on OSX, so I don't know.

I did however reproduce the "immediately return an empty 200 response" issue and I have a fix incoming for that. Man, networking can be a real pain to test and cover.

**Comment by quinnj** [comment]
Would you guys minding trying again w/ a new function I've put in the package? An example call would be
```
 d = HTTP.download("https://dl.dropboxusercontent.com/u/19048830/file.gz", "file.gz")
run(`gunzip file.gz`)
```

This will download a garbage file from my public dropbox, the uncompressed file size is around ~300MB.

**Comment by staticfloat** [comment]
Worked just fine for me on Linux.

**Comment by quinnj** [comment]
This is a weird one folks, I can only repro on linux with really huge (multi Gb) downloads. I finally got a corrupted file onto my mac w/ a clean download so I can compare them. Let's find the needle in the 1.5GB haystack!

**Comment by quinnj** [comment]
I might need a vacation after that one (which is ironic, because I did all the debug + fix over president's day weekend on vacation)
