### ISSUE TITLE
ConnectionPool should check require_ssl_verification

### ISSUE THREAD

**Issue by cnoelle** [JuliaWeb/HTTP.jl#244]
Julia 0.6.2 
HTTP.jl master (0.6.9+)
MbedTLS.jl 0.5.8

I have a web server on localhost with a selfsigned TLS certificate. Sending a GET request with certifacte verification enabled leads to an error, as expected:

````
HTTP.request("GET", "https://localhost:8080", require_ssl_verification = true) 
ERROR: MbedTLS error code -9984: X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
````

After sending a request with `require_ssl_verification = false`, this is no longer true:

```
HTTP.request("GET", "https://localhost:8080", require_ssl_verification = true)
HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Date: Wed, 30 May 2018 10:09:11 GMT
Set-Cookie: JSESSIONID=o6yzugifjchl1xt88fzpg428s;Path=/;Secure;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Transfer-Encoding: chunked
...
````

**Comment by samoconnor** [comment]
The [`ConnectionPool`](https://github.com/JuliaWeb/HTTP.jl/blob/master/src/ConnectionPool.jl#L314) caches and re-uses connections. Certificate verification occurs at the time a connection is established, so the `require_ssl_verification` flag has no effect when an already open connection is reused.
The rule for connection reuse is currently that `(host, port, pipeline_limit)` must match:
https://github.com/JuliaWeb/HTTP.jl/blob/597c0c7b35f1f76e5d5c709dd1c082e8c5391405/src/ConnectionPool.jl#L348-L350

We probably should extend this to match on `require_ssl_verification` as well so a connection would only be reused if the new request has the same `require_ssl_verification` value as the cached connection. (i.e. add `require_ssl_verification` as field of `struct Connection`)

As it stands, a connection could be opened to `https://foo.com` with `require_ssl_verification=false`, then a later request to the same host with `require_ssl_verification=true` would silently succeed even though no verification was done. This scenario seems unlikely, but it is probably best to make the change anyway. @quinnj ? @vtjnash ?

**Comment by quinnj** [comment]
Yeah, probably best to include that as a condition for re-use.
