### ISSUE TITLE
WebSocket test failure on 0.7

### ISSUE THREAD

**Issue by quinnj** [JuliaWeb/HTTP.jl#246]
As documented here: https://github.com/JuliaWeb/HTTP.jl/pull/238

**Comment by quinnj** [comment]
I believe this may have been due to a change in the server we're pinging for websocket tests, since I checked out 5d5614c9b65a4bfa66c730b373b8a160b535f012, which had known passing tests (according to travis logs), but which currently has the same test failures we're seeing on PRs/master.

**Comment by quinnj** [comment]
Note that the failing test has been commented out for now to ensure passing package tests; given this functionality is newer and not extremely robust, I think we're ok allowing failures on master for the moment, but it would be great if @EricForgy or @samoconnor could look into why this test is now failing on 0.7 and how to fix.

**Comment by samoconnor** [comment]
Tried this just now on 1.0, seems to pass:
```julia
$ julia10 ./test/WebSockets.jl
writing
testing
writing again
closewrite
reading response
writing
testing
writing again
closewrite
reading response
[ Info: Listening on: Sockets.InetAddr{IPv4}(ip"127.0.0.1", 0x1f95)
Testing local server...
[ Info: Accept:  🔗    0↑     0↓    0s 127.0.0.1:8085:8085 ≣16
[ Info: Closed:  💀    1↑     1↓🔒   0s 127.0.0.1:8085:8085 ≣16
Test Summary: | Pass  Total
WebSockets    |    8      8
```

**Comment by samoconnor** [comment]
6f454ba3a7e1b654f02baa65b5f16256978ed04f

**Comment by samoconnor** [comment]
Travis passing: https://travis-ci.org/JuliaWeb/HTTP.jl/jobs/422319666
