### ISSUE TITLE
missing body content?

### ISSUE THREAD

**Issue by vtjnash** [JuliaWeb/HTTP.jl#25]
It seems like all content gets lost if there's more than a few dozen seconds since the last request. (on Julia master and current HTTP.jl release 15f33bc518902b29fdb132f4bcc696fe3aa37ecc)

```julia
julia> r = HTTP.get(uriroot, headers = headers)
HTTP.Response:
"""
HTTP/1.1 200 OK
Connection: keep-alive
Via: 1.1 vegur
...
"""

<wait for a minute>

julia> r = HTTP.get(uriroot, headers = headers)
HTTP.Response:
"""
HTTP/1.1 200 OK

"""

julia> r = HTTP.get(uriroot, headers = headers)
HTTP.Response:
"""
HTTP/1.1 200 OK
Connection: keep-alive
Via: 1.1 vegur
...
```
```

**Comment by quinnj** [comment]
Yeah, this should be fixed on master. This issue is when the remote connection gets closed, but it's not detected on write, but only when we try to read the response. I need to get a new release out w/ the fix.

**Comment by vtjnash** [comment]
OK, cool. Just thought I would check. I just checked out master locally.
