### ISSUE TITLE
Remove client.jl

### ISSUE THREAD

**Issue by quinnj** [JuliaWeb/HTTP.jl#250]
We've had the deprecations in for several releases now, so I think it's time to remove the client.jl file. We need to refactor the `download` function, but we could also just deprecate it as well. @samoconnor, do you want to tackle this? Or I could take a stab at it sometime soon.

Or if anyone else is interested, I think it'd be a pretty easy PR.

**Comment by samoconnor** [comment]
I believe the download function isn't tested or documented.
I'm in favour of just removing it.
Maybe put an example like this at the top of the README:
```julia
HTTP.open("GET", url) do io
    write("/tmp/foo", io)
end
```

**Comment by samoconnor** [comment]
I'm assuming that at some point soon after 0.7 is released, we'll make a HTTP version that drops 0.6.3 from the REQURE file. Maybe that's a good time to remove the client.jl (and do a general pass through the code other deprecated stuff that we might want to remove).
My thinking is that this will avoid inconvenience for people who may have old working 0.6 code and no immediate plans to move to 0.7. Whereas people who are taking the plunge to upgrade their code to 0.7 will be expecting to deal with a deprecations/changes.

**Comment by samoconnor** [comment]
Re dropping 0.6.3 from REQUIRE: We can always back-port anything critical to a 0.6 branch if there is sufficient demand; and dropping 0.6.3 would allow cleanup of various `if VERSION...` cruft.

**Comment by quinnj** [comment]
Yeah, that's a good idea to do this w/ the dropping of 0.6.

**Comment by Nosferican** [comment]
Is this still relevant or should it be closed?
