### ISSUE TITLE
Use Compat.jl

### ISSUE THREAD

**Issue by rofinn** [JuliaWeb/HTTP.jl#251]
Seems like HTTP.jl should just use Compat.jl rather than doing compat things itself. Also, this results in HTTP.jl overwriting methods defined in Compat.jl

Julia 0.6.2 
HTTP.jl 0.6.11
Compat 0.68.0
```
WARNING: Method definition fetch(Task) in module Compat at /home/rory/.julia/v0.6/Compat/src/Compat.jl:1903 overwritten in module HTTP at /home/rory/.julia/v0.6/HTTP/src/compat.jl:66.
```

**Comment by ararslan** [comment]
Indeed, it's kind of silly to reimplement basically all of Compat in here rather than just using Compat.

**Comment by quinnj** [comment]
Fixed by 61e6b05d4dbfc296a4f05e587b7cd23ff3747f21

**Comment by quinnj** [comment]
Yeah, in hindsight we should have just went the Compat.jl route, but at the time, Compat was woefully slow at actually keep up w/ 0.7 changes and we actually didn't need very much compat; fast forward and well, this is where we are, not far from dropping 0.6 anyway.

**Comment by samoconnor** [comment]
We haven't implemented "basically all of Compat.jl", our compat file is ~80 lines vs 2000+ lines for Compat.jl.
