### ISSUE TITLE
Requests start failing in getaddrinfo after a couple of days

### ISSUE THREAD

**Issue by Keno** [JuliaWeb/HTTP.jl#253]
This gist is from a long-ish (3 days) running femtocleaner sessions: https://gist.github.com/Keno/ae363b7f495f99b4b9731eebb8f4db19

At some point all requests start failing in getaddrinfo, though there's no actual error being indicated.

**Comment by Keno** [comment]
I note that this is on 0.6, which has a bit wonky getaddrinfo handling. I'm planning to upgrade to 0.7 soon and we'll see if this persists.

**Comment by samoconnor** [comment]
From the stacktrace, the femtocleaner server calls 
[`create_access_token`](https://github.com/JuliaWeb/GitHub.jl/blob/master/src/apps/installations.jl#L10), which makes a HTTP request, which calls getaddrinfo,  which throws `SystemError` here: https://github.com/JuliaLang/julia/blob/v0.6.3/base/socket.jl#L657

**Comment by Keno** [comment]
Looking at this again, I may know what the issue is. This host is running a dual-stack IPv4/IPv6 network , but the IPv6 code is commented out on 0.6

**Comment by samoconnor** [comment]
It seems odd that the code reported in the `SystemError` is `0`. I guess the code comes from the libuv `status` [here ?](https://github.com/JuliaLang/julia/blob/v0.6.3/base/socket.jl#L596)
That seems to imply that `getaddrinfo` returned `0` status but didn't set the result pointer (it stayed NULL).

**Comment by samoconnor** [comment]
The [manual page for getaddrinfo](http://man7.org/linux/man-pages/man3/getaddrinfo.3.html) has an example where the call succeeds (return status `0`) but the result pointer is `NULL` with the comment "No address succeeded":

```C
           s = getaddrinfo(argv[1], argv[2], &hints, &result);
           if (s != 0) {
               fprintf(stderr, "getaddrinfo: %s\n", gai_strerror(s));
               exit(EXIT_FAILURE);
           }

           /* getaddrinfo() returns a list of address structures.
              Try each address until we successfully connect(2).
              If socket(2) (or connect(2)) fails, we (close the socket
              and) try the next address. */

           for (rp = result; rp != NULL; rp = rp->ai_next) {
               sfd = socket(rp->ai_family, rp->ai_socktype,
                            rp->ai_protocol);
               if (sfd == -1)
                   continue;

               if (connect(sfd, rp->ai_addr, rp->ai_addrlen) != -1)
                   break;                  /* Success */

               close(sfd);
           }

           if (rp == NULL) {               /* No address succeeded */
               fprintf(stderr, "Could not connect\n");
               exit(EXIT_FAILURE);
           }

           freeaddrinfo(result);           /* No longer needed */

```
This seems to be inconsistent with the statement elsewhere in the man page that "getaddrinfo() returns one or more addrinfo structures".

**Comment by quinnj** [comment]
@Keno, is this still an issue? Is it just 0.6 where the IPv6 code is commented out?

**Comment by Keno** [comment]
I haven't seen this again in the past couple of weeks.

**Comment by quinnj** [comment]
I'll close for now; please let us know if anything comes up again.
