### ISSUE TITLE
Split out `listen` functionality

### ISSUE THREAD

**Issue by simonbyrne** [JuliaWeb/HTTP.jl#258]
From the docs, it's not exactly clear what the function passed to `listen` should actually do. I ended up looking into the source and eventually found that there are 2 different paths, the course of which is determined [by calling `applicable`](https://github.com/JuliaWeb/HTTP.jl/blob/61e6b05d4dbfc296a4f05e587b7cd23ff3747f21/src/Servers.jl#L498-L502).

This seems like a bit of a code smell, as it seems to go against the "duck typing" idiom that Julia generally uses. My suggestion would be to split `listen` into 2 functions (say `listen` and `listen_stream`).

**Comment by samoconnor** [comment]
Hi @simonbyrne 
There are two examples of `listen` in the [`README.md`](https://github.com/JuliaWeb/HTTP.jl/blob/master/README.md). These examples and/or more explanation should probably be included in the documentation.

**Comment by quinnj** [comment]
We definitely need to consolidate `HTTP.listen` and `HTTP.serve`; it's too confusing to have essentially two main entry points to starting a server. It's been on my list for a few weeks, but just haven't found the time to do it.

**Comment by samoconnor** [comment]
Can `serve` simply be deprecated? It is currently a very thin wrapper for `listen`.

**Comment by EricForgy** [comment]
@essenciary

I think `server` was recently added to Genie.jl, but shouldn't be hard to transition to `listen` instead.
