### ISSUE TITLE
Feature: add custom "recoverable" predicate to RetryLayer

### ISSUE THREAD

**Issue by iamed2** [JuliaWeb/HTTP.jl#259]
This would allow handling cases like https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/http.jl with the RetryLayer directly rather than having retries on top. 

I'm happy to work on this if desired.

**Comment by samoconnor** [comment]
Hi @iamed2, this (and #260) seems useful.
My only cause for hesitation is wondering if it would be better to have an example in the documentation that shows how to plug in `MyCustomRetryLayer`. It was always my intention to make it easy for users or API libraries to insert/replace layers, but I haven't worked through an example of this yet.
On one hand configuring an existing layer via knobs and levers is handy. On the other hand, it might be cleaner to drop in a special purpose layer when needed and minimise the (potentially confusing) array of knobs and levers.

**Comment by quinnj** [comment]
@iamed2 @mattBrzezinski , would something like this still be useful? (going back over old issues)

**Comment by mattBrzezinski** [comment]
> @iamed2 @mattBrzezinski , would something like this still be useful? (going back over old issues)

It's been a a minute since I've looked at this package. Yes this functionality would be useful, but I believe we could do this individually by writing our own RetryLayer and making our own custom HTTP stack to use.

**Comment by quinnj** [comment]
Ok, well I'll close here for now then, unless it would be much more convenient to just add it to HTTP.jl's RetryLayer
