### ISSUE TITLE
FIFOBuffer code is all dead

### ISSUE THREAD

**Issue by oxinabox** [JuliaWeb/HTTP.jl#272]
There is a bunch of code for FIFOBuffers
https://github.com/JuliaWeb/HTTP.jl/search?q=fifobuffer&unscoped_q=fifobuffer

It is all either commented out,
or in files that are not `included`

It can be deleted yes?

**Comment by samoconnor** [comment]
Related https://github.com/JuliaWeb/HTTP.jl/issues/122#issuecomment-366511091, https://github.com/JuliaWeb/HTTP.jl/issues/120#issuecomment-361466101
