### ISSUE TITLE
Cookies aren't overwriting like they should

### ISSUE THREAD

**Issue by staticfloat** [JuliaWeb/HTTP.jl#28]
I'm sorry I don't have an MWE for you, I've been unable to reproduce this with a small amount of code.

I have a buildbot instance that I'm authenticating to and that authentication modifies a cookie.  This cookie is called `TWISTED_SESSION` and is a giant encoded mess, but the important part is that the cookie must be overwritten properly in order for the authentication to stick.  I've noticed that my authentication seems to randomly come and go; sometimes I can make dozens of requests with no problem, and sometimes it takes me 5 or 6 authentication requests for the cookie to be included in further requests that I make against the buildbot.  My bandaid solution until I could get a good MWE so far has been to just try authenticating again and again until it works, (which has the happy accident of making a lot of my code very resilient! yay!) but I think I just found something of interest.

Looking into my `client` object, I see that there are many `TWISTED_SESSION` cookies from my buildbot:

```
8-element Array{HTTP.Cookies.Cookie,1}:
 HTTP.Cookies.Cookie("TWISTED_SESSION","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2luZm8iOnsidXNlcm5hbWUiOiJqbGJ1aWxkIiwiZW1haWwiOiJqbGJ1aWxkIiwiZ3JvdXBzIjpbIkp1bGlhTGFuZyJdLCJmdWxsX25hbWUiOiJKdWxpYSBCdWlsZGJvdCJ9LCJleHAiOjE0ODg0Mjc1NTZ9.Y536-llbe8ox3dgvwXeD5US5cbRdbSTbqLoUhzq4N_s","/","buildtest.e.ip.saba.us",0001-01-01T00:00:00,0,false,false,true,String[])
 HTTP.Cookies.Cookie("TWISTED_SESSION","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2luZm8iOnsidXNlcm5hbWUiOiJqbGJ1aWxkIiwiZW1haWwiOiJqbGJ1aWxkIiwiZ3JvdXBzIjpbIkp1bGlhTGFuZyJdLCJmdWxsX25hbWUiOiJKdWxpYSBCdWlsZGJvdCJ9LCJleHAiOjE0ODg0Mjc1NzN9.OfTFv2QJHxtQkVQEKRZg3P2bkhAiGmsRoVQI775U3pE","/","buildtest.e.ip.saba.us",0001-01-01T00:00:00,0,false,false,true,String[])
 HTTP.Cookies.Cookie("TWISTED_SESSION","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2luZm8iOnsidXNlcm5hbWUiOiJqbGJ1aWxkIiwiZW1haWwiOiJqbGJ1aWxkIiwiZ3JvdXBzIjpbIkp1bGlhTGFuZyJdLCJmdWxsX25hbWUiOiJKdWxpYSBCdWlsZGJvdCJ9LCJleHAiOjE0ODg0Mjc1NTd9.ClKMBSCO7V_GlTHtOUH8fz9EI0p5MmnNBrDDeq4Qj9Q","/","buildtest.e.ip.saba.us",0001-01-01T00:00:00,0,false,false,true,String[])
 HTTP.Cookies.Cookie("TWISTED_SESSION","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2luZm8iOnsidXNlcm5hbWUiOiJqbGJ1aWxkIiwiZW1haWwiOiJqbGJ1aWxkIiwiZ3JvdXBzIjpbIkp1bGlhTGFuZyJdLCJmdWxsX25hbWUiOiJKdWxpYSBCdWlsZGJvdCJ9LCJleHAiOjE0ODg0Mjc1NTh9.Qc6t2ykLerNIeORlJYqfI67NrgfHv0q8-k70TaVRXvE","/","buildtest.e.ip.saba.us",0001-01-01T00:00:00,0,false,false,true,String[])
 HTTP.Cookies.Cookie("TWISTED_SESSION","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2luZm8iOnsidXNlcm5hbWUiOiJqbGJ1aWxkIiwiZW1haWwiOiJqbGJ1aWxkIiwiZ3JvdXBzIjpbIkp1bGlhTGFuZyJdLCJmdWxsX25hbWUiOiJKdWxpYSBCdWlsZGJvdCJ9LCJleHAiOjE0ODg0Mjc1NzR9.wK71WMj1HwVvnjzR5ho9uiua6b60oQLB0khNwIjhRYc","/","buildtest.e.ip.saba.us",0001-01-01T00:00:00,0,false,false,true,String[])
 HTTP.Cookies.Cookie("TWISTED_SESSION","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2luZm8iOnsidXNlcm5hbWUiOiJqbGJ1aWxkIiwiZW1haWwiOiJqbGJ1aWxkIiwiZ3JvdXBzIjpbIkp1bGlhTGFuZyJdLCJmdWxsX25hbWUiOiJKdWxpYSBCdWlsZGJvdCJ9LCJleHAiOjE0ODg0Mjc1NTl9.jXJ3c-JjwBoZxV4YHdCx8l9YnAqcPTtUvGnUDnEC5e4","/","buildtest.e.ip.saba.us",0001-01-01T00:00:00,0,false,false,true,String[])
 HTTP.Cookies.Cookie("TWISTED_SESSION","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2luZm8iOnsidXNlcm5hbWUiOiJqbGJ1aWxkIiwiZW1haWwiOiJqbGJ1aWxkIiwiZ3JvdXBzIjpbIkp1bGlhTGFuZyJdLCJmdWxsX25hbWUiOiJKdWxpYSBCdWlsZGJvdCJ9LCJleHAiOjE0ODg0Mjc1NzJ9.DdN7E1_Gg33lzdgYh7jb-zm4S59JouSBg9hTiix-RWk","/","buildtest.e.ip.saba.us",0001-01-01T00:00:00,0,false,false,true,String[])
 HTTP.Cookies.Cookie("TWISTED_SESSION","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2luZm8iOnsiYW5vbnltb3VzIjp0cnVlfSwiZXhwIjoxNDg4NDI3NTUxfQ.hfPJGiuK1iJ2eH7Ueyc2uVvIVRw5p26q1v8FiGzjhtA","/","buildtest.e.ip.saba.us",0001-01-01T00:00:00,0,false,false,true,String[])    
```

If all of these cookies are being sent to the server, I would not be surprised at all if the intermittent nature of my failures are due to Julia's `Set` key traversal pseudo-randomizing the order in which the cookies are sent to the server, thereby causing the "correct" cookie to sometimes be last/first/whatever position would cause the buildbot to use that cookie instead of any of the others.

Chrome/Postman/etc... do not get multiple cookies, they get only one for the same cookie name/subpath/host tuple, so I'm certain enough that this is a bug in HTTP.jl that I'll open this issue, but not certain enough that I'm willing to stake my reputation as an internet cookie connoisseur on it.

**Comment by quinnj** [comment]
Interesting. One way to see for certain what is getting sent is to do `HTTP.post(uri; verbose=true)`. That will show the full request getting sent over the wire (including the Cookie header).

So if I understand correctly, when you inspect the client cookies, you'd expect to see a single `TWISTED_SESSION` cookie and subsequent response with Set-Cookie w/ that same name should replace any existing cookie?

**Comment by staticfloat** [comment]
>  you'd expect to see a single TWISTED_SESSION cookie and subsequent response with Set-Cookie w/ that same name should replace any existing cookie?

Specifically, a cookie with the same name, (`TWISTED_SESSION`), Path (`/`) and Domain (`buildtest.e.ip.saba.us`) should be overwritten.  The `Path` stuff is perhaps annoying to implement and doesn't effect me, [Wikipedia has a small writeup about it](https://en.wikipedia.org/wiki/HTTP_cookie#Setting_a_cookie) that's easier to read than the actual IETF RFC's.  Basically, `Path` stuff restricts cookies to be sent only for certain subpaths of the server.

**Comment by staticfloat** [comment]
Wow, `verbose=true` is awesome.

Interesting.  I think the webserver might be (slightly) misbehaving here.  Here's a small conversation:
```
HTTP.Request:
"""
GET /auth/login?token=165e61d9522ce5a7b005c2ea3a082328da636cb1 HTTP/1.1
Host: buildtest.e.ip.saba.us
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8,application/json
User-Agent: HTTP.jl/0.0.0

"""
[HTTP - 2017-02-22T20:37:27.42]: waiting for response; will timeout afer 10.0 seconds
[HTTP - 2017-02-22T20:37:27.425]: received bytes from the wire, processing
[HTTP - 2017-02-22T20:37:29.055]: caching received cookies for host
[HTTP - 2017-02-22T20:37:29.055]: received response
HTTP.Response:
"""
HTTP/1.1 302 Moved Temporarily
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: TWISTED_SESSION=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2luZm8iOnsiYW5vbnltb3VzIjp0cnVlfSwiZXhwIjoxNDg4NDI5NDQxfQ.n1EBOT0lPd_JkRHSE8R3K5gLInYzblxMULemD
X1k10g; Path=/, TWISTED_SESSION=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2luZm8iOnsidXNlcm5hbWUiOiJqbGJ1aWxkIiwiZW1haWwiOiJqbGJ1aWxkIiwiZ3JvdXBzIjpbIkp1bGlhTGFuZyJd
LCJmdWxsX25hbWUiOiJKdWxpYSBCdWlsZGJvdCJ9LCJleHAiOjE0ODg0Mjk0NDF9.CwRCKPkqdemIOd5ADtIoQTkwlQm0A4P5ZSbM3vr7Z4Q; Path=/
Date: Thu, 23 Feb 2017 04:37:21 GMT
Content-Type: text/html
Location: https://buildtest.e.ip.saba.us/
Server: nginx/1.11.9

```

Notice how it sends back TWO cookies.  I think the problem is that we need to be choosing one and only one to store, but instead we store all of them.

**Comment by quinnj** [comment]
@staticfloat, any chance you could try out https://github.com/JuliaWeb/HTTP.jl/pull/29 to see if that fixes it? The change is to hash Cookies only on their path, name, and domain, which should ensure our `client.cookies` only ever keeps one cookie per name-path-domain combination.

**Comment by staticfloat** [comment]
Yes, it seems to be keeping only one cookie.  :)

I'll have to see if this actually fixes the problem.  As I said, it was intermittent.  But I can confirm it's storing cookies as I would have expected. :)

**Comment by quinnj** [comment]
Cool, I'll merge for now and keep this open. Do report back if something doesn't seem quite right.

**Comment by staticfloat** [comment]
This is definitely fixed now.  It's been working great.

**Comment by quinnj** [comment]
![Alt Text](http://i.giphy.com/3o7abB06u9bNzA8lu8.gif)
