### ISSUE TITLE
Support byte I/O

### ISSUE THREAD

**Issue by cstjean** [JuliaWeb/HTTP.jl#280]
On Julia 0.6.3, HTTP.jl 0.6.12, I'd like to use `JSON.print` directly, but I'm getting a method error

```julia
julia> HTTP.open("POST", url) do io
           JSON.print(io,22)
       end
ERROR: HTTP.Streams.Stream{HTTP.Messages.Response,HTTP.ConnectionPool.Transaction{TCPSocket}} does not support byte I/O
```

I can fix it by defining `Base.write(stream::HTTP.Streams.Stream, x::UInt8) = write(stream, string(Char(x)))`, although that looks super-inefficient. Could it be supported natively by this package?

**Comment by samoconnor** [comment]
It doesn't feel right to me for HTTP.jl to support byte I/O.
That would result in something like writing every byte as a seperate chunk with many bytes of overhead.
 
The [`BufferedStreams.jl`](https://github.com/BioJulia/BufferedStreams.jl) package may be what you need if your JSON data is very large, or for small data you could simply `JSON.print` to an `IOBuffer`

**Comment by cstjean** [comment]
> That would result in something like writing every byte as a seperate chunk with many bytes of overhead.

Ah, I didn't realize that this would happen. Nevermind, I'll try to find another way of solving my JSON.json memory leak. Thank you for the suggestions.
