### ISSUE TITLE
WebSocket errors on page reload

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HTTP.jl#293]
Julia 1.0
HTTP.jl 0.6.14
MbedTLS.jl 0.X.X -- Please specify versions

I have a page that connects to a websocket and if the page is re/unloaded, it will try to close the websocket and let Julia know the page is re/unloaded:

```js
    window.onbeforeunload = function () {
        callback("unloaded");
        if (sock) {
            sock.onclose = function () {};
            sock.close()    
        }
    };
```

The `callback` to Julia seems to be working fine, but I get an error in the REPL:

```julia
┌ Error: (ErrorException("Unexpected end of input\nLine: 0\nAround: ......\n           ^\n"), Base.StackTraces.StackFrame[])
└ @ HTTP.Servers C:\Users\Eric\.julia\packages\HTTP\nUK4f\src\Servers.jl:481
```

Any ideas?

PS: It is not super important, because, aside from the error in the REPL, the page reloads fine.

**Comment by samoconnor** [comment]
Could this be related? https://github.com/JuliaWeb/HTTP.jl/pull/305 (see also this https://github.com/JuliaWeb/WebSockets.jl/issues/114)

**Comment by quinnj** [comment]
Old stale issue
