### ISSUE TITLE
No error handling for broken pipe in getconnection

### ISSUE THREAD

**Issue by iamed2** [JuliaWeb/HTTP.jl#295]
Julia 0.6.4 
HTTP.jl 0.6.14 
MbedTLS.jl 0.5.12 -- Please specify versions

https://github.com/JuliaWeb/HTTP.jl/blob/cd9f60bcce2cd34c20bd87f10f5e30ff3db22744/src/ConnectionRequest.jl#L38
Sometimes this call to `getconnection` throws a `UVError`/`IOError` "connect: broken pipe (EPIPE)" (e.g., https://github.com/invenia/CloudWatchLogs.jl/issues/4). 

As far as I know this will be the same in the latest Julia+HTTP version combo.

Wrapping this in `HTTP.IOExtras.IOError` would allow the [retry code in AWSCore.jl](https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/http.jl#L54) to retry in this case. Is that something we can add+backport?

**Comment by quinnj** [comment]
Sounds fine to me; submit a PR?

**Comment by samoconnor** [comment]
I've backported this to release-0.6 as well.

**Comment by iamed2** [comment]
Thanks!! That's excellent!

**Comment by samoconnor** [comment]
Also see #306, which would imply simultaneously changing AWSCore to be compatible.
