### ISSUE TITLE
Starting basic server creates error in parser.jl

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [JuliaWeb/HTTP.jl#3]
The following code:

```julia
using HTTP

import HTTP: http, serve

server = HTTP.Server{http}(
	ip"127.0.0.1",
	8080,
	(request, response) -> println("$request,\t$response"),
	STDOUT
	)

serve(server)
```

results in the following error:

> Starting server to listen on: 127.0.0.1:8080
> ERROR: LoadError: MethodError: no method matching HTTP.Parser{R}(::Type{HTTP.Request}, ::Type{HTTP.http})
> Closest candidates are:
>   HTTP.Parser{R}{T}(::Type{T}) at /home/joel/.julia/v0.5/HTTP/src/parser.jl:33
>   HTTP.Parser{R}{T}(::Any) at sysimg.jl:53
>  in HTTP.ServerClient{T<:HTTP.Scheme,I<:IO}(::HTTP.Server{HTTP.http}) at /home/joel/.julia/v0.5/HTTP/src/server.jl:111
>  in serve(::HTTP.Server{HTTP.http}) at /home/joel/.julia/v0.5/HTTP/src/server.jl:188
>  in include_from_node1(::String) at ./loading.jl:488
>  in process_options(::Base.JLOptions) at ./client.jl:262
>  in _start() at ./client.jl:318
> while loading /home/joel/Development/Julia/Vocabulary/vocabulary_website.jl, in expression starting on line 9

I'm quite fresh to Julia and not sure whether I'm doing something wrong or this is a bug.

**Comment by quinnj** [comment]
It's a bug, I've been working on another iteration of the server code over the last week or so; let me see if I can clean it up and push somehting that works.

**Comment by TheOnlySilverClaw** [comment]
Err... you would tell us when the whole thing is usable again?

**Comment by quinnj** [comment]
Currently the client-side of things is very close to release-ready. I would definitely encourage people to use it and take it for a spin. For server-side, I think my plan is to do some quick updates to get something useable and then do an initial release. Unfortunately, my dreams of a multi-core efficient server are going to require quite a bit more work, but I don't want to hold up everything else good in the package until that's ready.

**Comment by quinnj** [comment]
Alrighty, server.jl code has been updated and with docs! Try `?HTTP.Server` and `?HTTP.serve` from the REPL for the info and do report back w/ any issues!
