### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HTTP.jl#307]
FYI, this is an issue on HttpServer.jl, but contains some benchmarks for HTTP.jl as well:

https://github.com/JuliaWeb/HttpServer.jl/issues/142

**Comment by samoconnor** [comment]
Hi @EricForgy , @leoncamel,

I've just pushed some new code I've been playing with that I hope will pave the way for reduced memory allocation and increase performance.

On the `so/lazyprep` branch I've committed a lazy HTTP Header parser (following the pattern of LazyJSON.jl): https://github.com/JuliaWeb/HTTP.jl/blob/so/lazyprep/src/LazyHTTP.jl.
This branch does not change any (I hope) of the existing functionality of HTTP.jl, it just adds some new modules.

On the `so/lazyintegrate` branch this is integrated with the HTTP.Messages module: https://github.com/JuliaWeb/HTTP.jl/blob/so/lazyintegrate/src/Messages.jl#L474

So far, I've tried to write code that is algorithmically fast and lazy, but I haven't yet done any real world testing or looked for degenerate cases. So far, results from a little benchmark look good: https://github.com/JuliaWeb/HTTP.jl/blob/so/lazyprep/test/LazyHTTP.jl#L320-L430

Only 2% of the old number of allocations for parsing (and ~14% for sending).
About 10x faster parsing sending on my macbook.
About 3.5x faster parsing the Travis box and 20x faster for sending. (odd)

Results from my 2014 macbook:
```
----------------------------------------------
LazyHTTP performance (vs HTTP.Parsers)
----------------------------------------------
github header:     2% allocs,  8% time
wikipedia header:  2% allocs,  9% time
netflix header:    2% allocs,  8% time
twitter header:    2% allocs,  9% time
nytimes header:    2% allocs,  8% time
----------------------------------------------
----------------------------------------------
LazyHTTP send performance (vs HTTP.Response)
----------------------------------------------
github header:     14% allocs,  12% time
wikipedia header:  12% allocs,  10% time
netflix header:    12% allocs,  10% time
twitter header:    13% allocs,  11% time
nytimes header:    12% allocs,  10% time
----------------------------------------------
```

Results from whatever machine Travis runs on:
```
----------------------------------------------
LazyHTTP performance (vs HTTP.Parsers)
----------------------------------------------
github header:     2% allocs, 32% time
wikipedia header:  2% allocs, 23% time
netflix header:    2% allocs, 30% time
twitter header:    2% allocs, 30% time
nytimes header:    2% allocs, 24% time
----------------------------------------------
----------------------------------------------
LazyHTTP send performance (vs HTTP.Response)
----------------------------------------------
github header:     14% allocs,   5% time
wikipedia header:  12% allocs,   5% time
netflix header:    12% allocs,   5% time
twitter header:    13% allocs,   5% time
nytimes header:    12% allocs,   4% time
----------------------------------------------
```

Of course, there may be other code in the server work loop that is causing GC load, (these changes only address message parsing and formatting). Also, whatever user code runs inside the `listen` block has to be GC friendly for overall high performance too.

CI Results:
`so/lazyprep`: https://travis-ci.org/JuliaWeb/HTTP.jl/jobs/435568895
`so/lazyintegrate`: https://travis-ci.org/JuliaWeb/HTTP.jl/jobs/435569180

**Comment by pevnak** [comment]
Following on this, we have tried to benchmark HTTP + AWSS3 in downloading 1000 files from S3.
We have compared four versions of HTTP on julia 0.6 and 0.7. The results are below.
```
HTTP 0.7.1           on Julii 0.7.0 ... 545s
HTTP 0.6.9          on Julii 0.6.2 ... 450s
HTTP 0.5.7          on Julii 0.6.2 ... 65s
HTTP 0.7.0#lazy on Julii 0.7.0 ... 393s
```

It seems like that the #lazy branch helps, but the performance is far from what it has been with HTTP 0.5. Does anyone guess, from where the regression comes from?

**Comment by samoconnor** [comment]
Thanks for posting your benchmark results @pevnak.
Can you please post your test code?

**Comment by janfrancu** [comment]
I work with @pevnak on this. Here is the distilled sample code.
```
using AWSCore
using AWSS3

awstoken = AWSCore.aws_config(region = "eu-west-1", creds = AWSCore.AWSCredentials())

bucket = # bucket 
files = # 1000 files of your choice

function testS3_get(awstoken, bucket, files)
	for file in files
	    bytes = AWSS3.s3_get(awstoken, bucket, file)
	end
end

@time testS3_get(awstoken, bucket, files)
```
All of the results were obtained with the same set of 1000 files. Their sizes vary a lot from 100B up to 3.6MB and median around 70kB.
What I mean by this is that in the newer versions, it seems to return the results in bursts.
Also one observation that I made is that, the newer version seems to resolve the request in bursts rather than one at a time.

**Comment by samoconnor** [comment]
Good to hear that the MbedTLS fix helped @janfrancu !
Note that you can use `@async` directly if `asyncmap` does not fit neatly into your system. As long as  your code ends up calling `HTTP.request` from multiple tasks then HTTP.jl will try to make efficient use of the network.

It would be good to know how long it takes you to run the same test with the same 1000 files using [boto3's `get_object`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.get_object).

**Comment by janfrancu** [comment]
> It would be good to know how long it takes you to run the same test with the same 1000 files using boto3's get_object.

I tested that now too, though I had to battle my rusty python skill. :-)
Same machine, the same 1000 files, default python 3.7.0 docker image from [repo](https://hub.docker.com/_/python/ ) and the results:
```
boto3-1.9.27, botocore-1.12.27          61s, 54s, 59s, 49s, 40s
```
Also I realized there was a lot of boilerplate code in my actual Julia benchmark, therefore I will put here the newest result I got with the MbedTLS#master.
```
HTTP 0.7.1 + MbedTLS#master          55s, 45s, 47s, 44s, 34s
```
