### ISSUE TITLE
Server not releasing port when batch is terminated

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HTTP.jl#314]
Julia 1.0.0 
HTTP.jl 0.7.0
MbedTLS.jl 0.6.1 -- Please specify versions

Hi,

I am trying to work HTTP into a workflow that involves React + TypeScript via WebPack. It feels like a nice match so far and I am able to get things working. Only thing is, now I am getting greedy and want things like hot reloading etc.

Basically, I have a small script `servers.jl` that creates some endpoints and launches my Julia server. I call this with:

```
> yarn start:dev
```

My TSX is compiled fine, bundled and served by HTTP (it is beautiful actually). The thing is, if I now terminate the batch job, the HTTP server does not shut down and it still uses my port so if I try to run the server again, it errors.

```
ERROR: LoadError: IOError: listen: address already in use (EADDRINUSE)
```

Any idea how to deal with this so the server shuts down properly when the batch is terminated?

**Comment by quinnj** [comment]
If you can find a way to send a `SIGINT`, then the server will interrupt and gracefully close the port listening.

**Comment by EricForgy** [comment]
Interesting. Search `SIGINT` in the Julia docs returns nada 😅

**Comment by quinnj** [comment]
It's a linux/bash sort of thing. In Julia, it's `InterruptException`. For example, if you do `kill -s SIGINT [julia_pid]` from the command line, it will interrupt a julia process with pid `juliapid`. At the Julia REPL, you can do `ctrl + c` which sends a `SIGINT`.

**Comment by amellnik** [comment]
Is there any way to make the service release the port gracefully when the Julia process receives a SIGINT?  I'm running servers with something like `HTTP.serve(s, "0.0.0.0", 9000; verbose=false)` but hitting `ctrl - c` on the command line kills julia without freeing the port, and I have to kill it manually every time.

**Comment by EricForgy** [comment]
Any hints how to fix this?

I was making some decent progress incorporating HTTP.jl in a React, mobx-state-tree, Webpack workflow, but this issue killed my dreams so I built my served in Node.js 😅

**Comment by quinnj** [comment]
This is fixed in #301

**Comment by samoconnor** [comment]
... which I have this morning set aside to look over and merge !

**Comment by quinnj** [comment]
🎉
