### ISSUE TITLE
Support pipeline_limit server-side

### ISSUE THREAD

**Issue by quinnj** [JuliaWeb/HTTP.jl#322]
https://github.com/JuliaWeb/HTTP.jl/pull/301#discussion_r222556927

**Comment by samoconnor** [comment]
> Setting a limit may be an important server tuning option to avoid starting more concurrent tasks than is efficient. The implementation would be something like checking c.readcount - c.writecount < pipeline_limit in handle_transaction and blocking on wait(t.c.writedone) as needed.

**Comment by fonsp** [comment]
Did https://github.com/JuliaWeb/HTTP.jl/pull/783 change this issue?

**Comment by quinnj** [comment]
Yes, this is irrelevant now
