### ISSUE TITLE
Getting an error when try to send a request with a proxy!

### ISSUE THREAD

**Issue by TheOnlyArtz** [JuliaWeb/HTTP.jl#325]
Julia 1
HTTP.jl latest
MbedTLS.jl latest 
(latest to this date)

```julia
import HTTP

println("Sending request using proxy.")
request = HTTP.request("GET", "SOMEURL", proxy="socks5://IP")
println(request)
```
Sending request using proxy.
ERROR: LoadError: IOError(EOFError() during request(socks5://47.104.10.11:1080))

**Comment by samoconnor** [comment]
I don't think HTTP.jl understands `proxy=socks5:...`.
See https://github.com/JuliaWeb/HTTP.jl/issues/218#issuecomment-371428829 for an example of what is supported.
