### ISSUE TITLE
dear sir,we need your performance benchmark vs other languages

### ISSUE THREAD

**Issue by 564064202** [JuliaWeb/HTTP.jl#327]

**Comment by samoconnor** [comment]
dear @564064202,
Please explain more about the context of your request.

**Comment by 564064202** [comment]
how about the performance vs nodejs (libuv)

**Comment by 564064202** [comment]
can you upgrade your project to julia 1.*

**Comment by CarpeNecopinum** [comment]
@564064202 this library already works fine with Julia 1.* (at least 1.0.1, which is what I'm on)

**Comment by richardanaya** [comment]
I did some stress testing with apache bench with a basic hello world GET request

ab -n 10000 -c 100 http://0.0.0.0:8080/
nodejs
```
Percentage of the requests served within a certain time (ms)
  50%     17
  66%     20
  75%     23
  80%     25
  90%     32
  95%     35
  98%     42
  99%     84
 100%   1055 (longest request)
```

ab -n 10000 -c 100 http://0.0.0.0:8080/
HTTP.jl
```
Percentage of the requests served within a certain time (ms)
  50%     27
  66%     30
  75%     32
  80%     32
  90%     36
  95%     44
  98%    116
  99%   2093
 100%   2123 (longest request)
```

ab -n 10000 -c 1000 http://0.0.0.0:8080/
node.js
```
 50%     58
  66%     68
  75%     79
  80%     82
  90%    213
  95%   1112
  98%   1579
  99%   2869
 100%   2881 (longest request)
```

ab -n 10000 -c 1000 http://0.0.0.0:8080/
HTTP.jl
```
Percentage of the requests served within a certain time (ms)
  50%     39
  66%     42
  75%     43
  80%     46
  90%    143
  95%    157
  98%    204
  99%   4369
 100%   4403 (longest request)
```


ab -n 10000 -c 10000 http://0.0.0.0:8080/
nodejs
```
Percentage of the requests served within a certain time (ms)
  50%   1432
  66%   1449
  75%   1458
  80%   1463
  90%   1479
  95%   1491
  98%   1497
  99%   1501
 100%   1502 (longest request)
```

ab -n 10000 -c 10000 http://0.0.0.0:8080/
HTTP.jl
```

```

**Comment by christopher-dG** [comment]
You might have forgotten to send a first request to your Julia server, that 2s longest request looks like precompilation. On a second try I got this for c=100:
```
  50%     21
  66%     22
  75%     22
  80%     22
  90%     23
  95%     23
  98%     27
  99%    183
 100%    185 (longest request)
```

**Comment by richardanaya** [comment]
https://github.com/aj-monk/C10k.jl has even better benchmarking

**Comment by quinnj** [comment]
Some recent benchmarkings using the same `ab` tests from above vs node: https://discourse.julialang.org/t/http-jl-doesnt-seem-to-be-good-at-handling-over-1k-concurrent-requests-in-comparison-to-an-alternative-in-python/38281/29?u=quinnj
