### ISSUE TITLE
does it support http2.0

### ISSUE THREAD

**Issue by introspection3** [JuliaWeb/HTTP.jl#328]
Julia 1.*
HTTP.jl  Pkg.add(....) 
MbedTLS.jl Pkg.add(....)   now

**Comment by samoconnor** [comment]
HTTP/2 is a work in progress : https://github.com/JuliaWeb/HTTP.jl/blob/so/lazyprep/src/HPack.jl

**Comment by Nosferican** [comment]
@samoconnor any update on this?

**Comment by mkschulze** [comment]
@samoconnor how is the progress going, we would need HTTP/2 support for a Julia project and using this package would be a great help. thanks for letting us know.

**Comment by racinmat** [comment]
Is there any update or any blocker for this?

**Comment by mkschulze** [comment]
> Is there any update or any blocker for this?

HTTP/2 is now natively supported in Julia 1.6 via LibCURL. Maybe that would help you.

**Comment by fonsp** [comment]
Continued in https://github.com/JuliaWeb/HTTP.jl/issues/797

If you are looking for an HTTP/2 **client**, you can use https://github.com/JuliaLang/Downloads.jl
