### ISSUE TITLE
help,what's the meaning of using ..

### ISSUE THREAD

**Issue by 564064202** [JuliaWeb/HTTP.jl#332]
using ..IOExtras, ..Sockets

import ..ByteView
import ..@debug, ..@debugshow, ..DEBUG_LEVEL, ..taskid
import ..@require, ..precondition_error, ..@ensure, ..postcondition_error

**Comment by samoconnor** [comment]
https://docs.julialang.org/en/v1/manual/modules/#Summary-of-module-usage-1

**Comment by 564064202** [comment]
but what's parent module of ..ByteView

**Comment by samoconnor** [comment]
ByteView is defined in `IOExtras`.
In this instance the `import ..ByteView` is probably redundant.

**Comment by 564064202** [comment]
and what's the parent module of Sockets
![image](https://user-images.githubusercontent.com/12368358/47004372-ff4cf080-d163-11e8-9e6f-171288235ca9.png)

**Comment by samoconnor** [comment]
https://github.com/JuliaWeb/HTTP.jl/blob/c24513dbb56663b93a2eee8aa39f085bfd4d949c/src/HTTP.jl#L13

https://docs.julialang.org/en/v1.0/stdlib/Sockets/

**Comment by quinnj** [comment]
`..X` generally just means: go up to the parent level and import/using `X` from the parent module's scope.
