### ISSUE TITLE
What happened to KILL ?

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaWeb/HTTP.jl#334]
I'm trying to move WebSockets to HTTP#master, but it's not that straight forward...
E.g. how do I port:
```Julia
    tcpserver = Ref{HTTP.Sockets.TCPServer}()
    @async begin
        while !isassigned(tcpserver)
            sleep(sleeptime)
        end
        while true
            val = take!(server.in)
            val == HTTP.Servers.KILL && close(tcpserver[])
        end
    end
    HTTP.listen(host, port; tcpref = tcpserver, ...)
```
The whole HTTP repository contains no mention of kill anymore, so not even in any docstring.
Any help appreciated :) 
cc: @quinnj

**Comment by samoconnor** [comment]
`tcpref=` was replaced by the `server=` option in #301.

I think @quinnj's intention is that you should call `Sockets.listen` yourself and pass the resulting `TCPServer` to the `server=` option. Then, whenever your application logic decides to close the server it can do  `close(::TCPServer)`.

I'm not sure if you still need to pass `host` and `port` to `HTTP.listen` in this case. @quinnj ?

**Comment by SimonDanisch** [comment]
That does sound much nicer! I see if it works!

**Comment by samoconnor** [comment]
Also, please check here for other options that have changed:
https://github.com/JuliaWeb/HTTP.jl/blob/27bc366ca59aba93ef93800fe34cb0491179dd61/src/Servers.jl#L97-L115

I had a quick look at your PR 120 and a few things I see are:
 - There is no more `HTTP.Servers.check_rate_limit`, just pass `rate_limit::Rational{Int}` to `listen` (*** note underscore in `rate_limit` ***)
 - There is no more `ssl=` option
 - `tcpisvalid` is still there, but unless you have a custom function, no need to specify this option.
 - There is no more `ratelimits=` option, I think this is now a hard-wired global variable.

**Comment by Nosferican** [comment]
Close issue?
