### ISSUE TITLE
support `readbytes!`?

### ISSUE THREAD

**Issue by ssfrr** [JuliaWeb/HTTP.jl#337]
Julia 1.0.1
HTTP.jl 0.7.1
MbedTLS.jl 0.6.4

I'm not sure if this is the same issue as #329 or if this is more expected behavior, but here's a simpler MWE that throws the same error on the current release:

```julia
using HTTP

const STREAM_URL = "http://doppler.media.mit.edu/impoundment.opus"

readbuf = Vector{UInt8}(undef, 4096)
HTTP.open("GET", STREAM_URL) do stream
    readbytes!(stream, readbuf)
end
```

Is there a workaround to get `readbytes!` working? I have some other code that works fine when streaming files from disk, but I'm now trying to get it working streaming audio from the network. `read!` and `read` also throw the same error.

**Comment by samoconnor** [comment]
One of the reasons for not providing a specialised method for `readbytes!(::HTTP.Transaction, ...) `is that Base has two contradicting definitions of `readbytes!`, so it is difficult to know what behaviour to implement (See https://github.com/JuliaLang/julia/issues/24526)

They both say "at most nb bytes", but the second one says `all=` is `true` by default, which implies "Read ~at most~ _exactly_ nb bytes..."
```
help?> readbytes!
search: readbytes!

  readbytes!(stream::IO, b::AbstractVector{UInt8}, nb=length(b))

  Read at most nb bytes from stream into b, returning the number of bytes
  read. The size of b will be increased if needed (i.e. if nb is greater than
  length(b) and enough bytes could be read), but it will never be decreased.

  ────────────────────────────────────────────────────────────────────────────

  readbytes!(stream::IOStream, b::AbstractVector{UInt8}, nb=length(b); all::Bool=true)

  Read at most nb bytes from stream into b, returning the number of bytes
  read. The size of b will be increased if needed (i.e. if nb is greater than
  length(b) and enough bytes could be read), but it will never be decreased.

  See read for a description of the all option.
```

`read(::IO)` has the same problem:

```
  read(s::IO, nb=typemax(Int))

  Read at most nb bytes from s, returning a Vector{UInt8} of the bytes read.

  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  read(s::IOStream, nb::Integer; all=true)

  Read at most nb bytes from s, returning a Vector{UInt8} of the bytes read.

  If all is true (the default), this function will block repeatedly trying to read all requested bytes, until an error or
  end-of-file occurs. If all is false, at most one read call is performed, and the amount of data returned is
  device-dependent. Note that not all stream types support the all option.
```

**Comment by samoconnor** [comment]
At present, the best way to stream data from a HTTP Response Body is like this:
https://github.com/JuliaWeb/HTTP.jl/blob/df13276971d66a7cd9c54cfb88a5d0000773d419/src/HTTP.jl#L227-L233

`readavailable` is non-blocking and should end up yielding block sizes that match the underlying transport layer if the consumer is keeping up with the network.

**Comment by samoconnor** [comment]
However, we could add methods for `read(::HTTP.Stream)` and `readbytes!(::HTTP.Stream)` implemented in terms of `readavailable` and `unread!`. Or perhaps push the current `readavailable` implementation into a new internal `read_stream` function that is called by `read`, `readbytes!` and `readavailable`.

Something like this...
```julia
function Base.read(http::HTTP.Stream, nb)
    bytes = readavailable(http)
    l = length(bytes)
    if l > nb
        unread!(http, view(bytes, nb+1:l))
        l = nb
    end
    return view(bytes, 1:l)
end

function Base.readbytes!(http::HTTP.Stream, buf, nb=length(buf))
    bytes = read(http, nb)
    copyto!(buf, bytes)
    return length(bytes)
end
```

**Comment by ssfrr** [comment]
In my application I expect the consumer to be running faster than the server, so the `read` function should block the task until new data is available. It’s a live audio feed so ideally I just sit in a loop reading from the http stream, decoding and playing back the data as it’s available.

The reason I’m using `readbytes!` is specifically to avoid unnecessary buffer creation/GC and data copying, through to be honest that’s less critical and could likely be premature optimization.

If only a non-blocking read is available I guess I just add a `sleep` and poll for data? In your example above won’t the `while` loop be spinning and using 100% CPU?

**Comment by samoconnor** [comment]
`eof(::io)` blocks when there is no data available.
So, `while !eof(io) readavailable(io)` is efficient from a CPU usage point of view.

I hear you on the request to be able to read into a pre-allocated buffer! :) Parts of what is needed for this are in place. e.g. we have a method for `unsafe_read(t::HTTP.ConnectionPool.Transaction)` but not yet for `unsafe_read(t::HTTP.Stream)`.

**Comment by ssfrr** [comment]
Ah sorry, I missed that `readavailable` blocks if there’s no data, so ignore the last 2 questions.

**Comment by samoconnor** [comment]
Actually, HTTP.jl's `readavailable` never blocks.

I see that the doc for `? readavailable` says "blocking the task only if no data is available.", but HTTP.jl does not ever block in `readavailable`.

`eof()` blocks.

```
  eof(stream) -> Bool

  Test whether an I/O stream is at end-of-file. If the stream is not yet exhausted,
this function will block to wait for more data if necessary, and then return false.
```

**Comment by ssfrr** [comment]
Ah, I see. Thanks for the clarification.
