### ISSUE TITLE
listen readtimeout option 

### ISSUE THREAD

**Issue by samoconnor** [JuliaWeb/HTTP.jl#341]
A couple of issues with the `readtimeout` option:
 - when no data is received for 60 seconds `HTTP/1.1 408 Request Time-out\r\n\r\n` is sent in the middle of the response data stream even though a response header has already been sent.
 - `check_readtimeout` aborts the connection even after the request has been successfully received and the response data is being streamed.

https://github.com/JuliaWeb/HTTP.jl/blob/df13276971d66a7cd9c54cfb88a5d0000773d419/src/Servers.jl#L304-L318

For now I think we should disable this feature by default. @quinnj ?

To be useful, the timeout should probably only be triggered if we are actually waiting on more data.
e.g., if we haven't yet found the end of the header, or if there was a content-length header and we're still waiting on more body data, or if we're midway through reading a chunk.

Also, if we've already sent a successful response header, then it makes no sense to send status 408.
https://tools.ietf.org/html/rfc7231#section-6.5.7

The timeout should probably be suspended as soon as the handler writes a response header.
If a handler wants to read more body data after sending a response header, and it want's a timeout for that, it should probably implement that itself with semantics that make sense for the particular application.

**Comment by quinnj** [comment]
Yeah, I agree we should disable it by default for now until we can sort out some of these questions.

**Comment by EricForgy** [comment]
What is the solution? If no one beats me to it, I can submit a PR 😊 

This is going to break my packages, but look forward to v0.8 👍💪

**Comment by ExpandingMan** [comment]
Another bump for v0.8 release.  This package tends to be rather critical to a lot of things and getting fixes in tends to be easier when the release isn't so far behind the commits.

**Comment by samoconnor** [comment]
Note: commit 086157b9ba343b3df5c0abe46ff726c67ca2fafa referenced above does not seem to address this issue.
