### ISSUE TITLE
add support with data=nothing for HTTP request?

### ISSUE THREAD

**Issue by jingpengw** [JuliaWeb/HTTP.jl#345]
Julia 0.7 
HTTP.jl 0.7.0
MbedTLS.jl 0.6.4 

Currently, if I send a request with data=nothing, it will return an iteration error. Does it make sense to add this option?

**Comment by samoconnor** [comment]
Do you mean `body=`?

If you leave out the body argument then no body will be sent. Or you can pass `HTTP.nobody`, or `UInt8[]`, or `""` or `[]` or any kind of empty itterable.
```julia
const nobody = UInt8[]

function request(method, url, h=Header[], b=nobody;
                 headers=h, body=b, query=nothing, kw...)::Response
```
https://github.com/JuliaWeb/HTTP.jl/blob/df13276971d66a7cd9c54cfb88a5d0000773d419/src/HTTP.jl#L304-L307

Is there a reason that supporting `body=nothing` would be more convenient?

**Comment by jingpengw** [comment]
it is similar, but seems more intuitive because "" and [] have explicit type?

**Comment by samoconnor** [comment]
https://github.com/JuliaLang/julia/issues/29877

**Comment by jingpengw** [comment]
thanks for the argument. this is not really a problem, so I'll close here.
