### ISSUE TITLE
UnicodeError: invalid character index when sending image

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [JuliaWeb/HTTP.jl#35]
I just tried to respond to a request for an image and it failed with this error.
The same seems to happen when I build a response with a FIFOBuffer, which is filled from an image file in the REPL.
Note: I used the default headers, but I guess the response writing code doesn't care?

> Error showing value of type HTTP.Response:
> ERROR: UnicodeError: invalid character index
>  in getindex(::String, ::UnitRange{Int64}) at ./strings/string.jl:130
>  in show(::IOContext{Base.Terminals.TTYTerminal}, ::HTTP.Response, ::HTTP.RequestOptions) at /home/joel/.julia/v0.5/HTTP/src/types.jl:400
>  in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/plain")}, ::HTTP.Response) at ./REPL.jl:132
>  in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::HTTP.Response) at ./REPL.jl:135
>  in display(::HTTP.Response) at ./multimedia.jl:143
>  in print_response(::Base.Terminals.TTYTerminal, ::Any, ::Void, ::Bool, ::Bool, ::Void) at ./REPL.jl:154
>  in print_response(::Base.REPL.LineEditREPL, ::Any, ::Void, ::Bool, ::Bool) at ./REPL.jl:139
>  in (::Base.REPL.##22#23{Bool,Base.REPL.##33#42{Base.REPL.LineEditREPL,Base.REPL.REPLHistoryProvider},Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at ./REPL.jl:652
>  in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at ./LineEdit.jl:1579
>  in run_frontend(::Base.REPL.LineEditREPL, ::Base.REPL.REPLBackendRef) at ./REPL.jl:903
>  in run_repl(::Base.REPL.LineEditREPL, ::Base.##930#931) at ./REPL.jl:188
>  in _start() at ./client.jl:360
>

**Comment by quinnj** [comment]
Hmmmm, yes, currently we try and detect if the body is compressed and avoid showing if so, but in the case of non-plain-text bodies, we should be able to do something better here. Let me see if I can come up w/ something a little smarter.
