### ISSUE TITLE
Add timeout for reading CLOSE frame in WebSockets.close

### ISSUE THREAD

**Issue by christopher-dG** [JuliaWeb/HTTP.jl#350]
Basically just formalizing this FIXME since I've encountered a scenario that would benefit from it: https://github.com/JuliaWeb/HTTP.jl/blob/804bd7005fa7c2b91123058d0bd15f7fa69a453f/src/WebSockets.jl#L221

**Comment by quinnj** [comment]
This is now implemented in HTTP#master
