### ISSUE TITLE
Can you give an example how to use cookie in http request?

### ISSUE THREAD

**Issue by kopes18** [JuliaWeb/HTTP.jl#360]
I want to use custom cookies when http request, cant find any doc demonstrate this.

Julia 1
HTTP.jl 0.6.15

**Comment by kvantitative** [comment]
I have the same request. I have been using the Julia package Requests.jl but need to convert to HTTP.jl. This involve translating legacy client code using Requests.jl:

response=get(url; cookies = Dict("NAME" => "value"))

Where 'response' is the response from the server, url is the URL to the server, "NAME" is the name of a cookie stored locally and "value" is the value of that cookie.

I figured that HTTP.jl uses HTTP.CookieRequest.default_cookiejar, that seems to be a Dict. I did some experiments, and it seems like the key in this Dict is the server address (=url?) and the values is a list of cookies defined as HTTP.Cookies.Cookie("NAME", "value").  However, it is impossible for me to get this working, so an example the mimic the Request.jl code listed above would be highly appreciated.

Julia 0.7 and 1.0
HTTP.jl 0.6.15
