### ISSUE TITLE
Digest Authentication

### ISSUE THREAD

**Issue by quinnj** [JuliaWeb/HTTP.jl#37]
Marking this as up for grabs if someone feels so inclined to implement. From what I can tell, it's not generally viewed as a great method of authentication anyway, and I've never personally had a use-case. My only worry w/ supporting it is where we'd get an MD5 hash function (w/o requiring some huge dependency or something).

Happy to hear other users experiences and such on this.

**Comment by samoconnor** [comment]
MD5 hash: https://github.com/JuliaWeb/MbedTLS.jl/blob/e1d243fc4b10704cd79abfbdaf98952418d1a983/src/MbedTLS.jl#L9

**Comment by samoconnor** [comment]
Starting point for implementing `DigestAuthRequest.jl` would be to copy this: https://github.com/JuliaWeb/HTTP.jl/blob/b7b8e0f8c5baf1fd39c529fc264cb74284538fe3/src/BasicAuthRequest.jl#L18-L29
