### ISSUE TITLE
Request: All @info off by default?

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HTTP.jl#378]
Here is a question from Slack #gizmos

> Another question: Can I mute these:
> ```julia
> [ Info: Listening on: Sockets.InetAddr{Sockets.IPv4}(ip"127.0.0.1", 0x11c1)
> [ Info: Accept (0):  �    0↑     0↓    2s 127.0.0.1:4545:4545 ≣16
> [ Info: Accept (1):  �    0↑     0↓    0s 127.0.0.1:4545:4545 ≣16
> [ Info: Accept (2):  �    0↑     0↓    0s 127.0.0.1:4545:4545 ≣16
> [ Info: Accept (3):  �    0↑     0↓    0s 127.0.0.1:4545:4545 ≣16
> [ Info: Accept (4):  �    0↑     0↓    0s 127.0.0.1:4545:4545 ≣16 
> ```
>
> It may be helpful for you as developers but for me they are just spam.

I kind of agree with that sentiment 😅 

Now that HTTP.jl is being used in higher level packages where the users have little (or negative) interest in knowing about connections etc, i.e. they just expect things to work, spewing anything to the REPL feels like spam.

If I understand correctly, this can be handled by replacing

```julia
@info blah
```

with 

```julia
showinfo && @info blah
```

or something like that.

What do you think? `showinfo` should be `false` by default.

If this is alright, I can go ahead and submit a PR 🙏

**Comment by SimonDanisch** [comment]
duplicate of https://github.com/JuliaWeb/HTTP.jl/issues/294 ;)

**Comment by EricForgy** [comment]
Ah. Excellent 😊 

Will close this one then 👍
