### ISSUE TITLE
Please don't deprecate `register!`

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HTTP.jl#379]
I'n hopping onto `master` to see if there is anything I can do to help nudge a new tag along, but my code just told me that `register!` is deprecated and we need to use a macro instead.

Is that really necessary? I prefer not to use macros unless really necessary. Can we keep the old `register!`? 🙏

**Comment by quinnj** [comment]
As discussed on slack, `register!` wasn't precompile safe, so making it a macro makes it more explicit that registering should only be a static operation.
