### ISSUE TITLE
Some needed deprecations before tagging

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HTTP.jl#380]
I'll just record some observations as I try out `master`

### Routers

`register!` is broken. Before it was expecting a HandlerFunction so when you hop on `master`, it immediately breaks, so we need a deprecation for `HandlerFunction` (or something).

When I replace `HandlerFunction -> RequestHandlerFunction`, then I get a deprecation warning that `register!` is being replaced by `@register` 👎 

My initial reaction is I'm not a big fan (but maybe I am missing something so will try to keep an open mind).

**Comment by quinnj** [comment]
@EricForgy can you provide a reproduction of the broken `register!`? I wasn't able to reproduce anything breaking.

**Comment by quinnj** [comment]
Ah, I see. I didn't anticipate people using `HTTP.Handlers.HandlerFunction` directly, because you can just pass in a function directly and it wrapped it in `HandlerFunction` for you. I guess we can add a quick shim to make sure that doesn't break anything though.
