### ISSUE TITLE
Misleading warning message

### ISSUE THREAD

**Issue by mdpradeep** [JuliaWeb/HTTP.jl#387]
The warning message at https://github.com/JuliaWeb/HTTP.jl/blob/e9a83ef502ea88bbbd3803b42b9b9df77adb290d/src/Servers.jl#L54 is misleading. It sounds as if the requests are throttled while it is really not.

**Comment by fredrikekre** [comment]
https://github.com/JuliaWeb/HTTP.jl/pull/701
