### ISSUE TITLE
When will the newest version release?

### ISSUE THREAD

**Issue by chengchingwen** [JuliaWeb/HTTP.jl#401]
Julia 1.1
HTTP.jl 0.8.0

I'm currently using the request with cookies in my own package, but even the newest release version right now doesn't have a fully functional cookies. I need a the master branch release to release my own package. Are there any plan for make a new release?

**Comment by chengchingwen** [comment]
bump

**Comment by quinnj** [comment]
New release tagged https://github.com/JuliaWeb/HTTP.jl/commit/7e9284dc2cc7a87da2619f0482b99b570ca4d77f
