### ISSUE TITLE
Proxy support - Automatically picking from environment

### ISSUE THREAD

**Issue by Ayushk4** [JuliaWeb/HTTP.jl#403]
>This issue is a follow up after #218 and https://github.com/JuliaWeb/HTTP.jl/issues/218#issuecomment-449367875

Currently, for using proxy support, we have to pass it as a parameter. eg - `HTTP.request("GET", url, proxy=proxy)`.
However, a lot of packages like Github.jl, DataDeps.jl ..... have HTTP.jl as a dependency. For these 200+ packages to operate behind a proxy, the packages would have to be edited and have an optional parameter for the proxy to be passed. 

Instead of this, I think it will be better to have HTTP.jl use the _system/environment proxy_ (if present in the system), besides also having the option to override it. (the same way it currently is)

**Comment by ancapdev** [comment]
Not adding anything, but voicing my support. I'm running into the same problem with the AWS packages, and have fallen back to calling the python AWS CLI from Julia for the time being. Global proxy configuration, through environment variables or a config API would be very helpful.

**Comment by quinnj** [comment]
I've implemented support for this in a PR: https://github.com/JuliaWeb/HTTP.jl/pull/423. If people can help test, that'd be great. To try out that branch, you can do `] add HTTP#jq/proxy` from the REPL. Once you're done testing the branch, you can do `] free HTTP` to go back to the current release.
