### ISSUE TITLE
using a router with stream handlers

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [JuliaWeb/HTTP.jl#407]
I am trying to use a router that links to stream handlers:

```
const router = HTTP.Router()
HTTP.@register(router, "GET", "/", handler)
HTTP.serve(router, HTTP.Sockets.localhost, port; stream=true)
```

But I get an error:

```
┌ Error: error handling request
│   exception =
│    MethodError: no method matching handler(::HTTP.Messages.Request)
│    Closest candidates are:
│      handler(::HTTP.Streams.Stream)
```

I looks like `HTTP.serve` is ignoring the `stream=true` argument or simply that the router can not receive streams. Is it the expected behavior? Is there a workaround?

Julia 1.1
HTTP.jl 0.8

**Comment by jvo203** [comment]
Hi, have you solved this issue? I am having the same problem, how did you solve it?

**Comment by jvo203** [comment]
Is this what you did? Wrap the handler using the StreamHandlerFunction? It seems to work for me.

```
HTTP.@register(
    FITSWEBQL_ROUTER,
    "GET",
    "/*/image_spectrum/",
    HTTP.StreamHandlerFunction(streamImageSpectrum)
)
```

**Comment by Hugo-Trentesaux** [comment]
@jvo203 It has been a while and I can't remember if I fixed it. However, having a look at [the project I was working on](https://gitlab.com/Hugo-Trentesaux/rlsjl/-/blob/master/modules/requesthandler.jl#L18-21) when I asked the question, it seems that I found an other way to handle stream by doing a "manual routing" through a `Dict`.

**Comment by jvo203** [comment]
Thank you.
