### ISSUE TITLE
FIFOBuffer does not follow `read(::Any, ::Type{UInt8})` standard

### ISSUE THREAD

**Issue by omus** [JuliaWeb/HTTP.jl#41]
I'm trying to use `readbytes!` with `FIFOBuffer` but I'm encountering errors since `read(::FIFOBuffer, ::Type{UInt8})` returns a `Tuple{UInt8,Bool}` rather than the typical `UInt8`.

```julia
julia> using HTTP

julia> f = HTTP.FIFOBuffer(5);

julia> b = Array{UInt8}(3);

julia> write(f, [0x01, 0x02, 0x03, 0x04, 0x05])
5

julia> readbytes!(f, b)
ERROR: MethodError: Cannot `convert` an object of type Tuple{UInt8,Bool} to an object of type UInt8
This may have arisen from a call to the constructor UInt8(...),
since type constructors fall back to convert methods.
 in readbytes!(::HTTP.FIFOBuffer, ::Array{UInt8,1}, ::Int64) at ./io.jl:351
 in readbytes!(::HTTP.FIFOBuffer, ::Array{UInt8,1}) at ./io.jl:342

julia> io = IOBuffer([0x01, 0x02, 0x03, 0x04, 0x05])
IOBuffer(data=UInt8[...], readable=true, writable=false, seekable=true, append=false, size=5, maxsize=Inf, ptr=1, mark=-1)

julia> readbytes!(io, b)
3
```

Could you use a different function name for this behaviour if it is required?

**Comment by quinnj** [comment]
Yeah, it'd probably be better to call it something different. It started out returning like normal, but then I realized I needed to return more, but kept the function name the same.

**Comment by omus** [comment]
I'm thinking that `Base.read(f::FIFOBuffer, ::Type{Tuple{UInt8,Bool}})` would be appropriate.

**Comment by omus** [comment]
I'm working on this at the moment as it's blocking some of my work
