### ISSUE TITLE
Suggested way to do multithreading?

### ISSUE THREAD

**Issue by richardanaya** [JuliaWeb/HTTP.jl#413]
How would the HTTP.jl recommend doing multithreaded servers at the moment that share a similar port to spread out CPU load? Is there anything upcoming we should be aware of?

**Comment by quinnj** [comment]
The only supported solution right now is to set `reuseaddr=true`, which allows multiple Julia processes (either started completely separately, or via `Distributed.addprocs` to each start `HTTP.serve` or `HTTP.listen` and listen on the same address/port, thus distributing the load. Note this is generally only supported on linux/unix/osx, not windows.

**Comment by richardanaya** [comment]
That’s not true, please reopen.

As per docs

   - If reuseaddr=true, multiple threads or processes can bind to the same
   address without error if they all set reuseaddr=true, but only the last
   to bind will receive any traffic.

**Comment by richardanaya** [comment]
I observed this not working on osx

**Comment by NLaws** [comment]
@quinnj can you please provide an example of how to use `Distributed.addprocs`?

I have been trying:
```
using Distributed
addprocs(1, exeflags="--project")
@everywhere using HTTP, JSON
@everywhere include("MyModule.jl")
@everywhere using .MyModule


@everywhere function job(req::HTTP.Request)
    d = JSON.parse(String(req.body))
    timeout = pop!(d, "timeout_seconds")
    m = model_from_my_module(timeout)
    results = method_from_my_module(m, d)
    return HTTP.Response(200, JSON.json(results))
end

@everywhere ROUTER = HTTP.Router()
@everywhere HTTP.@register(ROUTER, "POST", "/job", job)

@async HTTP.serve(ROUTER, "0.0.0.0", 8081)
@spawnat 2 HTTP.serve(ROUTER, "0.0.0.0", 8081)
```

The code all loads in fine, but then just exits without keeping up the servers. 

(Also, using `const` in front of `ROUTER` as shown in the docs does not work due to:
```
Cannot transfer global variable ROUTER; it already has a value.
└ @ Distributed /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/clusterserialize.jl:186
```
)

**Comment by quinnj** [comment]
@NLaws, do you have any kind of backtrace when the servers exit? It'd be helpful to see what error is being thrown or why they are stopping serving. Note in the discussion above that you should be passing `reuseaddr=true` to your `HTTP.serve` calls. I haven't tried doing this in a while, so forgive the lack of a more solid response at the moment.
