### ISSUE TITLE
Support multi-threaded HTTP.jl

### ISSUE THREAD

**Issue by richardanaya** [JuliaWeb/HTTP.jl#414]
The current method ascribed doses not work using reuseaddr (tested on Debian) as per docs

If reuseaddr=true, multiple threads or processes can bind to the same address without error if they all set reuseaddr=true, but only the last to bind will receive any traffic.

**Comment by quinnj** [comment]
I've tested `reuseaddr=true` on a few linux flavors and it all seems to be working as expected, which is:
> Additionally the kernel performs some "special magic" for SO_REUSEPORT sockets that isn't found in other operating systems: For UDP sockets, it tries to distribute datagrams evenly, for TCP listening sockets, it tries to distribute incoming connect requests (those accepted by calling  accept()) evenly across all the sockets that share the same address and port combination. Thus an application can easily open the same port in multiple child processes and then use SO_REUSEPORT to get a very inexpensive load balancing.

Now, I noticed that on OSX, it is indeed the case that its behavior is as you described, so while OSX allows multiple bindings to the same address/port, only a single process will actually accept connections; I also noticed that if the process that was accepting connections exits, a secondary process that was also listening will start to accept connections. So we should check for that and possibly warn when using `reuseaddr` on OSX.

**Comment by richardanaya** [comment]
Great news!

**Comment by quinnj** [comment]
I added a warning on osx if `reuseaddr=true` is used.

**Comment by richardanaya** [comment]
Thank you sir!
