### ISSUE TITLE
This functionality should be in Julia base library

### ISSUE THREAD

**Issue by sylvaticus** [JuliaWeb/HTTP.jl#415]
At least the client side should reside in Julia base library, not in a third-party package.. please consider this with Julia committers..

**Comment by fredrikekre** [comment]
See https://github.com/JuliaLang/julia/issues/27043

Just out of curiosity, whats wrong with this beeing a package?

**Comment by sylvaticus** [comment]
Thank you. So I'm not the only one to think this ;-)

I just feel this is a low-level enough functionality that should have a more "standard" or "official" status from which the other packages could depend from.

Secondly ( _much_ secondly..) some people may look down at Julia thinking that "this programming language needs an external package even to do such a basic thing!"

**Comment by fredrikekre** [comment]
There is now a Downloads.jl stdlib for client usage. I don't think a HTTP server is needed in base.
