### ISSUE TITLE
0.8.1 shouldn't have been a patch release?

### ISSUE THREAD

**Issue by rofinn** [JuliaWeb/HTTP.jl#424]
Julia 0.6.2 
HTTP.jl 0.8.1 
MbedTLS.jl 0.6.8 -- Please specify versions

The underlying API was changed during a patch release. Since `StatusError` doesn't seem to be exported so I'd be fine with a minor release, but this did break some mocking/test code we have which makes me think that changes like that shouldn't be in patch releases?

**Comment by quinnj** [comment]
Oops! I've added back in a backwards compatible constructor and I'll tag a new release. Thanks for reporting.

**Comment by rofinn** [comment]
Great, thank you.
