### ISSUE TITLE
Headers with `-` inside the key value can't be set

### ISSUE THREAD

**Issue by George3d6** [JuliaWeb/HTTP.jl#426]
Julia 1.1.1
HTTP.jl 0.8.3
MbedTLS.jl -- not installed (can't find it via `Pkg.installed()`)

From the documentation gotten from `?HTTP.request` it seems that this syntax should work for setting headers:

`HTTP.request("GET", "url"; headers=Dict("a" => "b"))`

however if I use a `-` in the key value (e.g. `user-agent`) I get: the error:

```
ERROR: MethodError: no method matching getindex(::Pair{String,Any}, ::String)
Closest candidates are:
  getindex(::Pair, ::Int64) at pair.jl:59
  getindex(::Pair, ::Real) at pair.jl:60
Stacktrace:
 [1] macro expansion at main.jl:27 [inlined]
 [2] macro expansion at ./task.jl:244 [inlined]
 [3] get_image_urls() at main.jl:20
 [4] main() at main.jl:48
 [5] top-level scope at none:0
```

Would you be able to document why this might not work ? How to properly set headers ? And how to properly set the `user-agent` in case this doesn't follow the same rules as normal headers in your interface.

**Comment by fredrikekre** [comment]
What exactly did you try? This works:
```
HTTP.request("GET", "https://github.com"; headers = Dict("User-Agent" => "Julia"))
```

**Comment by George3d6** [comment]
`"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"` was the value I introduced... though testing it now seems to work, which is really weird, I guess I may have introduced some extra character or comma somewhere. Strange, well, since I can't currently reproduce I will close the issue.
