### ISSUE TITLE
Websockets uses insecure random for Sec-WebSocket-Key and mask

### ISSUE THREAD

**Issue by chethega** [JuliaWeb/HTTP.jl#437]
Consider the [this](https://github.com/JuliaWeb/HTTP.jl/blob/2b108234acef05e1f7cac4e67efd1de8a94450e0/src/WebSockets.jl#L82) and [this](https://github.com/JuliaWeb/HTTP.jl/blob/2b108234acef05e1f7cac4e67efd1de8a94450e0/src/WebSockets.jl#209) line.

Here, we use the base `rand`, which uses Mersenne twister. This is not a cryptographically secure random source.

Per [rfc6455](https://tools.ietf.org/html/rfc6455#section-5.3), "The masking key needs to be unpredictable; thus, the masking key MUST be derived from a strong  source of entropy, and the masking key for a given frame MUST NOT make it simple for a server/proxy to predict the masking key for a subsequent frame."

After reading the websockets spec and the paper that lead to this requirement, this is not a severe problem. Still, would be better to fix this and use a secure random source.

A possibility could be to simply use `const CSPRNG = Random.RandomDevice()`.

Cf general discussion [here](https://github.com/JuliaLang/julia/issues/32954).

**Comment by quinnj** [comment]
This is a good suggestion; a PR to implement this is [here](https://github.com/JuliaWeb/HTTP.jl/pull/844)
