### ISSUE TITLE
Possible very fast C dependencies for HTTP/2, HTTP/3 and HPACK

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaWeb/HTTP.jl#448]
FYI: Litespeed open sourced code in 2017, and again days ago, 

I thought I should let you know, found HPACK.jl which pointed here (and while it claims Julia-only; potentially good-to-have, not unless actually as fast as possible and maintained, and I think we should use be/use this fastest code in "the world").

They probably have more features, and at least for the case in b) 2 to 12 times faster, so seems Julia should use it:

a)
https://blog.litespeedtech.com/2019/09/11/litespeed-quic-http3-open-source/

"LiteSpeed Technologies is releasing its QUIC and HTTP/3 library under an open-source license. This library, written in the C programming language, contains both client and server logic as well as [..]
The following QUIC and HTTP/3 versions are currently supported:
* Q039
* Q043
* Q046
* h3-22

Q039, Q043, and Q046 are versions of the Google QUIC protocol. Q046 is used by the current version of Chrome (Chrome 76). h3-22 is the experimental precursor to HTTP/3, the next-generation HTTP protocol. We will update the library as new gQUIC and HTTP/3 versions are released."

b)
Under MIT licence already ported to Windows and with bug fixes seems to hard to pass up:

https://github.com/litespeedtech/ls-qpack
"Fix fast Huffman decoder: detect bad EOS in all cases 	10 days ago"

https://blog.litespeedtech.com/2019/09/11/litespeed-quic-http3-open-source/

"Our web server outperforms nginx by a factor of 2 to 12 in several readily reproducible benchmarks.

How do we do it? The truth is, when we are not adding new features, we are optimizing existing code. [..]
Why do we do it? HTTP/2 is on its way to become the dominant web protocol. HTTP/2 performance is crucial for any modern web server. And, of course, we want to be faster than everyone else.

This article describes one of the optimizations that made ours the fastest HTTP/2 implementation in the world.

Well-led software projects are not afraid to borrow good ideas, for the hubris of the not-invented-here syndrome often leads to suboptimal implementations. Such is the story of the HPACK Huffman decoder in today’s major web servers. [..]
by Renato Pajarola in his paper Fast Prefix Code Processing. It is significantly faster than prior methods. The idea is to process compressed data several bits — instead of one bit — at a time. Tatsuhiro chose 4 bits as input length. 4 is a good number. [..]
Presented with normal input, the LiteSpeed Fast Huffman Decoder almost doubles the speed of the nginx Huffman decoder. [..]
We also use the Fast Huffman Decoder in our QPACK library, speeding up our HTTP/3 stack. We intend to maintain performance leadership with next-generation HTTP version as well.

While writing this article, I found two more optimizations that would make the Fast Huffman Decoder even faster. Stay tuned!"

Older: https://blog.litespeedtech.com/2017/10/02/developers-corner-why-use-litespeed-quic-library/

See also: https://blog.litespeedtech.com/2019/08/15/litespeed-addresses-http-2-dos-advisories/

**Comment by quinnj** [comment]
HTTP.jl is for pure-Julia code only.
