### ISSUE TITLE
HTTP.jl should send a User-Agent header by default

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaWeb/HTTP.jl#450]
HTTP RFC says that clients "SHOULD" send a user agent by default. I would propose
```
User-Agent: HTTP.jl/$version
```
where `version` is the version number of the HTTP library. GitHub, for example, refuses to serve requests for URLs when the request doesn't have a user agent. Doesn't matter what it is, but it has to be set.

**Comment by oxinabox** [comment]
See https://github.com/JuliaWeb/HTTP.jl/issues/161

Some http libraries default it.
Others do not
List in that issue

Which includes

**Comment by StefanKarpinski** [comment]
This has come up on Slack again when someone is trying to use HTTP to duplicate some simple Python code and it doesn't work because HTTP.jl doesn't send a user agent by default and the service refuses to serve data without a user agent. I will repeat what I wrote there:

> The notion that people using HTTP.jl are going to figure out that something isn’t working because they need to send a user agent, then learn about user agents, then set a user agent is… frankly, daft.

Let's consider the drawbacks of sending a default user agent versus not sending one:

* If we send a user agent by default and some application ignores the recommendation to change it, then the service getting requests will only know that some program using the HTTP.jl package is connecting to their service, not which specific application is connecting. Everything will work.

* If we don't send a user agent by default, then people will try to do things that work in other languages (e.g. Python), it will mysteriously not work and then they will be stumped. I happened to figure it out, but you know, I did my PhD work in computer networking and it still took me a while. These people will conclude that HTTP.jl and possible Julia in general is broken and janky and will go back to using Python because we refused to pick a default that "just works". Most HTTP.jl users will still not set a user agent because many services don't require it, and those services will have zero information about the software that's making request because instead of having a generic "HTTP.jl" user agent string, they will have no user agent string at all.

So yeah, I don't really understand the decision not to send a user agent string by default.

**Comment by StefanKarpinski** [comment]
There's another point... The immediate question upon telling someone about `HTTP.setuseragent!` is "and what would I set it to?" So is each user have to make up a name for their throwaway script that just wants to make an HTTP request? That seems strictly worse than sending `HTTP.jl/v1.2.3` or whatever the correct HTTP.jl version number is by default. It just doesn't make sense for the user to pick the user agent in most casual use cases.

**Comment by quinnj** [comment]
I agree we should set a user-agent by default; implemented in https://github.com/JuliaWeb/HTTP.jl/pull/482.

In addition to @StefanKarpinski's excellent points, I think it's also reasonable to expect users concerned with/needing a custom user-agent, to be familiar w/ the documentation and how to set that on their own, while casual users/scripts will have things work by default.
