### ISSUE TITLE
How do I simply push messages over WebSockets?

### ISSUE THREAD

**Issue by arjensuijker** [JuliaWeb/HTTP.jl#452]
Not an issue but a question. I'm having a lot of trouble figuring out how to do something so simple. I want to establish just one websocket from julia as the server and then push json through that socket at random intervals from elsewhere in my code. Any suggestions?

**Comment by itsdfish** [comment]
Here is one possible solution:

Paste into one REPL:
```
using HTTP, JSON

@async HTTP.WebSockets.listen("127.0.0.1", UInt16(8081)) do ws
           while !eof(ws)
               recieved_message = readavailable(ws)
               isempty(recieved_message) ? break : nothing
               data = JSON.parse(String(recieved_message))
               println(data)
               say = rand() < .1 ? "bye" : "hello"
               send_message = Dict(:x=>rand(), :y =>say)
               jmessage = JSON.json(send_message)
               write(ws, jmessage)
           end
       end
```

Paste into a different REPL:
```
using HTTP, JSON

HTTP.WebSockets.open("ws://127.0.0.1:8081") do ws
      running = true
      while running
              send_message = Dict(:x=>.34, :y=>"hello")
              data = JSON.json(send_message)
              write(ws, data)
              recieved_message = readavailable(ws)
              message = JSON.parse(String(recieved_message))
              println(message)
              running = message["y"] == "bye" ? false : true
      end
      println("Exiting...")
      println()
  end
```

I don't think you need to do this in different REPLs, but it makes the demonstration a bit more convincing (to me).

In the first block of code, the line   `isempty(recieved_message) ? break : nothing` will prevent the code from crashing at JSON.parse. For some reason, each message is followed by a empty UINT16 vector. Perhaps there is a better solution, but this seems to work.

**Comment by arjensuijker** [comment]
Thank you for your answer. I'm sorry for my late reply, the project was on hold for a bit. Your solution works perfectly, but is not entirely applicable to my situation. I think I didn't quite manage to word my question correctly. Please allow me to rephrase my situation:

I have some processes running in Julia. These processes obtain results at unpredictable intervals. The results of these processes should be pushed immediately to a browser-based javascript client. I have figured out the JavaScript part, but how do I get Julia to push messages over the WebSocket non-periodically without holding up the rest of my code AND without having to wait for requests from the client?

**Comment by essenciary** [comment]
@arjensuijker Not sure if it's feasible to switch to Genie at this point in your project, but Genie provides infrastructure for WebSockets messaging over the WebChannels API. You can register WebChannels, have JS clients subscribed to individual channels, and then receive and push messages over the channel (or broadcast over all the channels).

**Comment by arjensuijker** [comment]
I looked at Genie as an option, but it seemed like it would be a little overkill for my small project. But if it provides better websocket support for my situation then I might try it. Genie looks like a great project anyway, will be fun to try out. I couldn't find good documentation on the webchannels / websockets though. Could you point in the right direction to get started?

**Comment by essenciary** [comment]
The feature is overdue for documenting :) If you're not in a big hurry, I can add a section on it, it's been on my todo for a while so I can move it up a bit.

**Comment by itsdfish** [comment]
I would also be interested in documentation for those features and a simple working example if possible.

**Comment by arjensuijker** [comment]
That would be great! As an added advantage, you would be adding even more unique selling points to Genie ;) .

**Comment by arjensuijker** [comment]
@essenciary Any progress? Can I help?

**Comment by essenciary** [comment]
@arjensuijker on its way! Thanks for the help offer, will appreciate feedback on the docs and code once it's up! Need a few more days though, busy period!

**Comment by essenciary** [comment]
@arjensuijker https://genieframework.github.io/Genie.jl/documentation/17--Working_with_Web_Sockets.html -- let me know if this is what you're looking for, feedback appreciated!
