### ISSUE TITLE
ConnectionPool isn't threadsafe

### ISSUE THREAD

**Issue by kcajf** [JuliaWeb/HTTP.jl#454]
following on from https://github.com/JuliaLang/julia/issues/33429

It appears ConnectionPool isn't threadsafe. I'm trying to work out the minimal correct locking to make it work. In https://github.com/JuliaWeb/HTTP.jl/blob/master/src/ConnectionPool.jl#L371, do you think `poollock` and `poolcondition` can be combined into one `Threads.Condition`? I'm not entirely sure of their individual purposes, but from first glance it seems like they should be able to.

**Comment by tk3369** [comment]
Following Jeff B's comment from the other issue, we could possibly change the `Condition` object to `Threads.Condition`.  

Looks like the `closeall` function needs some work... I would guess the `close` function call may throw exception so we could add a `tryclose` function with try/catch wrapped around it.  

https://github.com/JuliaWeb/HTTP.jl/blob/5089010c05f33ad680e2ed28ea18b4eef774051a/src/ConnectionPool.jl#L379-L388

Also, shall we consider using this locking style according to the recent [multi-threading blog](https://julialang.org/blog/2019/07/multithreading)?  So then we don't need a separate `ReentrantLock`...

```julia
lock(cond::Threads.Condition)
try
    while !ready
        wait(cond)
    end
finally
    unlock(cond)
end
```

**Comment by rana** [comment]
Encountered a bug related to HTTP ConnectionPool too; likely the same. Glad you're looking into it. Looking forward to a fix. Thank you.

```
 Info: Error in @async writebody task. Server likely closed the connection unexpectedly. Only an issue if unable to read the response and this error gets re-thrown. 
│   exception =
│    concurrency violation detected
│    Stacktrace:
│     [1] error(::String) at ./error.jl:33
│     [2] concurrency_violation() at ./condition.jl:8
│     [3] assert_havelock at ./condition.jl:25 [inlined]
│     [4] assert_havelock at ./condition.jl:48 [inlined]
│     [5] assert_havelock at ./condition.jl:72 [inlined]
│     [6] notify(::Base.GenericCondition{Base.AlwaysLockedST}, ::Any, ::Bool, ::Bool) at ./condition.jl:126
│     [7] #notify#465 at ./condition.jl:124 [inlined]
│     [8] notify at ./condition.jl:124 [inlined] (repeats 2 times)
│     [9] closewrite(::HTTP.ConnectionPool.Transaction{MbedTLS.SSLContext}) at /home/rana/.julia/packages/HTTP/lZVI1/src/ConnectionPool.jl:260
│     [10] writebody(::HTTP.Streams.Stream{HTTP.Messages.Response,HTTP.ConnectionPool.Transaction{MbedTLS.SSLContext}}, ::HTTP.Messages.Request, ::Array{UInt8,1}) at /home/rana/.julia/packages/HTTP/lZVI1/src/Streams.jl:120
└     [11] (::HTTP.StreamRequest.var"#2#3"{HTTP.ConnectionPool.Transaction{MbedTLS.SSLContext},HTTP.Messages.Request,Array{UInt8,1},HTTP.Streams.Stream{HTTP.Messages.Response,HTTP.ConnectionPool.Transaction{MbedTLS.SSLContext}}})() at ./task.jl:333
```

**Comment by quinnj** [comment]
Fixed in https://github.com/JuliaWeb/HTTP.jl/pull/479
