### ISSUE TITLE
uri_reference_regex doesn't seem threadsafe

### ISSUE THREAD

**Issue by kcajf** [JuliaWeb/HTTP.jl#456]
I've had some odd errors in the vicinity of 
https://github.com/JuliaWeb/HTTP.jl/blob/master/src/URIs.jl#L94
in multithreaded code. It definitely isn't threadsafe, since it stores state and gets operated on in a few places e.g. 
https://github.com/JuliaWeb/HTTP.jl/blob/master/src/URIs.jl#L126

A simple solution might be to have a threadlocal version of this object?

**Comment by kcajf** [comment]
Same for all the global `RegexAndMatchData` consts in Parsers.jl 

the whole library probably needs a general checking over to find any other global state

**Comment by kcajf** [comment]
Any thoughts on this?

**Comment by quinnj** [comment]
Fixed in https://github.com/JuliaWeb/HTTP.jl/pull/479
