### ISSUE TITLE
Equivalent to curl --insecure

### ISSUE THREAD

**Issue by jeremiedb** [JuliaWeb/HTTP.jl#462]
Julia 1.1.1
HTTP.jl 0.8.6
MbedTLS.jl 0.6.8

I'm trying to perform a GET request with the equivalent to `-k` or `--insecure` flag in curl. 
In the R httr package, equivalent behavior is obtained with : `httr::set_config(config(ssl_verifypeer = 0L))`

With http.jl, the following resulted in error 403 - denied: 

```
conf = MbedTLS.SSLConfig()
MbedTLS.authmode!(conf, MbedTLS.MBEDTLS_SSL_VERIFY_REQUIRED)
r = HTTP.request("GET", "https://localhost:5000/v1/portal/portfolio/accounts", sslconfig=conf)
```

I tried some variations with `MbedTLS.MBEDTLS_SSL_VERIFY_NONE` and `MbedTLS.MBEDTLS_SSL_VERIFY_UNSET` but without success. 

Any way to perform the equivalent to: 

```
curl --insecure https://localhost:5000/v1/portal/portfolio/accounts
```

**Comment by benelsen** [comment]
You should be able to just pass `require_ssl_verification = false` or `sslconfig = SSLConfig(false)`.
I tested this with `v0.8.6`, but only against one local server with a self-signed cert.

I did discover that once `sslconfig = SSLConfig(false)` has been passed future requests aren't verified (even when passing `sslconfig = SSLConfig(true)`) as long as the connection is reused (60s per default). Maybe the connection should be closed once a request with a different `sslconfig` is made?

**Comment by jeremiedb** [comment]
It unfortunately doesn't seem to do the trick. The 2 following commands result in a 403 Forbidden error: 

```
r = HTTP.request("GET", "https://localhost:5000/v1/portal/portfolio/accounts", sslconfig=SSLConfig(false))
r = HTTP.request("GET", "https://localhost:5000/v1/portal/portfolio/accounts", require_ssl_verification=false)
```

While the following curl works fine: 

```
curl --insecure https://localhost:5000/v1/portal/portfolio/accounts
```

**Comment by benelsen** [comment]
I'm sorry, I read the original question then checked my solution but forgot about the 403 you mentioned when replying.
You shouldn't be able to get a 403 anyhow if the verification fails, the request should throw an `IOError`. (Have you checked this is what happens when doing a request with verification on?)

My suspicion is that the server might require some additional headers to be set. For example `User-Agent` or `Accept`.

**Comment by jeremiedb** [comment]
How would such headers be set (I couldn't find example in the docs)?

Something like that?:
```
r = HTTP.request("GET", "https://localhost:5000/v1/portal/portfolio/accounts", Accept="application/json", sslconfig=MbedTLS.SSLConfig(false))
```

Still, wouldn't it be counterintuitive that a header be required while both the vanilla curl command line or the R httr packages doesn't?

**Comment by benelsen** [comment]
I don't know what httr does by default, but curl sends both `User-Agent: curl/x.y.z` and `Accept: */*` while HTTP.jl does send neither (there are different schools of thought on this https://github.com/JuliaWeb/HTTP.jl/issues/161 https://github.com/JuliaWeb/HTTP.jl/issues/450).
(Libcurl apparently doesn't set it, while calling curl does.)

You can pass headers as a collection of Pairs or Tuples
> HTTP.request(method, url [, headers [, body]]; <keyword arguments>]) -> HTTP.Response
> headers can be any collection where [string(k) => string(v) for (k,v) in headers] yields Vector{Pair}. e.g. a Dict(), a Vector{Tuple}, a Vector{Pair} or an iterator.

for example:
```
HTTP.request("GET", "https://localhost:8444/foobar.txt", ["User-Agent" => "ExampleProject/0.1.0", "Accept" => "*/*"], require_ssl_verification = false)
```

There are some servers that require a User-Agent to be set, and some only return content when there's an explicit match on the Accept header.

**Comment by jeremiedb** [comment]
Now that's a win! Effectively both `User-Agent` and `Accept` fields were needed in the request. 
Thanks for providing the extra context around this topic, helpful making sense of what's going on.  

Noob question, but is it normal that the above quote regarding the header being vector of Pairs seems not having made it to the docs? https://juliaweb.github.io/HTTP.jl/dev/public_interface/#Requests-1

Thanks for the help!

**Comment by benelsen** [comment]
It should be in the docs, but currently isn't because the reference to the docstring got broken in the last release. There's a [PR](https://github.com/JuliaWeb/HTTP.jl/pull/446) to fix this, but it's unfortunately not yet merged in.

Overall not much changed for `HTTP.request` since 0.6 so you can refer to those https://juliaweb.github.io/HTTP.jl/v0.6/#Requests-1 and/or check against the docstring https://github.com/JuliaWeb/HTTP.jl/blob/master/src/HTTP.jl#L35 directly.
