### ISSUE TITLE
InexactError resulting from page reload (plus random status field in errors)

### ISSUE THREAD

**Issue by zot** [JuliaWeb/HTTP.jl#471]
Julia 1.3.0-rc2.0
HTTP.jl 0.8.7
MbedTLS.jl 0.X.X -- not sure about this but I'm not using TLS

Reloading a page in my app is throwing an exception here: https://github.com/JuliaWeb/HTTP.jl/blob/84a0a2d9030b9a73fdc8a16c511ea21e3f77c36d/src/WebSockets.jl#L272

The problem is that on a `WS_CLOSE`, line 269 creates a `UInt16` from the first two bytes of the header and then uses that to initialize `WebSocketError.status::Int16`. Sometimes the high bit is set, which makes a `UInt16` that's out of the `Int16` range.

I'm using Brave for testing. I don't know the details of the `WebSocket` protocol but maybe something's off with using the first two bytes as a status code (the first two bytes appear to have arbitrary values on a  `WS_CLOSE`) or else maybe Brave has an error in its `WebSocket` code (Brave is based on the Chromium code base).

**Comment by fonsp** [comment]
Had the same issue when running the [README.md code to run a WebSocket server](https://github.com/JuliaWeb/HTTP.jl#websocket-examples), and opening and closing a connection from chrome (not consistently). It looks like we just need to change the type of `status` from `Int16` to `UInt16` [here](https://github.com/JuliaWeb/HTTP.jl/blob/84a0a2d9030b9a73fdc8a16c511ea21e3f77c36d/src/WebSockets.jl#L24). 

Throughout `WebSockets.jl`, the `status` field is only set to `0` or to a `UInt16`, so there should be no conflict.
