### ISSUE TITLE
How to write data to specific WebSocket connections?

### ISSUE THREAD

**Issue by onetonfoot** [JuliaWeb/HTTP.jl#474]
Using the snippet in the example I can send data to all the connected web sockets

```julia
@async HTTP.WebSockets.listen("127.0.0.1", UInt16(8081)) do ws
     while !eof(ws)
        data = readavailable(ws)
        write(ws, data)
    end
end
```

How would I go about sending data to only specific web sockets?

Julia 1.2 
HTTP.jl 0.8.6

**Comment by itsdfish** [comment]
I had a similar issue a few days ago. You can find my solution on [discourse](https://discourse.julialang.org/t/using-connection-pools-in-a-websocket-server-with-http-jl/31524/2). I would be interested in learning if there is a better solution.

**Comment by touchft** [comment]
Similar problem for me. How do we label a **reliable ID** for the connection of websocket such that this ID will not change as long as the connection is online ? I know `ws::WebSockets` can be a mark for the connection, but I have no idea if it will be changed during the whole life of socket connection.

**Comment by quinnj** [comment]
In the recently merged overhaul of the websockets code, the `WebSocket` object now includes a unique UUID field that can be accessed like `ws.id` to uniquely identify websocket connections. So you could potentially have clients send their own id when connecting to the server, for example as the first thing they send once they're connected.
