### ISSUE TITLE
Error when testing with ab

### ISSUE THREAD

**Issue by JockLawrie** [JuliaWeb/HTTP.jl#48]
Hi there,

I have a simple server that works when making a request from Julia, but fails when making a request from the ab tool. Minimal example below. Any ideas?

```julia
using HTTP

function app(req, res)
    res.body = FIFOBuffer("Hello world!")
    res
end

server = HTTP.Server(app)
HTTP.serve(server, IPv4(127, 0, 0, 1), 8000)
````

This works:
```julia
using HTTP
res = HTTP.get("http://127.0.0.1:8000/")
```

But this fails:
```
ab -n 1 "http://127.0.0.1:8000/"
```

By contrast the following server works in both cases:
```julia
using HttpServer

function app(req, res)
    res.data = "Hello world!"
    res
end

server = Server(app)
run(server, 8000)
```

**Comment by joshbode** [comment]
The error in question:

```
[HTTP - 2017-05-04T13:34:13.434]: starting server to listen on: 127.0.0.1:8000
[HTTP - 2017-05-04T13:34:29.112]: throttling 127.0.0.1
[HTTP - 2017-05-04T13:34:29.117]: new tcp connection accepted, reading request...
[HTTP - 2017-05-04T13:34:29.645]: processing on connection i=0...
[HTTP - 2017-05-04T13:34:38.446]: throttling on connection i=0
[HTTP - 2017-05-04T13:34:38.511]: reading request bytes with readtimeout=180.0
[HTTP - 2017-05-04T13:34:53.843]: received request on connection i=0
HTTP.Request:
"""
GET / HTTP/1.0
Host: 127.0.0.1:8000
Accept: */*
User-Agent: ApacheBench/2.3

"""
[HTTP - 2017-05-04T13:34:54.605]: responding with response on connection i=0
HTTP.Response:
"""
HTTP/1.1 200 OK
Connection: close
Content-Length: 12
Content-Type: text/html; charset=utf-8
Date: Thu, 04 May 2017 03:34:54
Content-Language: en
Server: Julia/0.5.1

Hello, World
"""
ERROR (unhandled task failure): ArgumentError: stream is closed or unusable
 in check_open(::TCPSocket) at ./stream.jl:258
 in uv_write(::TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:806
 in unsafe_write(::TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:830
 in write(::TCPSocket, ::Array{UInt8,1}) at ./io.jl:175
 in write at /Users/josh/.julia/v0.5/HTTP/src/types.jl:445 [inlined] (repeats 2 times)
 in macro expansion at /Users/josh/.julia/v0.5/HTTP/src/server.jl:158 [inlined]
 in (::HTTP.##92#94{HTTP.Server{HTTP.http,Base.TTY},HTTP.Parser,Int64,TCPSocket,HTTP.RateLimit,Base.RefValue{Float64},Bool,#app,Base.TTY,HTTP.ServerOptions,Float64})() at ./task.jl:360
[HTTP - 2017-05-04T13:34:55.748]: finished processing on connection i=0
```

Note: the error goes away if you use the `-k` (Keep Alive) option to `ab`, e.g.

    ab -k -n 1 "http://127.0.0.1:8000/"

which suggests that `ab` is aggressively closing the socket before HTTP.jl is finished writing to it.

**Comment by joshbode** [comment]
Intermittent stream errors when testing with concurrent connections, even with keep-alive enabled.
e.g. 10 requests, with 5 concurrent:
```bash
$ ab -k -n 10 -c 5 "http://127.0.0.1:8000/"
```

**Comment by quinnj** [comment]
Ok, I just pushed a change where we'll write the response back all in one write operation instead of broken up (we were writing the header line, the headers, then the body). Can you pull latest master and run your example again? (`Pkg.checkout("HTTP")`). Is `ab` easy to install? I could also try to get a repro for me on my end if it's not too hard to get setup.

**Comment by JockLawrie** [comment]
I pulled master and reran the test. Same error I'm afraid.

`ab` is ApacheBench, a tool for testing the performance of a server by firing requests at it. It's really easy to use. It is available on all major linux distros. I don't use a Mac but presumably it is available via Homebrew.

**Comment by quinnj** [comment]
Ok, just pushed a kind-of fix. I mean, from what I can tell here, `ab` is not necessarily interested in the responses anyway, so it's just aggressively opening, then immediately closing connections, to test performance. On the server side, I've just made it more robust so that in cases where the client has closed their end of the stream for whatever reason, we don't throw an unhandled error, but close our end gracefully. Let me know if you see any other issues.

**Comment by JockLawrie** [comment]
OK, that handles the closed socket without failing, but then we can't test performance. E.g., `ab -n 1000 "http://127.0.0.1:8000/"` stops executing after just 5 requests. In particular, I can't compare the speed of HTTP.jl to that of HttpServer.jl/Requests.jl.

**Comment by joshbode** [comment]
Change your example to increase the `ratelimit` (requires PR #50) and turn off logging:
```julia
server = HTTP.Server(app; ratelimit=10000//1)
HTTP.serve(server, ip"127.0.0.1", 8000; verbose=false)
```
and it works well (1000 requests, 10 at a time):
```bash
$ ab -n 1000 -c 10 "http://127.0.0.1:8000/"
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:
Server Hostname:        127.0.0.1
Server Port:            8000

Document Path:          /
Document Length:        0 bytes

Concurrency Level:      10
Time taken for tests:   0.464 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      0 bytes
HTML transferred:       0 bytes
Requests per second:    2154.39 [#/sec] (mean)
Time per request:       4.642 [ms] (mean)
Time per request:       0.464 [ms] (mean, across all concurrent requests)
Transfer rate:          0.00 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.2      0       2
Processing:     1    4   2.4      4      23
Waiting:        0    0   0.0      0       0
Total:          2    5   2.4      4      23

Percentage of the requests served within a certain time (ms)
  50%      4
  66%      4
  75%      5
  80%      5
  90%      7
  95%      8
  98%     10
  99%     21
 100%     23 (longest request)
```

**Comment by JockLawrie** [comment]
Nice, thanks. FYI, the HttpServer example in the initial post handles around 3000 requests/s.

**Comment by quinnj** [comment]
Yeah, you'll definitely have to bump the rate limiting if you're doing a mass performance test that's coming from the same IP. Given the net + in functionality over HttpServer, it's good to hear we're not too much slower. Given there hasn't been hardly any performance tuning, there's probably some low hanging fruit.

**Comment by JockLawrie** [comment]
Apologies, my benchmark was disorganised. Starting afresh: After an initial request to compile the code, running `ab -n 1000 "http://127.0.01:8000/"` yields about 3000 req/s for the HttpServer version, and about 4500 req/s for the HTTP version on my machine (dell, i7, debian). A 50% speedup. Nice work!
