### ISSUE TITLE
Can I use HTTP.jl to configure a callback URL to your server?

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaWeb/HTTP.jl#485]
Julia 1.3 

Hey! I am trying to set up a program that pings an API. However, the API uses OAuth 2.0 so I need to set up a "configure a callback URL to your server". Is it possible to do this with HTTP.jl and if so, can you provide a simple example and what my URL would me?

**Comment by quinnj** [comment]
I would check out @randyzwitch's great package: https://github.com/randyzwitch/OAuth.jl

**Comment by logankilpatrick** [comment]
Cool! Thanks.
