### ISSUE TITLE
Help with bearer authorization in headers

### ISSUE THREAD

**Issue by wcostrino** [JuliaWeb/HTTP.jl#492]
Julia 1.2.0
HTTP.jl 0.8.8
MbedTLS.jl 0.X.X -- not installed

I need help on creating a HTTP.get sending the header of a bearer authorization.
The key is a composed text, with no format defined, but composed of hexa digits.

I tryed the solution found in stack-ov, 
https://stackoverflow.com/questions/47717932/julia-http-get-api-key-authorization

but did not worked or I am doing something wrong changing from basic to beare.

Help.

Update:
the format is something like this:
headers = {
           "Accept"=> "application/json",
           "Authorization"=> "Bearer XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
           }

Wilson

**Comment by benelsen** [comment]
Can you describe what you tried in a minimal code example and what did not work, i.e. did you get a `401 Unauthorized` or did it throw some other error? (Remember to redact the token and maybe the url if that one is security-sensitive. If it's a public api maybe specify which one.)
Bearer tokens should be pretty straight forward in general, but might require additional information depending on the service.
```julia
headers = ["Accept" => "application/json", "Authorization" => "Bearer XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"]
HTTP.get("https://example.com/", headers)
```

**Comment by wcostrino** [comment]
Benelsen,

Thanks a lot!
Just changed the data in your example and it worked flawlessly!
I was having difficults in understand the type of data I had to feed to HTTP.get.

Thanks again!
