### ISSUE TITLE
Characters with accents are displayed wrong

### ISSUE THREAD

**Issue by ssagaert** [JuliaWeb/HTTP.jl#493]
Julia 1.2.0 
HTTP.jl 0.8.6
MbedTLS.jl 0.7.0

Characters with accents are displayed wrong in a web page (on Ubuntu 17). e.g. ü is shown as Ã¼. Clearly it's a character encoding issue. Note that it worked correctly on julia 0.6 + HttpServer.

**Comment by benelsen** [comment]
Can you provide an minimal example that reproduces this behaviour? With the information you provided it's difficult to act on this issue and help you.

I assume you use HTTP.jl to serve and display it in a browser.
`ü` encoded in UTF-8 (e.g. a `String` in julia) would be displayed as `Ã¼` if the client assumes a wrong charset (here probably windows-1252 or ISO 8859-1,3,15). [Firefox](https://developer.mozilla.org/en-US/docs/Web/Guide/Localizations_and_character_encodings) for example falls back to a charset depending on the current locale by default if no charset is send by the server. It also provides an error in the console.

Do you provide a charset in the `Content-Type` header of your response, i.e. `Content-Type: text/html; charset=UTF-8` for html?
Alternatively you can add `<meta charset="utf-8">` to the html `<head>`.

**Comment by ssagaert** [comment]
Ok that solved it. You can close it.
