### ISSUE TITLE
Multi-core server

### ISSUE THREAD

**Issue by quinnj** [JuliaWeb/HTTP.jl#5]
Might be tricky, might be an easier way:

* need to wrap/export http://docs.libuv.org/en/v1.x/stream.html#c.uv_write2 in Base julia
* use above send a TCPSocket handle between processes using a pipe stream
* "recreate" the TCPSocket on the slave process using the received handle

**Comment by amitmurthy** [comment]
Socket passing between processes is not trivial. You can use a pair of `RemoteChannels` and long running tasks on workers to process received requests from a single front-end master that only does socket read/write.

**Comment by quinnj** [comment]
Yeah, that could potentially work; I'm only slightly worried about the burden that leaves on the master process. It also sounds like libuv has explicitly designed for the case of passing handles between processes, so I'm encouraged that approach could work.

**Comment by amitmurthy** [comment]
In NGINX,

- A monitor process starts listening on configured ports and forks off workers.
- The workers inherit those "listening" sockets and call `accept` on them.
- The OS picks one of the workers for an incoming connection and it is processed directly in the worker.
- The monitor process checks for worker deaths and does a fork-exec to replace dead workers.

I find this model clean. Given that fork-exec is problematic with a Julia runtime, it will be a little difficult to implement here. Putting it out just in case it inspires an equivalent model.

**Comment by tanmaykm** [comment]
Would `SO_REUSEADDR | SO_REUSEPORT` help here?

**Comment by amitmurthy** [comment]
`SO_REUSEPORT ` may just work. This article https://lwn.net/Articles/542629/ talks about using it across process boundaries. Would be a Linux-only solution for starters though.

**Comment by amitmurthy** [comment]
FWIW https://github.com/JuliaLang/julia/blob/5b6ff4afdcc6c828570be0b8a8d5637081a1b4e4/base/managers.jl#L459-L486 in Base.

**Comment by tanmaykm** [comment]
Also found this: http://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t.

It seems to indicate that it is available on windows and osx as well.

**Comment by tanmaykm** [comment]
Maybe relevant: https://github.com/libuv/libuv/issues/386 and https://github.com/libuv/libuv/pull/400

**Comment by amitmurthy** [comment]
Since Julia has now moved to the newer libuv, https://github.com/JuliaLang/julia/blob/5b6ff4afdcc6c828570be0b8a8d5637081a1b4e4/base/managers.jl#L459-L486  should be updated to bind early and enable support on OSX and Windows too.

**Comment by amitmurthy** [comment]
Issue created - https://github.com/JuliaLang/julia/issues/19893

**Comment by tanmaykm** [comment]
Related: https://github.com/JuliaLang/julia/pull/24115
