### ISSUE TITLE
WebSocket: error: 1002: Client MUST mask all frames (RFC-6455: Section 5.1)

### ISSUE THREAD

**Issue by rana** [JuliaWeb/HTTP.jl#502]
Julia 1.3.1 
HTTP.jl 0.8.8
MbedTLS.jl 0.7.0

Using a WebSocket.
This error gets logged when the connection is closed.
I looked into packet capture session and saw that the WebSocket close frame communication from the Julia side was missing a mask, as the error indicates. Seemingly harmless except for the log message makes me wonder what if anything is wrong.

```julia
┌ Error: HTTP.WebSockets.WebSocketError(1002, "Client MUST mask all frames (RFC-6455: Section 5.1)")
```

**Comment by quinnj** [comment]
Yep, the old code wasn't masking the CLOSE frame that was sent when a connection was closed. This has been fixed on HTTP#master.
