### ISSUE TITLE
Tag a new version?

### ISSUE THREAD

**Issue by hannahilea** [JuliaWeb/HTTP.jl#504]
It looks like there have been some useful changes since the last tagged release; any chance there's a plan to tag a new version soon? Specifically I'm looking to use #476 without being dev'd. :) 

(Also, it has been super easy to get HTTP.jl up and running --- thanks!)

**Comment by quinnj** [comment]
Ok, started a new release here: https://github.com/JuliaWeb/HTTP.jl/commit/d5e2561d17cb7c8408d644caba8817188ff33c31
