### ISSUE TITLE
Playing nicely with Windows Auth?

### ISSUE THREAD

**Issue by amellnik** [JuliaWeb/HTTP.jl#51]
Does anyone know roughly what it would take to enable this?  It looks like there's similar python libraries that support this, looking into them now.

**Comment by quinnj** [comment]
Hmmm....I'm not quite sure what you're talking about w/ this feature request. Any links you can point to? Does it somehow take your Windows username/password and turn it into a basic auth header?

**Comment by amellnik** [comment]
[requests-ntlm](https://github.com/requests/requests-ntlm) is a python package that does this.  I thought that there's also one that uses some windows-specific thing to pull credentials so that you don't even need to supply the Windows username and password, but looking into this more I'm pretty sure I was mistaken.  wget, curl, etc all require the username and password to be passed.    

This is a somewhat niche use case, and I think supporting `HTTP_PROXY` and similar are probably higher priority.  Thanks!

**Comment by samoconnor** [comment]
Hi @amellnik, you mentioned supporting `HTTP_PROXY`, please comment on #218 if this is useful to you. Cheers!

**Comment by samoconnor** [comment]
Is this NTLM feature still useful in the age of OAuth 2 etc?
(I'm afraid that I'm not familiar with Windows).

**Comment by amellnik** [comment]
@samoconnor -- Thanks.  Unfortunately I think not everyone has moved away from NTLM yet.

**Comment by Nosferican** [comment]
Status?
