### ISSUE TITLE
0.8.9 breaks OSX & Windows

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaWeb/HTTP.jl#511]
All my packages relying on HTTP have broken test on OSX & Windows right now:
* https://travis-ci.com/beacon-biosignals/ElectronTests.jl
* https://travis-ci.com/SimonDanisch/JSServe.jl
* https://ci.appveyor.com/project/SimonDanisch/jsserve-jl/build/job/067aw3anrsprcrnt

I can also reproduce it locally on my windows laptop.
On that laptop, fixing the HTTP version to 0.8.8 fixes the tests. That tests started failing yesterday when the new version got released is another indicator ;)

**Comment by quinnj** [comment]
It would be more helpful to narrow down what exactly is breaking. I mean, it's not like we're [ignoring OSX & windows](https://travis-ci.org/JuliaWeb/HTTP.jl/builds/654530883?utm_medium=notification&utm_source=github_status), so there's a lot we know _didn't_ break, and in fact, our testing got a lot more reliable/robust in the latest release. But if there's something we weren't testing before, then we need to narrow down what that was and how it broke. I can look into it, but the links you shared weren't very helpful; they mostly looked like you pinned version to 0.8.8, which isn't helpful.

**Comment by SimonDanisch** [comment]
Sorry for the tone, I'm just in the middle of lots of things and have no time to debug it (yet) ;) So no offence, I just wanted to quickly state what I'm seeing, hoping that you can already see something that I could only figure out with lots of debugging!

I guess, I sent the general links, not the specific logs.
This is a specific log for the failure: https://travis-ci.com/beacon-biosignals/ElectronTests.jl/jobs/290883780

**Comment by quinnj** [comment]
Ok, finally figured out what was going on: https://github.com/JuliaWeb/HTTP.jl/pull/512. To my great relief, it _didnt'_ have anything to do w/ all the concurrency changes! Much simpler case of an unexpected breaking change.

**Comment by SimonDanisch** [comment]
Oh sweet, thanks a lot for the speedy fix! :)
