### ISSUE TITLE
WebSocket: long messages get split up

### ISSUE THREAD

**Issue by fonsp** [JuliaWeb/HTTP.jl#532]
Julia 1.0.5
HTTP.jl 0.8.12
MbedTLS.jl 0.6.8

`readavailable(ws)` as in the [example server in README.md](https://github.com/JuliaWeb/HTTP.jl#websocket-examples) only gives the first ~129 kB of the message, the remainder is only returned in the next `readavailable` call.

I patched this by adding a delimiter string at the end of each message (at the client side), but I feel like this should be fixed in HTTP.jl.

Or perhaps I am not using the correct function to read the entire message?

Thanks in advance!

**Comment by quinnj** [comment]
Hmmm.....this sounds pretty suspect. I can't quite pinpoint what exactly would have been wrong in the old websockets code, other than I know it didn't handle fragmented messages quite right (not sure if the message in your case was fragmented or not).

But in any case, we now pass [this test](https://github.com/crossbario/autobahn-testsuite/blob/55339e767789fd59d0e46fefcd31930c1f1f112f/autobahntestsuite/autobahntestsuite/case/case9_1_6.py), where a single message of 16M is sent and echo'd back successfully, so it seems like we've got this fixed on HTTP#master.
