### ISSUE TITLE
Why is Julia http so slow compared to powershell ?

### ISSUE THREAD

**Issue by redredwine** [JuliaWeb/HTTP.jl#535]
Julia 1.4.1 
HTTP.jl v0.8.14

this is my program
using HTTP
using Dates
println(now())
r = HTTP.request("GET", "http://example.mocklab.io/recordables/123", verbose=1, retries=0) #trying a , instead of a ;
println(now())

why is Julia HTTP Package slow
about 7 seconds using the following julia command
D:\julia-practice>julia web-serv.jl
**2020-05-05T22:35:07.97
GET /recordables/123 HTTP/1.1
HTTP/1.1 200 OK <= (GET /recordables/123 HTTP/1.1)
2020-05-05T22:35:14.66**

when I do it with Powershell it takes less than 1 seconds
PS C:\Users\cassepose2> get-date -Format HH:mm:ss.ffff
  $myrestresponse = Invoke-webRequest http://example.mocklab.io/recordables/123
 get-date -Format HH:mm:ss.ffff

**22:59:58.9215
22:59:59.1622**

**Comment by quinnj** [comment]
In Julia, the first time a function is called, it is compiled. On subsequent invocations, the compiled function is used directly, avoiding the compilation overhead. See [here](https://docs.julialang.org/en/v1.5-dev/manual/performance-tips/#Measure-performance-with-[@time](@ref)-and-pay-attention-to-memory-allocation-1) in the official docs manual for more information. In your case, try doing:
```julia
@time r = HTTP.request("GET", "http://example.mocklab.io/recordables/123", verbose=1, retries=0)
@time r = HTTP.request("GET", "http://example.mocklab.io/recordables/123", verbose=1, retries=0)
```

and see the difference between the first timing result and the second.
