### ISSUE TITLE
Websocket integration

### ISSUE THREAD

**Issue by quinnj** [JuliaWeb/HTTP.jl#54]
It'd be nice to support websocket upgrade requests in an HTTP.Server, as well as have websocket client functionality as well.

cc: @sarvjeethghotra

**Comment by iblis17** [comment]
please checkout [DandelionWebSockets](https://github.com/dandeliondeathray/DandelionWebSockets.jl) and this PR as well:
https://github.com/dandeliondeathray/DandelionWebSockets.jl/pull/5

**Comment by EricForgy** [comment]
I'm by no means an expert, but I'd love to see websockets integration. Any pointers how to get started? Maybe I could try to help.

**Comment by samoconnor** [comment]
I've implemented a simple WebSockets client as a way to get test coverage of `Connection: Upgrade`. Adding server support should be straight forward.

The API is like this...
```julia
HTTP.WebSockets.open("wss://echo.websocket.org") do io
        write(io, "Foo")
        @test !eof(io)
        @test String(readavailable(io)) == "Foo"

        write(io, Vector{UInt8}("Hello"))
        write(io, " There")
        write(io, " World", "!")
        closewrite(io)

        buf = IOBuffer()
        write(buf, io)
        @test String(take!(buf)) == "Hello There World!"

        close(io)
    end
```

https://github.com/samoconnor/HTTP.jl/blob/simplify_parser_branch/test/WebSockets.jl

**Comment by samoconnor** [comment]
This now supports client and server WebSockets: https://github.com/JuliaWeb/HTTP.jl/blob/master/src/WebSockets.jl

@EricForgy is also working on integreating HTTP.jl with the other WebSockets.jl package: https://github.com/JuliaWeb/WebSockets.jl/commits/change_dependencies

**Comment by samoconnor** [comment]
Websockets client and server is now implemented here and over at WebSockets.jl.
Please open a new issue if you encounter a problem.
