### ISSUE TITLE
HTTP.request ignores /etc/hosts file

### ISSUE THREAD

**Issue by Seelengrab** [JuliaWeb/HTTP.jl#545]
Julia  1.5.0-DEV.876
HTTP.jl 0.8.15

When requesting a URL that's only set via /etc/hosts and doesn't resolve via the default DNS server, I get a DNSError. The exact same URL works fine with `Base.download` and standard `curl` from the shell.

This is reproducible by setting an entry for a non-existing domain pointing to e.g. one of the servers of `dig google.com` in /etc/hosts, checking that something gets returned with `curl` (probably 404s), checking with `Base.download` that it also 404s and then trying the same with `HTTP.get(...)`, resulting in a DNSError.

**Comment by staticfloat** [comment]
I cannot reproduce.

What OS are you using?

**Comment by Seelengrab** [comment]
I'm on Windows 10, running through WSL. Julia thinks it's a regular linux and /etc/hosts exists with the correct entry. 

I've done some more digging and found the following:

```
HTTP.get("http://<entry from hosts")
```

works, but 

```
HTTP.get("<entry from hosts>")
```

doesn't and fails with the DNS error.

I'm not sure what the correct approach here should be, but since the domain does actually resolve, I don't think it should end in a DNS error simply because the scheme is missing. Passing the string without a scheme to `URL` currently produces an object with empty `host`, which is probably what triggers the DNS error in the end.

`URL` currently seems to assume a well-formed URL as given string, but I'm not sure the same should be expected for `HTTP.get` and similar - they're much more user facing and feel more like a user agent and thus could have more leeway with what they receive. I'd be fine with assuming `http` as scheme if no scheme is given (after all, this _is_ HTTP.jl) or simply documenting that the string given to `HTTP.get` and the like has to be a valid absolute URL.

**Comment by staticfloat** [comment]
For the record, this has nothing to do with a hosts file: `HTTP.get()` parses the given string as a `URI`, and a `URI` does not parse properly without a scheme:

```
julia> u = HTTP.URI("google.com")
HTTP.URI("google.com")

julia> u.scheme
""

julia> u.host
""

julia> u.path
"google.com"
```

So as you can see, the DNS error comes from the fact that without a scheme, the parsing goes awry.  There used to be [an error that gets thrown](https://github.com/JuliaWeb/HTTP.jl/blob/f3a08d7fab731b907fc5ed5dfe0072eef5a2538f/src/URIs.jl#L112) if the scheme was missing, but it's not getting triggered, perhaps something needs to be updated.

**Comment by Seelengrab** [comment]
Yes, that deduction with /etc/hosts/ was probably too hasty on my part - I didn't think to check with a scheme, since it worked fine without a scheme with curl.

That said, I think the parsing here is actually correct - it gets parsed as a relative (to "") URL  instead of an absolute one. It's just that to me this doesn't make sense to do if the string to be parsed originated from `HTTP.request` and the like - they always expect absolute URIs, don't they?
