### ISSUE TITLE
Meaning and Handling of `connection reset by peer` Error

### ISSUE THREAD

**Issue by ueliwechsler** [JuliaWeb/HTTP.jl#547]
I am using [https://github.com/wookay/Bukdu.jl](`Bukdu.jl`) for creating a REST web server.  

The application is running without problems but from time to time I get a`Base.IOError("read: connection reset by peer (ECONNRESET)", -4077)`  error message which was generated at https://github.com/JuliaWeb/HTTP.jl/blob/b9b42c3e4c75fe27f5126dbc61ae5c93aee9f56a/src/Servers.jl#L264 (see full error log below).

I have posted already an issue [https://github.com/wookay/Bukdu.jl/issues/105](url) in the `Bukdu` repo and also read this post on discourse  [https://discourse.julialang.org/t/econnreset-error-with-http-jl/11228](url) but I didn't understand the scope of the problem entirely  since my understanding of web protocol is basic at best.

Even though the application runs, I do feel uneasy to use it in production just like this. Do you have any more resources on why this error happens (apart from the source code 😅). Do I need to refactor the webserver or is it safe to use with this message occurring?

The versions are:
```julia
Julia 1.4.2
HTTP v0.8.15
MbedTLS v1.0.2
```
and the full error message is
```julia
(Base.IOError("read: connection reset by peer (ECONNRESET)", -4077), 
Base.StackTraces.StackFrame[wait_readnb(::Sockets.TCPSocket, ::Int64) at stream.jl:350, eof at stream.jl:48 [inlined], 
read_to_buffer(::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, ::Int64) at ConnectionPool.jl:253, 
readuntil(::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, ::Function, ::Int64) at ConnectionPool.jl:273, readuntil at ConnectionPool.jl:271
 [inlined], readheaders(::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, ::HTTP.Messages.Request) at Messages.jl:471, 
startread(::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at Streams.jl:155, 
handle_transaction(::typeof(Bukdu.handle_stream_with_remote_ip), ::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, ::HTTP.Servers.Server{Nothing,Sockets.TCPServer}; final_transaction::Bool) at Servers.jl:343, 
(::HTTP.Servers.var"#handle_transaction##kw")(::NamedTuple{(:final_transaction,),Tuple{Bool}}, ::typeof(HTTP.Servers.handle_transaction), ::Function, ::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, ::HTTP.Servers.Server{Nothing,Sockets.TCPServer}) at Servers.jl:338, handle_connection(::Function, ::HTTP.ConnectionPool.Connection{Sockets.TCPSocket}, ::HTTP.Servers.Server{Nothing,Sockets.TCPServer}, ::Int64, ::Int64) at Servers.jl:299, 
(::HTTP.Servers.var"#8#9"typeof(Bukdu.handle_stream_with_remote_ip),HTTP.Servers.Server{Nothing,Sockets.TCPServer},Base.RefValue{Int64},Int64,Int64,Bool,HTTP.ConnectionPool.Connection{Sockets.TCPSocket}})() at task.jl:358])
└ @ HTTP.Servers D:\Libraries\Julia\v1.x\packages\HTTP\BOJmV\src\Servers.jl:264
```

**Comment by gseastream** [comment]
I am also getting this happening. I'm running an internal package server using PkgServer.jl behind a corporate proxy, and almost every time a user makes a request to my container I get this connection reset error. I see in the following line:

https://github.com/JuliaWeb/HTTP.jl/blob/34fccfaa49f035cce1869bafbbbac067a89dc4e5/src/Servers.jl#L261

It is attempting to capture this event and throw a warning instead, but my error code is -104, not -54, and the original issue above has a code of -4077. I guess this error can come with many different codes.

Are these codes really all the same error? And are they not actually errors, simply warnings of a benign connection reset? It'd be nice to resolve this, but I'm also curious if anyone knows why this happens. And maybe in the code above you can check for the existence of `ECONNRESET` or something.

<details>
<summary>Click to see full error message</summary>

```
┌ Error: (Base.IOError("read: connection reset by peer (ECONNRESET)", -104), Base.StackTraces.StackFrame[
wait_readnb(::TCPSocket, ::Int64) at stream.jl:350,
eof at stream.jl:48 [inlined],
read_to_buffer(::HTTP.ConnectionPool.Transaction{TCPSocket}, ::Int64) at ConnectionPool.jl:251,
readuntil(::HTTP.ConnectionPool.Transaction{TCPSocket}, ::Function, ::Int64) at ConnectionPool.jl:271,
readuntil at ConnectionPool.jl:269 [inlined],
readheaders at Messages.jl:471 [inlined],
startread(::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{TCPSocket}}) at Streams.jl:155,
handle_transaction(::PkgServer.var"#72#75", ::HTTP.ConnectionPool.Transaction{TCPSocket}, ::HTTP.Servers.Server{Nothing,Sockets.TCPServer}; final_transaction::Bool) at Servers.jl:343,
(::HTTP.Servers.var"#handle_transaction##kw")(::NamedTuple{(:final_transaction,),Tuple{Bool}}, ::typeof(HTTP.Servers.handle_transaction), ::Function, ::HTTP.ConnectionPool.Transaction{TCPSocket}, ::HTTP.Servers.Server{Nothing,Sockets.TCPServer}) at Servers.jl:338,
handle_connection(::Function, ::HTTP.ConnectionPool.Connection{TCPSocket}, ::HTTP.Servers.Server{Nothing,Sockets.TCPServer}, ::Int64, ::Int64) at Servers.jl:299,
(::HTTP.Servers.var"#8#9"{PkgServer.var"#72#75",HTTP.Servers.Server{Nothing,Sockets.TCPServer},Base.RefValue{Int64},Int64,Int64,Bool,HTTP.ConnectionPool.Connection{TCPSocket}})() at task.jl:356])
└ @ HTTP.Servers ~/depot/packages/HTTP/IAI92/src/Servers.jl:264
```
</details>

**Comment by fredrikekre** [comment]
#764
