### ISSUE TITLE
URI

### ISSUE THREAD

**Issue by musm** [JuliaWeb/HTTP.jl#55]
Is there any reason not to use  `URIParser`  for the representation of  URI's instead of AbstractString?

**Comment by quinnj** [comment]
I don't quite follow your question; URI's are represented using the `HTTP.URI` type defined in the `uri.jl` source file.

In terms of the URIParser.jl package, there were several reasons for rewriting a new representation in this package:

* Performance: `HTTP.URI` parsing in this package is 3x-4x faster than URIParser.jl (see https://github.com/JuliaWeb/HTTP.jl/pull/9)
* Memory usage: URIParser.jl inefficiently represents a URI as like 20 different component strings, `HTTP.URI` is a tidy 36 bytes total, and once we get stack-allocation for reference types in immutables, it will be even more efficient
* Code modernization: Most of the URIParser.jl code was written in 2013, which is ancient in Julia terms; the code in this package is up-to-date with latest 0.5/0.6 Julia features & functionality

The long-term plan is to actually replace the code in URIParser.jl w/ what is here, but I haven't gotten around to doing that yet.

**Comment by musm** [comment]
Thanks for the clarification. It's a bit confusing that this package has the URIParser, and also deals with requests and the server. Perhaps they should be submodules  within `HTTP` ?
