### ISSUE TITLE
Detect http connection close on server side

### ISSUE THREAD

**Issue by malagbek** [JuliaWeb/HTTP.jl#551]
Julia 1.0.5
HTTP.jl 0.8.15

Dear all,

I am creating load balancer using HTTP.jl and Distributed. Requests are accepted by HTTP.jl based server process and distributed to workers for processing. Worker tasks are normally long running and occupy cpu time. In case if http connection is closed by external client i would like to abort processing corresponding task and free computational resources. 
Now to my question: Is there any callback or event which can be used on server side to detect connection close? Some basic implementation example would be very appreciated. 

Best regards,
Ruslan

**Comment by clarkevans** [comment]
Ruslan, I don't think this is best practice to rely upon TCP connection life for a backend process. It's better if you handled this at the application layer, make a resource that represents the asynchronous request.  Use POST to create the async request, then GET can be used to check its status. This GET request can have http refresh logic with a delay on it for those using the API directly.  Then, once the results are generated, the location could return a 301 Moved Permanently with the location of the computed output.  You could the let DELETE be used to kill the process, or you could have a timer that says if "GET" isn't used for N seconds (ie, that the client is still checking status), you could kill the corresponding content generator.  I hope this helps.

**Comment by quinnj** [comment]
Though I usually recommend against having high latency request -> response transactions (I think it's much better to define an asynchronous API with a /startprocessing + /poll_for_finish or an ability to /startprocess + pass a callback endpoint to hit when finished), I designed way to do this would be to handle your own `Stream` object. The default stream handler function is simply defined as:
```julia
return function(stream::Stream)
        request::Request = stream.message
        request.body = read(stream)
        closeread(stream)
        request.response::Response = handler(request)
        request.response.request = request
        startwrite(stream)
        write(stream, request.response.body)
        return
    end
```
so it's fairly straightforward to include that yourself in your server code and then you have full control over the reading/writing and checking `isopen(stream)` as needed for the lifetime of the request.
