### ISSUE TITLE
Intermittent `HTTP.Parsers.ParseError(:INVALID_STATUS_LINE, ...)`

### ISSUE THREAD

**Issue by staticfloat** [JuliaWeb/HTTP.jl#559]
```
Julia 1.4.2 
HTTP.jl v0.8.16
MbedTLS.jl v1.0.2
```

Occasionally, in the `PkgServer.jl` tests, we get an error such as the following:

```
HTTP.Parsers.ParseError(:INVALID_STATUS_LINE, "\x1f\x8b\b\0\0\0\0\0\x02\x03\xec\xbd{{\x1a\u05f58ܿ\xfd)\xa6\xe9\xfb\x14)\a\xa1\x8be%\xb1\x93<F\b\xc94\x02\xe9\x05\x14\xdb=\xe7<0\xc0 M\r3tf\xb0D\xda\xe6\xb3\xff\xd6m߆\x01Ɏ\x85\xdd\xd3\xd0Ԃ\xb9\xec\xcb\xdak\xaf\xdb^\x97A\x18\xfd\xe1\xb1?{{{\xdf<{\xe6\xe1_\xf8\xe4\xff\xf2\x0f\xf7\xfb7Gώ\xfe\xe0=\xfb\xc3\x06>\xf34\xf3\x13\x18\xca'\x98\xa43\xb9\x7f\x93O\x18\r'\xf3Q\xb0;N\x82 [̂\x03\xfdmw\x18G\xe3\xf0zw\x9c\xf1\x97\xca\xcdo\0\xcd\xd1\xe1\xe1\xaa\xf5?<::x\xea\xae\xff\xfe7Ͼ\xd9\xfb\x83\xb7\xf7\xfb\xfa?\xfag\xf7k\xcf,p\xc5\xf3\u382(H\xfc,\x18y\xe3\$\x9e\x9a{a\xe4\r\x16\x1e\xff\x98'\x01<\xf9\xf5\xee\x93ݯ?\xe1片\xff\xd9=\xca\x15ϻj5\xde줳`\x18\x8eá\x1e\x84\x9f\x85q\xe4\x8d\xc3I\xe0m\xa9\x9b|-\x8e&\x8b튼^\x8bg\x8b\$\xbc\xbeɼ\xadڶ\xb7\xff\xddwG;\a{\xfb\xdf\xc1t\xf0\xee\x89\xff>\x1cy\xddy\x02\xd3.{\xedx\x10\$\x99\xf7:\x9c\xdc\x04\x93i\xd9\xf3\xa3\x91\xf7:\xc0{\xdey0\x85{ת\xd5\xeeM\x98r\xdf\xf0w\xe6\xc3K\xf1\xd8\xcbn\x02\xef\x14\xb6O\x17\xb6\x8f7K\xe2\xbf\x05Ì\e\x99\xfa\v\x1a\x957\b\xbcy\x1a\x8c\xca\xd8\xc64\x1e\xc1\x98\xe1\a=2")
```

Here is [an example](https://travis-ci.org/github/JuliaPackaging/PkgServer.jl/jobs/711273427#L1648).  Note that the data is not exactly the same as in the chunk that I pasted above, because I have run this job multiple times (I'm not re-running the job I linked so that it stays) but that seems to indicate some kind of serving of uninitialized data or something.

Since this is happening during a request that is also being served by a server also running `HTTP.jl`, I'm not entirely sure where the error lies.  It seems to happen roughly 1/10th of the time, so it's probably not hard to trigger, if you have debugging ideas.

**Comment by quinnj** [comment]
Ok, looked into this a bit tonight; from what I can tell, the client-side code looks pretty solid. If you wanted to verify client side, you could replace IOExtra.readuntil w/:
```julia
function Base.readuntil(buf::IOBuffer,
                    find_delimiter::Function #= Vector{UInt8} -> Int =#
                   )::ByteView

    l = find_delimiter(view(buf.data, buf.ptr:buf.size))
    @show buf.size, l
    if l == 0
        return nobytes
    end
    bytes = view(buf.data, buf.ptr:buf.ptr + l - 1)
    buf.ptr += l
    return bytes
end
```
that way we could see exactly how many bytes we're looking at for finding the end of header.

It could potentially be a server-side issue, but it's not exactly clear how we might end up w/ junk being written for a response. Unless we have some data-race/connection-pool issue where the buffer is getting messed up when writing. Do you know if the issue tends to happen w/ lots of concurrent requests? Or is it a pretty isolated request? That would help in knowing whether it might be a race condition of some kind.

@Keno has also mentioned capturing an `rr` trace in these cases, which could indeed be helpful to see what exactly is happening w/ the data buffers here. He might have to teach me how to read an `rr` trace though 😉

**Comment by staticfloat** [comment]
It's happening right here: https://github.com/JuliaPackaging/PkgServer.jl/blob/master/test/tests.jl#L198

Your questions made me think about this in a different way, thanks for that!  It turns out that this is because we do a `HEAD` request, and then a `GET` request right afterward, but we weren't doing any special handling for methods; so if you sent in a `HEAD` request, we would serve the entire file in the response body.

I've fixed that, and I don't get this error anymore.  Yay!  But it makes me a little nervous that what is written in the body of the response to the `HEAD` request is leaking out into the response for the follow-up `GET` request.

Here's a MWE for that issue:
```julia
using HTTP

# Start server task:
t_server = @async begin
    HTTP.listen("0.0.0.0", 8001) do http
        try
            N = 1024
            HTTP.setheader(http, "Content-Length" => string(N))
            HTTP.setheader(http, "Content-Type" => "application/x-binary")
            startwrite(http)
            write(http, ones(UInt8, N))
        catch e
            @error("server error", exception=e)
        end
    end
end

# Trigger rapid HEAD->GET requests:
for idx in 1:100
    println(idx)
    try
        HTTP.head("http://localhost:8001/")
    catch e
        @error("client HEAD error", exception=e)
    end
    try
        HTTP.get("http://localhost:8001/")
    catch e
        @error("client GET error", exception=e)
    end
end

# Show any issues on the server side
wait(t_server)
```

This very reliably triggers the issue, and it is easy to see that the `ones()` I'm generating in the response to the `HEAD` are instead being sent to the `GET` request.

**Comment by quinnj** [comment]
Ok, researching a bit more what we can/should do in HTTP.jl here; I think I've come to the conclusion that we don't need to make changes client-side, but on server-side, prevent any body being written w/ HEAD requests. The relevant http spec docs say:
```
"The presence of a message body in a response depends on both the
 request method to which it is responding and the response status code.
 Responses to the HEAD request method never include a message body [].
 2xx (Successful) responses to a CONNECT request method (Section 4.3.6 of
 [RFC7231]) switch to tunnel mode instead of having a message body.
 All 1xx (Informational), 204 (No Content), and 304 (Not Modified)
 responses do not include a message body.  All other responses do
 include a message body, although the body might be of zero length."
[RFC7230 3.3](https://tools.ietf.org/html/rfc7230#section-3.3)
```
so, to me, that means we can assume that on client-side, there won't be any body in responses to HEAD requests. This is important because the spec _does_ allow for pipelining requests, so once we finish parsing a response to a HEAD request, there _may_ be additional bytes in the buffer and we should assume those are starting the response to the next pipelined request.

Hence, another solution to the original issue here would be to pass `reuse_limit=0` in each HTTP request method.

I'll dig a little more into what exactly that means server-side to ensure no bodies are written in response to HEAD requests.

**Comment by quinnj** [comment]
Ok........well, it's going to be a bit tricky to do things on the server side, because at the lowest level, we hand off the stream itself and people can read/write whatever they want before giving control back to the server. I'll close this for now.
