### ISSUE TITLE
Explain how to stop async HTTP.Listen task in README.md

### ISSUE THREAD

**Issue by kubark42** [JuliaWeb/HTTP.jl#563]
I love that there is a good, clear example of how to use Websockets. However, the following example 

```
@async HTTP.WebSockets.listen("127.0.0.1", UInt16(8081)) do ws
           while !eof(ws)
               data = readavailable(ws)
               write(ws, data)
           end
       end
```

spawns a process with `@async` but does not include code for how to stop that process. In general, it is not well documented how to stop a spawned process which does not have a handle. There are perhaps ways to do it, but I couldn't find any in a brief search.

The becomes a problem when the user wants to extend the listener's functionality but runs into failures because the new listener fails to spawn because the old listener is squatting on the port.

**Comment by green-nsk** [comment]
@kubark42 the only way I found to do that is to create a server object yourself (using e.g. `Sockets.listen()`) and pass it to `HTTP.WebSockets.listen()` via a keyword argument `server`.

That's what [listen() documentation](https://juliaweb.github.io/HTTP.jl/stable/public_interface/#HTTP.Servers.listen) says:

> The server= option can be used to pass an already listening socket to HTTP.listen. This allows manual control of server shutdown.

Though, I agree it would be far less confusing if `HTTP.listen()` and `HTTP.WebSockets.listen()` behaved similarly to `Sockets.listen()`.

**Comment by quinnj** [comment]
This is now included in the docs

**Comment by kubark42** [comment]
@quinnj Could we re-open this? The issue is still present that if someone copy/pastas the code from the readme-- which is the most common way for people to explore a new project-- they will still trip up on shutting down the `@async` process (unless something underlying has changed in the meanwhile). 

Maybe the solution is to provide a link in the README code snippet to the documentation on shutting down the async task?

**Comment by quinnj** [comment]
In https://github.com/JuliaWeb/HTTP.jl/pull/854, I'm proposing some updates to server ergonomics and I'll make sure the README/examples are updated with some of the proposed simpler approaches.
