### ISSUE TITLE
Allow setting of cipher suites & ALPN version

### ISSUE THREAD

**Issue by iw-an** [JuliaWeb/HTTP.jl#570]
I think that it would be a great addition to the library if it was possible to pass the cipher suites that we wanted to use and the ALPN type via the SSLContext

I've seen that its possible to set the ALPN version here: https://github.com/JuliaLang/MbedTLS.jl/blob/master/test/runtests.jl#L150

However I'm currently unsure about the technicalities behind setting the allowed cipher suites in MbedTLS 

Thanks

**Comment by quinnj** [comment]
Sorry for the very slow response here; you are able to pass your own `sslconfig::MbedTLS.SSLConfig`, so as far as I understand, you can indeed control the cipher settings/etc on your own that way. I'm going to make a note to include this in the documentation update I do soon.
