### ISSUE TITLE
Example application fails with `UndefVarError: @ip_str not defined`

### ISSUE THREAD

**Issue by clarkevans** [JuliaWeb/HTTP.jl#585]
Julia 1.5.1
HTTP.jl 0.8.19 
MbedTLS.jl 1.0.2

The example application in the documentation fails to load at the very last line.

```
julia> HTTP.serve(ANIMAL_ROUTER, ip"127.0.0.1", 8080)
ERROR: LoadError: UndefVarError: @ip_str not defined
in expression starting at REPL[15]:1
```

**Comment by fredrikekre** [comment]
Needs `using Sockets` (but you probably figured that out).
