### ISSUE TITLE
Convert POST request body to Dict

### ISSUE THREAD

**Issue by jlewis91** [JuliaWeb/HTTP.jl#59]
Thanks for the great library!

Is it possible to convert the body of a Request to a dictionary when responding to a POST request?

 ```julia
using HTTP
function handle_post(req::Request, rep::Response)
    String(take!(req)) # convert to Dict here
    return rep::Response
end

server = HTTP.Server(handle_post)
tsk = @async HTTP.serve(server, ip"0.0.0.0", 5000, verbose=true)

sleep(2)
r = HTTP.post("http://0.0.0.0:5000", body=Dict("amount"=> 1000))
```

**Comment by quinnj** [comment]
It depends: what do you want the actual body to be? JSON? If so, you can load the JSON library `using JSON`, then do `JSON.json(Dict("amount"=>1000))`.

**Comment by jlewis91** [comment]
Hey! Thanks for the quick reply. I'm interested in parsing the dictionary I'm posting on the server-side. As far as I can tell, the only way I can process a request body is using `String(take!(req))` which returns a string. But there's no method to access the form keys I'm posting and get the values. Perhaps this library is intended to only handle lower-level use cases and I'll need to find a different way of fetching these parameters. Appreciate your thoughts.

Something like: http://code.runnable.com/UhLMQLffO1YSAADK/handle-a-post-request-in-flask-for-python

**Comment by jlewis91** [comment]
Just looked into this further...it looks like there is a [`Form`]{https://github.com/JuliaWeb/HTTP.jl/blob/90061e78b96c28c11662bb56867e173df8ea5dd5/src/types.jl#L121
} function that takes a dictionary and converts it to the proper Form format for a http POST, but there's no method `Dict(HTTP.Body(Request()))`  that takes the body of a Request and converts it into a Dict, which would be necessary for consuming a Posted dict server-side.

Does this make sense? What would be involved in creating this function? Happy to take a crack at it.

**Comment by quinnj** [comment]
Ah yes, that's exactly what you're looking for. Yes, there's no "decode" function yet for Forms, but it shouldnt' be too hard. Essentially, you'd want to write a "multipart/form" parser, that takes a string and boundary as input. You'd then split the string by boundaries, then go to parse each boundary section. Definitely feel free to take a crack and let me know if you have any other questions along the way!

**Comment by jlewis91** [comment]
Hey! So I now understand your initial advice about converting the payload dict to a string to that it doesn't get converted to Form data. Looks like a much better way of passing a json object via POST. Just wanted to post my result, in case someone else is looking to do the same. Let me know if this is super-inefficient Julia code, I'm new to the language. Thanks again!

```julia
using HTTP, JSON
function handle_post(req::Request, rep::Response)
    data = JSON.parse(String(take!(req))) # convert to Dict here
    data["amount"] = 9
    return Response(200, Dict("Content-Type" => "application/json"), JSON.json(data))::Response
end

server = HTTP.Server(handle_post)
tsk = @async HTTP.serve(server, ip"0.0.0.0", 5000, verbose=true)

sleep(2)
r = HTTP.post("http://0.0.0.0:5000", body=JSON.json(Dict("amount"=> 1000)))
```

**Comment by quinnj** [comment]
Definitely nothing bad there, JSON is extremely common for this kind of use-case. Multipart forms are better suited when you're dealing w/ exotic content types, but straight data is much easier w/ JSON.
