### ISSUE TITLE
12 "Transfer-Encoding: chunked" Tests Fail Due to httpbin issue

### ISSUE THREAD

**Issue by jlewis91** [JuliaWeb/HTTP.jl#60]
It looks like there is an [unresolved httpbin issue / feature regression](https://github.com/kennethreitz/httpbin/issues/340) with chunked POST requests which is causing 10 of the 12 current test failures. Can anyone confirm this?

**Comment by quinnj** [comment]
Yes, this is an upstream error. I can run the same tests against a local julia server & it runs fine.

**Comment by samoconnor** [comment]
https://github.com/kennethreitz/httpbin/issues/340#issuecomment-330176449

**Comment by samoconnor** [comment]
Can we just remove these tests? They're not providing us with any value as they are.
The httpbin guys seem to be unsure which part of their hosting stack is causing the problem and don't seem to have control over all parts of the stack. We have other test coverage for chunked encoding.

**Comment by quinnj** [comment]
I'm fine w/ that.
