### ISSUE TITLE
Splitting out URI parsing into URIs.jl

### ISSUE THREAD

**Issue by c42f** [JuliaWeb/HTTP.jl#605]
Hi all,

As mentioned in https://github.com/JuliaWeb/URIParser.jl/issues/71, I've extracted the code related to URI parsing into its own library so that it can be used independently from HTTP.jl

This has resulted in https://github.com/JuliaWeb/URIs.jl, where I've tried to keep all git history relevant to the parser. Also I've copied the attribution and license etc from HTTP.jl.

URIs.jl seems to work, but I thought I'd open this issue to make people aware of the split and to discuss further action we should take as it relates to HTTP.jl. Presumably HTTP should be made to depend on URIs to prevent the codebases from diverging.

Thoughts?

**Comment by quinnj** [comment]
Yes, let's get URIs.jl package registered, and then we can remove the code from HTTP.jl and add the URIs.jl dependency. I'm looking at doing a 0.9 release in the next week or so and we can include these changes as a part of it.
