### ISSUE TITLE
Migrating from Requests.jl to HTTP.jl, experience and suggestions...

### ISSUE THREAD

**Issue by samoconnor** [JuliaWeb/HTTP.jl#63]
Hi @quinnj,

I read (your announcement in Feb)[https://discourse.julialang.org/t/ann-new-http-jl-package/2048] with interest. My AWSCore.jl package relies on Requests.jl and I found the experience of getting it to work reliably was less than ideal, so the idea of a cleaner HTTP implementation appeals to me. 

I've just finished an experimental port to HTTP.jl. On the whole, it looks like a big improvement. The new HTTP API pretty much just does what I want with no fuss. Compare my [new much simpler http.jl](https://github.com/samoconnor/AWSCore.jl/blob/http_jl_branch/src/http.jl)   to my [old http.jl](https://github.com/samoconnor/AWSCore.jl/blob/master/src/http.jl).

Note that the [AWSCore.jl/src/http.jl layer](https://github.com/samoconnor/AWSCore.jl/blob/http_jl_branch/src/http.jl) does not disappear completely, it still adds the following features to HTTP.jl:

 - `HTTPException` type for non `20x` result status.
 - Retry with exponential back-off  for status `< 200` or `>= 500` and `UVError`.

Would you consider a PR to introduce a `HTTPException` type to HTTP.jl?

Would you consider a PR to add exponential back-off using [Retry.jl](https://github.com/samoconnor/Retry.jl) ?

My other suggestion is to consider separating some of HTTP.jl's functionality into layers (seperate files and distinct APIs). HTTP.jl currently implements both stateless low-level HTTP wire-protocol stuff and high-level stateful stuff (e.g. Cookies, Authentication, Retries, Redirect processing). It's great to have all this functionality, but it would be cleaner to factor it out a little.

I suggest something like this:

Low level request/response layer:
 - Just send a request and read the response.
 - No default headers, just encode and send headers and body passed by the caller. 

Middle retry layer:
 - Retry with exponential back-off  for status `< 200` or `>= 500` and low level IO Exceptions.
 - Throw an exception for non `20x` status.

High level stateful layer:
 - Useful default headers (User-Agent, Accept etc)
 - Authentication
 - Redirect handling (e.g. handle issues like authentication signatures changing on redirect).
 - Transfer-Encoding?
 - Cookies

A library like AWSCore.jl would use the middle layer directly (rather than using the high-level API with a bunch of options to disable default behaviour as it does now).

**Comment by quinnj** [comment]
FWIW, I'm sketching out some changes to implement from your suggestions along with improvements I want to do from #56. I should have something to PR in the next week.

**Comment by samoconnor** [comment]
Any chance of addressing #49, #61, #62 before beginning a larger refactoring?

**Comment by samoconnor** [comment]
FYI, `AWSCore.jl/master` is [now using `HTTP.jl`](https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/http.jl).

However, I haven't tagged yet pending the latest fixes in `HTTP.jl` being tagged, and:
- [ ] https://github.com/JuliaWeb/HTTP.jl/issues/58#issuecomment-323573444
- [ ] #73 
- [ ] #69
- [ ] https://github.com/JuliaWeb/HTTP.jl/issues/40#issuecomment-315281051

**Comment by quinnj** [comment]
Ok, I think we've addressed a good number of the original things you've brought up. Most of the "extra" features can either be turned off at the `HTTP.Client` level w/ `HTTP.RequestOptions`, or using the slightly lower level `HTTP.request(client, request)` method for making requests. 

In terms of the auto-retries for status < 200 || status >= 500: what about once we hit the retry limit? Just return the 500? Throw a FailedStatusException?

**Comment by samoconnor** [comment]
The retires should be completely transparent. i.e. Whatever exception type cause failure on the last attempt should be thrown.
If there are poorly defined errors from low level libraries (e.g. LibUvException) these should be wrapped with something more meaningful.
For HTTP status exceptions I think there should be a HTTPException with an accessor to get the status code: https://github.com/samoconnor/AWSCore.jl/blob/master/src/http.jl#L19

**Comment by quinnj** [comment]
Ok, so we would need an `HTTPStatusException` then, since we currently don't throw for 200 reponses.

**Comment by quinnj** [comment]
Ok, I've implemented an `HTTP.StatusError` (e59c7c0e9e791361e973744aebadf16944ba0d33) type that gets raised when a non-2XX response code is received in a request. I also added a `statusraise::Bool` RequestOption which allows the user to get back the old behavior if desired (i.e. they can do `HTTP.get(url; statusraise=false)` in order to get back a 404 if they want).

Having played around with it a bit, I like it; it's also nice that it dovetails nicely w/ the retry code (and respects the # of retries that have been given).

Looking over this issue, I think that pretty much covers everything you've suggested/discussed. Feel free to open new issues for other specific concerns/suggestions.

**Comment by samoconnor** [comment]
OK,
I'll have to rework places where I use `HTTPException` like this:
- https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/http.jl#L46
- https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/http.jl#L62
- https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/AWSCore.jl#L439
- https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/AWSException.jl#L22

**Comment by quinnj** [comment]
Indeed, hopefully it simplifies your side of things. Let me know if you think we should tweak any of the behavior HTTP.jl-side.

**Comment by samoconnor** [comment]
Thanks for all your work on this @quinnj !

**Comment by samoconnor** [comment]
AWSCore.jl is now based on HTTP.jl:  https://github.com/JuliaLang/METADATA.jl/pull/11826
Note, AWSS3 tests rely on this fix: https://github.com/JuliaWeb/HTTP.jl/pull/107
