### ISSUE TITLE
close(websocket) yields IOError

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaWeb/HTTP.jl#649]
```
Julia 1.6
HTTP.jl 0.9.1
```

This has been bugging me for a while, but since it didn't happen very often I never had the chance to debug it.
The problem is, that `txclosed`: https://github.com/JuliaWeb/HTTP.jl/blob/master/src/WebSockets.jl#L234, isn't always true when the browser side already killed the connection.
So we still try to write to the factually closed websocket, which then throws and never "officially" closes the websocket (`isopen(ws)` stays true forever).
The workaround is clear:
```julia
    try
        close(ws)
    catch e
        if !(e isa Base.IOError)
            @warn "error while closing websocket!" exception=e
        end
    finally
        ws.rxclosed = true
    end
```
I'm not sure at what level we actually want to fix this in HTTP though, so can't PR this right now :(

**Comment by omus** [comment]
Issue is the same as #722 which was fixed in #723 and included in the v0.9.11 release
