### ISSUE TITLE
automatically gzip compress content

### ISSUE THREAD

**Issue by clarkevans** [JuliaWeb/HTTP.jl#654]
It'd be useful to automatically, by default, compress content for HTTP.Response ; this ticket is the opposite of https://github.com/JuliaWeb/HTTP.jl/issues/256 and complementary to https://github.com/JuliaWeb/HTTP.jl/issues/653 -- gzipping content could be done as part of the rendering process as the send buffer is filled  (avoiding a literal copy of the user data).  As the content is `printed` to an IO stream, it can be gzipped, and once the buffer is full, a chunked response could be sent for streams that exceed the buffer length. 

One of the challenges here is having a bypass for static content that is already compressed; for example, many resource bundles precompress their output so that you don't have to do it at runtime.

In a WSGI like stack, this is implemented as a `Response` proxy.  Basically, it's a wrapper that, when you print the headers looks to see if `Transfer-Encoding` is already set, if so, it is a no-op.  A `FileResponse` object would notice that the file being served may have a `gzip` extension and start with the gzip chararaters and set the headers appropriately.  The GzipResponse would then use the `body` of the wrapped response, reading or printing it, and gzipping the results.  There are some advantages of being a proxy, but, it's not a necessary requirement for the design it could be built-in as a flag of some sort.

**Comment by fonsp** [comment]
Awesome! And it should check for `gzip` in the `Accept-Encoding` header of the request.

**Comment by fredrikekre** [comment]
#256

**Comment by jvo203** [comment]
Are you sure this issue has been solved fully and can be closed? The HTTP streams do not seem to be gzip-compressed automatically:
```
function streamXEvents(http::HTTP.Streams.Stream)
      # ...
      HTTP.setstatus(http, 200)
      startwrite(http)
      write(http, "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n")
      write(
        http,
        "<link href=\"https://fonts.googleapis.com/css?family=Inconsolata\" rel=\"stylesheet\"/>\n",
     )
      # ...
     write(http, "</body></html>")
    return nothing
end
``` 
The HTTP request does contain `Accept-Encoding | gzip, deflate, br` and yet the response is not being compressed at all, all it contains is
```
HTTP/1.1 200 OK
Transfer-Encoding: chunked
```
with the body size being the original uncompressed. So the streaming HTTP response is not being compressed on the fly.
