### ISSUE TITLE
should the documentation be separate?

### ISSUE THREAD

**Issue by clarkevans** [JuliaWeb/HTTP.jl#655]
This ticket is a stylistic question from reading the code.  The docstrings are large, mixing package documentation inside the implementation.  It's hard for me to follow. One set of refactors would be to rip most of the docstrings out and move to a separate test harness & documentation system (say [NarrativeTest.jl](https://github.com/rbt-lang/NarrativeTest.jl) or [Literate.jl](https://github.com/fredrikekre/Literate.jl)).  This ticket can be closed without comment if the maintainers are happy with the documentation approach.

**Comment by quinnj** [comment]
I'd like to overhaul the documentation for upcoming releases (0.10 and 1.0), but I've always been a fan of a dual approach: a healthy amount of "reference"-style documentation inline in the code, with longer "manual"/guide documentation in the separate docs/ folder to be built. I'll make it a priority to do a big update of docs before the next release.
