### ISSUE TITLE
How to not send the Transfer-Encoding header?

### ISSUE THREAD

**Issue by MasFlam** [JuliaWeb/HTTP.jl#656]
I'm fighting with the library to not send the `Transfer-Encoding` header at all, since its mere existence for some reason seems to make the server I'm making the request to respond with a 500. Is there a way to tell HTTP.jl to **not** have the header in the request at all?

Julia 1.5.3
HTTP.jl 0.9.2
MbedTLS.jl 1.0.3

**Comment by staticfloat** [comment]
Try setting an explicit `Content-Length`.

**Comment by MasFlam** [comment]
Thank you so much, it worked! I noticed somewhere else I'm using the same utility function, and it works without any problem, the difference being that I provide a String body, where the part that broke passed `nothing` as the body argument, so apparently that makes the `Transfer-Encoding` header present in the request. (with the explicit `Content-Length` it isn't there)
