### ISSUE TITLE
Deprecate higher-level functionality, such as router?

### ISSUE THREAD

**Issue by clarkevans** [JuliaWeb/HTTP.jl#658]
As you move towards 1.0, one wishes to have a stable API. There's two ways to do this, make existing APIs cleaner, the second way is to simply remove functionality that could be done better at a higher level.  I would argue that the router functionality is one area that could be extracted without loss.  It could be moved to another package.  One might also point someone to `Mux.jl` instead, which seems to have a more suitable abstraction.   It would be better, in my opinion, to delegate to higher-level libraries that provide more application level services -- leaving HTTP.jl to focus on technical issues... suitable low-level interfaces & performance.

**Comment by c42f** [comment]
:+1: to moving the Router to a higher level package. (Though Mux itself isn't the answer — it's kind of abandoned at this point. From an implementation standpoint Mux's routing is pretty hacky + inefficient and leads to ureadable stack traces.)

**Comment by quinnj** [comment]
There have been a number of discussions around breaking things up, but not a lot of effort from anyone. The best example we have is @c42f splitting URIs.jl out into a separate package. We originally consolidated some 5-6 packages _because_ it was too confusing to users which pieces lived where and where issues should be filed. IMO, given the lack of a lot of dedicated maintenance effort (myself included), I wouldn't recommend splitting pieces out unless they're very stable and someone is willing to step up in a strong way to "own" the piece being split out.

**Comment by fredrikekre** [comment]
It is also already now possible to build a better router functionality outside of HTTP without modifying this package. If everyone starts using that instead then it would make sense to think about removing the router functionality here.

**Comment by c42f** [comment]
Those are all very good points. We're currently in need of a light middleware framework a bit like Mux.jl, but with understandable documentation, richer functionality, and active maintenance. We may have the resources to start working on this kind of thing soon, but we'll have to see. Of course we could extend Mux... but it does so little, and the little that it does is kind of quirky so it might be easier to start afresh.

**Comment by quinnj** [comment]
For the 1.0 release, we have a new handlers/middleware framework/interfaces and we're going to keep the (newly written) Router code in HTTP.jl for now.
