### ISSUE TITLE
Include Accept: */* in headers by default

### ISSUE THREAD

**Issue by mbauman** [JuliaWeb/HTTP.jl#661]
This is the default behavior of `curl`, `libcurl`, and Python's [requests](https://github.com/psf/requests/blob/c2b307dbefe21177af03f9feb37181a89a799fcc/requests/utils.py#L824).  While [RFC7231 ](https://tools.ietf.org/html/rfc7231#section-5.3.2) suggests that sites should treat a missing accept header as `*/*` that's not always true in practice.

**Comment by fredrikekre** [comment]
xref https://discourse.julialang.org/t/help-translating-curl-command-to-http-jl/53790

**Comment by DilumAluthge** [comment]
Can we also add a default Content-Type header? It seems like curl also adds that by default?

**Comment by danielw2904** [comment]
I don't know how common that is but with the Spotify API used in the discourse thread `Content-Type` was also necessary:

```
    "Content-Type" => "application/x-www-form-urlencoded"
```
I've added a comparison of `requests`, `curl` and `HTTP.jl` [here](https://discourse.julialang.org/t/help-translating-curl-command-to-http-jl/53790/22?u=danielw2904)

**Comment by quinnj** [comment]
PR is up: https://github.com/JuliaWeb/HTTP.jl/pull/666 (don't get too spooked by the PR number though 👿 )
