### ISSUE TITLE
Requests sent twice

### ISSUE THREAD

**Issue by NikEyX** [JuliaWeb/HTTP.jl#667]
Julia 1.5.3
HTTP 0.9.1

In very rare circumstances the HTTP lib seems to send the same request TWICE using 
`r = HTTP.request("GET", url; verbose=0, connection_limit=500, pipeline_limit=0, readtimeout=60)`

This happens maybe every 10,000 requests. Note that I am running this on spawned threads and that the double request is coming from the same thread. 

I gonna try to create a reproduceable example but until then would anyone have an idea what the cause of that could be?

**Comment by quinnj** [comment]
There are default retry options: https://github.com/JuliaWeb/HTTP.jl/blob/337a372aace7ea80273f5d859b1bbf9d306c13e7/src/HTTP.jl#L117. If a request fails for some retry-able reason, then the request will automatically be retried. You can prevent this by passing `retry=false` or `retries=0`.

**Comment by NikEyX** [comment]
Ok I will try that and reopen if the problem resurfaces. Thanks Jacob

**Comment by NikEyX** [comment]
Hmm, I seem to be getting a bunch of these now:
```
IOError(Base.IOError("stream is closed or unusable", 0) 
```
Again, somewhat random and not consistent. I suppose that explains why requests get sent twice even though the server already received it once. I checked the response with verbose=3 and it matches what I expect, so I am not sure why it would show "stream is closed".

I also updated to HTTP 0.9.2 because I've seen there were some commits on those lines, but that didn't seem to fix it. 

Unfortunately I cannot directly check for this particular error and then simply work with the response, because if I check for the error using something like
```
try
    r = HTTP.request("GET", url; verbose=3, connection_limit=500, pipeline_limit=0, readtimeout=60 * 60, retry=false, redirect=false)
catch IOErr
    @info r.body
end
```
the `response` will be of course be `Nothing` and so `response.body` won't be accessible. 

So what's the right fix for this? And is there any particular reason that this seems to happen on the server side?

**Comment by NikEyX** [comment]
Ok, so this seems to happen notably when HTTP requests are done in quick succession, i.e.:
```
r = HTTP.request("GET", url; verbose=3, connection_limit=500, pipeline_limit=0, readtimeout=60 * 60, retry=false, redirect=false)
r = HTTP.request("GET", url; verbose=3, connection_limit=500, pipeline_limit=0, readtimeout=60 * 60, retry=false, redirect=false)
r = HTTP.request("GET", url; verbose=3, connection_limit=500, pipeline_limit=0, readtimeout=60 * 60, retry=false, redirect=false)
```

will ALWAYS result in the `IOError(Base.IOError("stream is closed or unusable", 0) during request(...))` error.
However, if I add `sleep(1)` in between it will work without problem. So it seems almost like the HTTP lib is trying to reuse the connection despite the pipeline_limit=0 suggesting that it shouldn't do that?

**Comment by c42f** [comment]
I think `pipeline_limit` isn't respected, due to the race conditions described in https://github.com/JuliaWeb/HTTP.jl/issues/517#issuecomment-881408734

**Comment by fonsp** [comment]
Pipelines have been removed for clients, https://github.com/JuliaWeb/HTTP.jl/pull/783 , which might fix this issue. Could you try this again with:
```
julia> ]
pkg> add HTTP#master 
```

**Comment by quinnj** [comment]
Any remaining issues here should be resolved in HTTP#master
