### ISSUE TITLE
need much better debug logging

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaWeb/HTTP.jl#669]
It's obviously extremely useful for debugging to know the exact request being sent and the exact response received.  The `verbose` option is nice, but if you are are not sitting very close to the `HTTP` calls, it can be difficult to pass this, as typically API's which wrap HTTP won't forward it.

I noticed that there are a bunch of `@debug` in the repo, but I think we badly need this for some of the most common use cases like the one described above.  Setting `JULIA_DEBUG=HTTP` does not give me very much in the current version of the package.

**Comment by quinnj** [comment]
Will be resolved by #826
