### ISSUE TITLE
Documentation about `request` and `response` struct and `getfield` function.

### ISSUE THREAD

**Issue by AtsushiSakai** [JuliaWeb/HTTP.jl#681]
Thank you for great OSS!!.
I found a small enhancement for HTTP.jl documentation.

I think [Current document](https://juliaweb.github.io/HTTP.jl/stable/) does not explain how to get HTTP information from request and response object clearly.

Because the docs of `request` and `response` struct are in internal interfaces section, and the docs does not explain how to get it: [Internal Interfaces · HTTP\.jl](https://juliaweb.github.io/HTTP.jl/stable/internal_interface/#HTTP.Messages.Request)

When I checked the source code, I found `getfield` can be used for it.
https://github.com/JuliaWeb/HTTP.jl/blob/edc5e28e53d33c470930f2284ff2cf0e3f877afe/src/Messages.jl#L227-L230
https://github.com/JuliaWeb/HTTP.jl/blob/edc5e28e53d33c470930f2284ff2cf0e3f877afe/src/Messages.jl#L157-L159

I think it would be better that the docs of request and response are moved to public interface sections and it should explain how to get these data for beginners.

Thanks again.

Julia 1.5.3 
HTTP.jl 0.8.19
MbedTLS.jl 1.0.3

**Comment by quinnj** [comment]
Hmmm, I can't actually remember why we deprecated the accessor methods and suggested `getfield`. I'd welcome a PR _un_-deprecating the accessor methods w/ updates to the docs. Mind making a PR @AtsushiSakai ?

**Comment by AtsushiSakai** [comment]
@quinnj Thank you for your comment. I created a PR #682. PTAL.
