### ISSUE TITLE
Export `statustext` function.

### ISSUE THREAD

**Issue by AtsushiSakai** [JuliaWeb/HTTP.jl#685]
I think `statustext` function would be useful in some client codes.
https://github.com/JuliaWeb/HTTP.jl/blob/ed02d37b373386804707262d68856c0fad329b16/src/status_messages.jl#L1-L6

Is there any plan to export it and update doc related it?

Julia 1.5.2 
HTTP.jl 0.9.5

**Comment by quinnj** [comment]
I kind of like keeping the exports to a minimum; what needs to update in the doc?

**Comment by AtsushiSakai** [comment]
Thank you for your comment. 
> I kind of like keeping the exports to a minimum; 

Yes, I agree that it should be. However, in my case, I always needs to implement the similar codes of the statustext and STATUS_MESSAGE... 

> what needs to update in the doc?
Just adding it’s doc in public interface section  https://juliaweb.github.io/HTTP.jl/dev/public_interface/
And adding a doctest for the function might be good for better documentation, I think.

**Comment by quinnj** [comment]
Yeah, that all sounds good to me; mind making a PR?
