### ISSUE TITLE
Failing request with xml query

### ISSUE THREAD

**Issue by diegozea** [JuliaWeb/HTTP.jl#694]
Julia 1.5.3 
HTTP.jl 0.9.5

Hi! I have the following XML query from [BioMart](https://m.ensembl.org/info/data/biomart/biomart_restful.html). It works fine with `wget`, but it gives me an error with `HTTP.request`. Do you know what the problem is? I guess it is because of the `"` characters. Best regards,

```julia
xml_query = """http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "hsapiens_gene_ensembl" interface = "default" ><Filter name = "ensembl_transcript_id" value = "ENST00000307677"/><Attribute name = "ensembl_gene_id" /><Attribute name = "ensembl_gene_id_version" /><Attribute name = "ensembl_transcript_id" /><Attribute name = "ensembl_transcript_id_version" /><Attribute name = "transcript_appris" /></Dataset></Query>"""

r = HTTP.request("GET", xml_query) # It fails

run(`wget -O result.txt $xml_query`) # It works fine
```

**Comment by quinnj** [comment]
You'll have to share more details; what error are you seeing specifically? something in making the actual request? Or in the response? I always recommend doing something like `verbose=2` or `verbose=3` to see exactly what HTTP.jl is doing in the request. Then you can do the same with `wget` (i.e. turn on verbosity) and compare what differences are.

**Comment by diegozea** [comment]
Thanks! I didn't know about verbose. It looks to me that the difference is in how `wget` is scaping characters in the query:

```julia
using HTTP
	
xml_query = """http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "hsapiens_gene_ensembl" interface = "default" ><Filter name = "ensembl_transcript_id" value = "ENST00000307677"/><Attribute name = "ensembl_gene_id" /><Attribute name = "ensembl_gene_id_version" /><Attribute name = "ensembl_transcript_id" /><Attribute name = "ensembl_transcript_id_version" /><Attribute name = "transcript_appris" /></Dataset></Query>"""
	
@info "HTTP"
	
r = HTTP.request("GET", xml_query, verbose=2)
	
@info "WGET"
	
run(`wget --verbose -O result.txt $xml_query`)
	
@info "WGET BODY"
run(`cat result.txt`)
```

![image](https://user-images.githubusercontent.com/2822757/111609538-b25d2080-87da-11eb-83f0-2777843bf1f3.png)

Using `verbose` `3` I see: 
```
DEBUG: 2021-03-18T11:14:22.108 1231 ➡️  "716984324798105111109971141164710997114116115101114118105991016311311710111412161606312010910832118101114115105111110613449464834321011109911110010511010361348584704556346362603368796784898069328111710111412162608111710111412132321181051141161179710883991041011099778971091013261323410010110297117108116343210211111410997116116101114326132348483863432104101971001011143261323448343211711010511311710182111119115326132344834329911111711011632613234343210097116971151011166711111010210510386101114115105111110326132344846543432626068971169711510111632110971091013261323410411597112105101110115951031011101019510111011510110998108343210511011610111410297991013261323410010110297117108116343262607010510811610111432110971091013261323410111011510110998108951161149711011599114105112116951051003432118971081171013261323469788384484848484851485554555534476260651161161141059811711610132110971091013261323410111011510110998108951031011101019510510034324762606511611611410598117116101321109710910132613234101110115101109981089510310111010195105100951181011141151051111103432476260651161161141059811711610132110971091013261323410111011510110998108951161149711011599114105112116951051003432476260651161161141059811711610132110971091013261323410111011510110998108951161149711011599114105112116951051009511810111411510511111034324762606511611611410598117116101321109710910132613234116114971101159911410511211695971121121141051153432476260476897116971151011166260478111710111412162327284848047494649131072111115116583211911911946101110115101109981084611111410313106599991011121165832424742131085115101114456510310111011658327284848046106108474946534652131067111110116101110116457610111010311610458324813101310" (write)
```

**Comment by diegozea** [comment]
I show the capture response as HTTP is getting a `Query ERROR` response, but the correct file content for `wget`.

**Comment by fredrikekre** [comment]
To compare what the server gets in the two cases you can use `netcat` as in the end of the answer here: https://stackoverflow.com/a/66276751/5087136.

**Comment by benelsen** [comment]
Looks like the URI is just not escaped properly.
This for example works fine, as far as I can tell:

```julia
julia> using HTTP, URIs

julia> uri = URI(URI("http://www.ensembl.org/biomart/martservice"); query = ["query" => """<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "hsapiens_gene_ensembl" interface = "default" ><Filter name = "ensembl_transcript_id" value = "ENST00000307677"/><Attribute name = "ensembl_gene_id" /><Attribute name = "ensembl_gene_id_version" /><Attribute name = "ensembl_transcript_id" /><Attribute name = "ensembl_transcript_id_version" /><Attribute name = "transcript_appris" /></Dataset></Query>"""])
URI("http://www.ensembl.org/biomart/martservice?query=%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%3C%21DOCTYPE%20Query%3E%3CQuery%20%20virtualSchemaName%20%3D%20%22default%22%20formatter%20%3D%20%22TSV%22%20header%20%3D%20%220%22%20uniqueRows%20%3D%20%220%22%20count%20%3D%20%22%22%20datasetConfigVersion%20%3D%20%220.6%22%20%3E%3CDataset%20name%20%3D%20%22hsapiens_gene_ensembl%22%20interface%20%3D%20%22default%22%20%3E%3CFilter%20name%20%3D%20%22ensembl_transcript_id%22%20value%20%3D%20%22ENST00000307677%22%2F%3E%3CAttribute%20name%20%3D%20%22ensembl_gene_id%22%20%2F%3E%3CAttribute%20name%20%3D%20%22ensembl_gene_id_version%22%20%2F%3E%3CAttribute%20name%20%3D%20%22ensembl_transcript_id%22%20%2F%3E%3CAttribute%20name%20%3D%20%22ensembl_transcript_id_version%22%20%2F%3E%3CAttribute%20name%20%3D%20%22transcript_appris%22%20%2F%3E%3C%2FDataset%3E%3C%2FQuery%3E")

julia> HTTP.request("GET", uri)
HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Date: Thu, 18 Mar 2021 12:47:36 GMT
Server: Apache
Transfer-Encoding: chunked
Content-Type: text/plain; charset=utf-8

ENSG00000171552	ENSG00000171552.14	ENST00000307677	ENST00000307677.5	principal1
"""
```

**Comment by diegozea** [comment]
Thank you very much! :) Yes, the difference is in how the query is escaped: 

- top: Using the code in https://github.com/JuliaWeb/HTTP.jl/issues/694#issuecomment-801800280
- bottom: Using the alternative in https://github.com/JuliaWeb/HTTP.jl/issues/694#issuecomment-801899140

![image](https://user-images.githubusercontent.com/2822757/111770752-19e2a100-88ab-11eb-8c0c-d1782dcad1b1.png)

**Comment by quinnj** [comment]
Yeah, so I think probably the core issue is that we have the following:
```julia
julia> xml_query = """http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "hsapiens_gene_ensembl" interface = "default" ><Filter name = "ensembl_transcript_id" value = "ENST00000307677"/><Attribute name = "ensembl_gene_id" /><Attribute name = "ensembl_gene_id_version" /><Attribute name = "ensembl_transcript_id" /><Attribute name = "ensembl_transcript_id_version" /><Attribute name = "transcript_appris" /></Dataset></Query>"""
"http://www.ensembl.org/biomart/martservice?query=<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE Query><Query  virtualSchemaName = \"default\" formatter = \"TSV\" header = \"0\" uniqueRows = \"0\" count = \"\" datasetConfigVersion = \"0.6\" ><Dataset name = \"hsapiens_gene_ensembl\" interface = \"default\" ><Filter name = \"ensembl_transcript_id\" value = \"ENST00000307677\"/><Attribute name = \"ensembl_gene_id\" /><Attribute name = \"ensembl_gene_id_version\" /><Attribute name = \"ensembl_transcript_id\" /><Attribute name = \"ensembl_transcript_id_version\" /><Attribute name = \"transcript_appris\" /></Dataset></Query>"

julia> HTTP.URIs.URI(xml_query)
URI("http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "hsapiens_gene_ensembl" interface = "default" ><Filter name = "ensembl_transcript_id" value = "ENST00000307677"/><Attribute name = "ensembl_gene_id" /><Attribute name = "ensembl_gene_id_version" /><Attribute name = "ensembl_transcript_id" /><Attribute name = "ensembl_transcript_id_version" /><Attribute name = "transcript_appris" /></Dataset></Query>")
```
i.e. when constructing a URI that has a query component, it doesn't get escaped as a part of the uri escaping.

@c42f and @fonsp, what do we think? Should we change that behavior in URIs.jl?

**Comment by clarkevans** [comment]
You should not escape the query since you don't know how you should escape it.  You should instead have an API for constructing URLs that have query components.

**Comment by c42f** [comment]
URIs directly inherited the escaping stuff from HTTP.jl, so I'm not super familiar with it. But my general feeling is that it's fairly buggy/inconsistent and should be fixed.

@pfitzseb mentioned a while back that LanguageServer fixed some of these issues... IIRC.  Looks like the code is here:

https://github.com/julia-vscode/LanguageServer.jl/blob/0700041fe34e0879b4d09c8d58b8408f86b849d6/src/URIs2/URIs2.jl

I agree with the points @clarkevans made too.

**Comment by quinnj** [comment]
Ok, closing this for now then; I'm going to try and do a pass over the URIs.jl code and maybe do a reference check against another language lib (probably golang).

**Comment by c42f** [comment]
Awesome, thanks Jacob. I wish I had time to maintain URIs.jl... all I really managed to do was split it out from HTTP.jl! Definitely :+1: to reading how other languages (Go! python?) handle escaping and splitting URIs.

I did a bunch of reading of RFCs, but it's not always clear now to distill a good design out of those.

**Comment by fonsp** [comment]
FYI JavaScript also *magically* fixes this by escaping the query. In the example below, I'm fairly sure that the first `fetch` internally calls `new URL(url)`:
```js
➜  ~ deno
Deno 1.22.0
exit using ctrl+d or close()
> let xml_query = `http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "hsapiens_gene_ensembl" interface = "default" ><Filter name = "ensembl_transcript_id" value = "ENST00000307677"/><Attribute name = "ensembl_gene_id" /><Attribute name = "ensembl_gene_id_version" /><Attribute name = "ensembl_transcript_id" /><Attribute name = "ensembl_transcript_id_version" /><Attribute name = "transcript_appris" /></Dataset></Query>`
undefined
> await (await fetch(xml_query)).text()
"ENSG00000171552\tENSG00000171552.14\tENST00000307677\tENST00000307677.5\tprincipal1\n"
> let u = new URL(xml_query)
undefined
> u
URL {
  href: "http://www.ensembl.org/biomart/martservice?query=%3C?xml%20version=%221.0%22%20encoding=%22UTF-8%22?...",
  origin: "http://www.ensembl.org",
  protocol: "http:",
  username: "",
  password: "",
  host: "www.ensembl.org",
  hostname: "www.ensembl.org",
  port: "",
  pathname: "/biomart/martservice",
  hash: "",
  search: "?query=%3C?xml%20version=%221.0%22%20encoding=%22UTF-8%22?%3E%3C!DOCTYPE%20Query%3E%3CQuery%20%20vir..."
}
> u.href
"http://www.ensembl.org/biomart/martservice?query=%3C?xml%20version=%221.0%22%20encoding=%22UTF-8%22?%3E%3C!DOCTYPE%20Query%3E%3CQuery%20%20virtualSchemaName%20=%20%22default%22%20formatter%20=%20%22TSV%22%20header%20=%20%220%22%20uniqueRows%20=%20%220%22%20count%20=%20%22%22%20datasetConfigVersion%20=%20%220.6%22%20%3E%3CDataset%20name%20=%20%22hsapiens_gene_ensembl%22%20interface%20=%20%22default%22%20%3E%3CFilter%20name%20=%20%22ensembl_transcript_id%22%20value%20=%20%22ENST00000307677%22/%3E%3CAttribute%20name%20=%20%22ensembl_gene_id%22%20/%3E%3CAttribute%20name%20=%20%22ensembl_gene_id_version%22%20/%3E%3CAttribute%20name%20=%20%22ensembl_transcript_id%22%20/%3E%3CAttribute%20name%20=%20%22ensembl_transcript_id_version%22%20/%3E%3CAttribute%20name%20=%20%22transcript_appris%22%20/%3E%3C/Dataset%3E%3C/Query%3E"
> await (await fetch(u)).text()
"ENSG00000171552\tENSG00000171552.14\tENST00000307677\tENST00000307677.5\tprincipal1\n"
```

cc our new URI RFC expert @kernelmethod 🙌

**Comment by pfitzseb** [comment]
This is what the LS URIs2 does with that URL:
```
julia> uri = LanguageServer.URIs2.URI("""http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "hsapiens_gene_ensembl" interface = "default" ><Filter name = "ensembl_transcript_id" value = "ENST00000307677"/><Attribute name = "ensembl_gene_id" /><Attribute name = "ensembl_gene_id_version" /><Attribute name = "ensembl_transcript_id" /><Attribute name = "ensembl_transcript_id_version" /><Attribute name = "transcript_appris" /></Dataset></Query>""")
LanguageServer.URIs2.URI("http", "www.ensembl.org", "/biomart/martservice", "query=<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE Query><Query  virtualSchemaName = \"default\" formatter = \"TSV\" header = \"0\" uniqueRows = \"0\" count = \"\" datasetConfigVersion = \"0.6\" ><Dataset name = \"hsapiens_gene_ensembl\" interface = \"default\" ><Filter name = \"ensembl_transcript_id\" value = \"ENST00000307677\"/><Attribute name = \"ensembl_gene_id\" /><Attribute name = \"ensembl_gene_id_version\" /><Attribute name = \"ensembl_transcript_id\" /><Attribute name = \"ensembl_transcript_id_version\" /><Attribute name = \"transcript_appris\" /></Dataset></Query>", nothing)

julia> dump(uri)
LanguageServer.URIs2.URI
  scheme: String "http"
  authority: String "www.ensembl.org"
  path: String "/biomart/martservice"
  query: String "query=<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE Query><Query  virtualSchemaName = \"default\" formatter = \"TSV\" header = \"0\" uniqueRows = \"0\" count = \"\" datasetConfigVersion = \"0.6\" ><Dataset name = \"hsapiens_gene_ensembl\" interface = \"default\" ><Filter name = \"ensembl_transcript_id\" value = \"ENST00000307677\"/><Attribute name = \"ensembl_gene_id\" /><Attribute name = \"ensembl_gene_id_version\" /><Attribute name = \"ensembl_transcript_id\" /><Attribute name = \"ensembl_transcript_id_version\" /><Attribute name = \"transcript_appris\" /></Dataset></Query>"
  fragment: Nothing nothing

julia> string(uri)
"http://www.ensembl.org/biomart/martservice?query=%3C?xml%20version=%221.0%22%20encoding=%22UTF-8%22?%3E%3C!DOCTYPE%20Query%3E%3CQuery%20%20virtualSchemaName%20=%20%22default%22%20formatter%20=%20%22TSV%22%20header%20=%20%220%22%20uniqueRows%20=%20%220%22%20count%20=%20%22%22%20datasetConfigVersion%20=%20%220.6%22%2" ⋯ 193 bytes ⋯ "te%20name%20=%20%22ensembl_gene_id%22%20/%3E%3CAttribute%20name%20=%20%22ensembl_gene_id_version%22%20/%3E%3CAttribute%20name%20=%20%22ensembl_transcript_id%22%20/%3E%3CAttribute%20name%20=%20%22ensembl_transcript_id_version%22%20/%3E%3CAttribute%20name%20=%20%22transcript_appris%22%20/%3E%3C/Dataset%3E%3C/Query%3E"
```

That looks correct to me at least. Something like this case may have been the motivation for that re-implementation, but neither David nor I could remember the actual reason when we last talked about it.

**Comment by kernelmethod** [comment]
Re: this point about "magical behavior":

> You should not escape the query since you don't know how you should escape it.
> 
> ... What about `http://server?query=true&x=2` ? Should you escape the second `&` and `=` assuming the person providing the URL didn't already escape properly? Or, does `server` take two arguments and the URL is already properly escaped? You must assume the latter, hence, you shouldn't do the former. I wouldn't try to guess... this gets complex fast.

I believe the "normal" thing to do when parsing + URL-encoding the query component of a URI is to parse it as `application/x-www-form-urlencoded` data, i.e. as key-value pairs separated by `&`; at least, this seems to be what [Python](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.parse_qs) and [Go](https://pkg.go.dev/net/url#ParseQuery) do. In any case, it seems relatively unambiguous how the query component of the URI should be parsed, at least in the sense that there's a lot of precedent outside of Julia we can refer to for how query parsing should work.

---

That said, IIUC there isn't actually a *formal* standardization of how the query string should be structured or interpreted, even if there's a lot of precedent (perhaps this is what you were saying @clarkevans?). And from a cursory glance it seems like the default behavior for whether or not a query should be escaped is completely different across languages, even if they all parse query strings in the same way when you explicitly ask them to:

- Javascript will automatically escape a URL constructed with `new URL(...)`:

```javascript
>> let url = new URL("http://localhost:8000/?q=hello world");

>> console.log(url.search)
?q=hello%20world
```

- Python does not escape the URL automatically when you use `urllib.parse.urlparse`, but the [requests](https://github.com/psf/requests) library (which is the most common library for making HTTP requests and is maintained by PSF) does:

```python
>>> from urllib.parse import urlparse
>>> import requests
>>> url = urlparse("http://localhost:8000/?q=hello world")
>>> print(url.query)
q=hello world
>>> requests.get("http://localhost:8000/?q=hello world")
<Response [200]>
>>> # Local server received `?q=hello%20world`
```

- Go does not escape the query by default if you use either [url.Parse](https://pkg.go.dev/net/url#Parse) or if you make an HTTP request:

```go
package main

import (
        "fmt"
        "net/http"
        "net/url"
        "os"
)

func main() {
        url, err := url.Parse("http://localhost:8000/?q=hello world")
        if err != nil {
                fmt.Fprintf(os.Stderr, "Error parsing url: %s", err)
                return
        }
        fmt.Printf("%s\n", url.RawQuery)

        resp, err := http.Get("http://localhost:8000/?q=hello world")
        if err != nil {
                fmt.Fprintf(os.Stderr, "Error making request: %s", err)
        }
        fmt.Printf("Status: %s\n", resp.Status)
}
```

```
$ go build
$ ./main
q=hello world
Status: 400 Bad request syntax ('GET /?q=hello world HTTP/1.1')
```

Without a formal standard for how query strings are structured, I don't think it makes sense to change the default behavior of URIs.jl itself.

There's an argument to be made though that HTTP.jl should be more opinionated; I believe the structure of query parameters in HTTP URLs is slightly more standardized than it is for URIs in general (although there still isn't a single spec I could point to to demonstrate that). Arguably the more user-friendly option is to escape the query by default in HTTP.jl while keeping an option that leaves the URI untouched (i.e. to follow Python), but Go's approach is more technically correct.

**Comment by c42f** [comment]
> IIUC there isn't actually a _formal_ standardization of how the query string should be structured or interpreted, even if there's a lot of precedent

Exactly, this was my reading of the relevant RFCs regarding URIs last time I looked.

Perhaps this could be a reason to have a type-level distinction between `URL` vs `URI`? Where using `URL` means parsing the query section into key value pairs according to the usual convention, whereas `URI` keeps that part as a string, according to the standard.  In that case I'd still be in favour of putting the `URL` parsing/type into URIs.jl because people do want the parsing machinery in isolation from any HTTP client or server stuff.

**Comment by clarkevans** [comment]
I'm sorry if I was confusing.  It's just that encoding of characters should not be done blindly.

Characters that are not in the reserved or unreserved set should be percent encoded, each character using its UTF-8 representation.

```
reserved      = gen-delims / sub-delims
gen-delims    = ":" / "/" / "?" / "#" / "[" / "]" / "@"
sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"  / "*" / "+" / "," / ";" / "="
unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
```

Escaping  ' '  is not only fine, but required for it to be a valid URI.   

However, what you don't want to do is percent-encode any character from the `reserved` character list, as this would change the meaning of the URI.  Conversely, normalizing  `unreserved` characters (unescaping them) does not change the meaning of the URI, so you could do that as well.

As I recall, before 3986, you had to know the scheme before you knew the escaping rule, e.g. was it a urn, email, url, etc.  With 3986 the escaping rules are normalized.  My apologies if I caused any confusion.

**Comment by clarkevans** [comment]
> Perhaps this could be a reason to have a type-level distinction between `URL` vs `URI`? Where using `URL` means parsing the query section into key value pairs according to the usual convention, whereas `URI` keeps that part as a string, according to the standard.

Just because `<form action="..." method="POST">` would never generate a URL that includes a `+` in the query string doesn't mean that other URL schemes don't use `+`.  The `+` character is a reserved character, and percent-encoding it would change the meaning of the URL provided to the library.

The solution (which is probably already implemented correctly?) is to percent-encode characters that are not in `reserved` or `unreserved` character classes. Unescaping characters in the `unreserved` might also prove useful.  Of course, you have to hope that the one providing the URL has already properly escaped '%', one should probably raise an error if it's not a valid escape sequence, e.g. `?query=3%2` is invalid because `2` is not a 2-character, base 16 representation of an octet.

**Comment by clarkevans** [comment]
This stuff gets complicated fast.  So, the other option is to keep URL stupid, and have a function to build query strings from dictionaries in the same way `<form method="POST" ...>` does?
