### ISSUE TITLE
Origin header breaks AWS EC2 API

### ISSUE THREAD

**Issue by samoconnor** [JuliaWeb/HTTP.jl#71]
See: https://github.com/JuliaWeb/HTTP.jl/commit/90061e78b96c28c11662bb56867e173df8ea5dd5#commitcomment-23615586

**Comment by samoconnor** [comment]
FYI, I'm working around this by creating a `HTTP.Request` object directly (to avoid the constructor that sets default headers): https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/http.jl#L33

**Comment by quinnj** [comment]
We no longer add the `Origin` header; closed via #77
