### ISSUE TITLE
Julia HTTP.jl performance vs python requests

### ISSUE THREAD

**Issue by serhii-havrylov** [JuliaWeb/HTTP.jl#710]
Hi,
after some benchmarking, I’ve noticed that Julia’s HTTP.jl performance is somewhat worse than python’s requests (370ms vs 240ms) for GET requests. This is probably due to the fact that I use “persistent connection” in python via requests.session and just plain HTTP requests for HTTP.jl. So, is there any way to get a similar performance in Julia?

**Comment by fredrikekre** [comment]
Can you include the Julia and Python code you used for the benchmark?

**Comment by serhii-havrylov** [comment]
Hi, I am embarrassed to admit that I can't reproduce it anymore; the time discrepancy is within 3ms between python-requests and HTTP.jl. I don't understand how this could happen but anyhow, thank you for your reply and sorry for bothering you.
