### ISSUE TITLE
Possibly excessive memory allocations in ascii.jl

### ISSUE THREAD

**Issue by StatisticalMice** [JuliaWeb/HTTP.jl#724]
Julia 1.6.1
HTTP.jl 0.9.10
MbedTLS.jl 1.0.3

I did async HTTP GETs, and I found that the memory usage varied widely. When I analyzed where the allocations happen, it pointed to lines 15 and 16 of ascii.jl, which are shown below.

```
     10 
     11 """
     12 Case insensitive ASCII string comparison.
     13 """
     14 function ascii_lc_isequal(a, b)
     15     a = Iterators.Stateful(codeunits(a))
     16     b = Iterators.Stateful(codeunits(b))
     17     for (i, j) in zip(a, b)
     18         if !ascii_lc_isequal(i, j)
     19             return false
     20         end
     21     end
     22     return isempty(a) && isempty(b)
     23 end
```

There's more about that here [Discourse post](https://discourse.julialang.org/t/what-is-the-recommended-way-to-run-n-workers-asynchronously/63128/8?u=statisticalmouse)

**Comment by quinnj** [comment]
Thanks for researching this and posting an issue; I've proposed a fix here: https://github.com/JuliaWeb/HTTP.jl/pull/725
