### ISSUE TITLE
How to use Websockets in binary mode?

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [JuliaWeb/HTTP.jl#726]
Julia 1.6.1 
HTTP.jl 0.9.10

I'm trying to adapt the [chat server documentation example](https://juliaweb.github.io/HTTP.jl/stable/public_interface/#Server-/-Handlers) to websocket. Doing it in text mode works well:

```julia
using HTTP

function chat(io)
    @async while !eof(io)
        write(stdout, "> ", readavailable(io), "\n? ")
    end
    while isopen(io)
        write(io, readline(stdin))
    end
end

server() = HTTP.WebSockets.listen("127.0.0.1", UInt16(8087)) do ws
    write(ws, "Hello")
    chat(ws)
end

client() = HTTP.WebSockets.open("ws://127.0.0.1:8087") do ws
    chat(ws)
end
```

but I'm trying to do it in binary mode using Serialization:

```julia
using HTTP, Serialization

function chat(io)
    @async while !eof(io)
        write(stdout, "> ", deserialize(readavailable(io)), "\n? ")
    end
    while isopen(io)
        buffer = IOBuffer()
        serialize(buffer, readline(stdin))
        seek(buffer, 0)
        write(io, buffer)
    end
end

server() = HTTP.WebSockets.listen("127.0.0.1", UInt16(8087); binary=true) do ws
    buffer = IOBuffer()
    serialize(buffer, "Hello")
    seek(buffer, 0)
    write(ws, buffer)
    chat(ws)
end

client() = HTTP.WebSockets.open("ws://127.0.0.1:8087"; binary=true) do ws
    chat(ws)
end
```

It seems that the client never receive the "Hello" message. How should it be done?

**Comment by fonsp** [comment]
Salut Hugo !! (Quelle chance de te revoir ici !)

The way I do this is by modifying the `ws.frame_type` directly, but I am not sure that this is official API:

```julia
HTTP.WebSockets.listen("127.0.0.1", UInt16(8087); binary=true) do ws
    # ...
	
	ws.frame_type = HTTP.WebSockets.WS_BINARY

	write(ws, my_data::Vector{UInt8})
end
```

**Comment by quinnj** [comment]
Yeah, this was a bit of an oddity of the old websockets code that had an internal `frame_type` field of the websocket itself that determined whether frames would be sent as TEXT or BINARY.

In the newly (and now documented!) merged websockets code, it now just depends on the type of the thing you're sending, so e.g.: `send(ws, msg)` where `msg` is an `AbstractString` will send a TEXT frame, but if `msg` is an `AbstractVector{UInt8}`, then a BINARY frame will be sent. That means no more messing with undocumented internal fields of `WebSocket`, and it's easy to mix and match the two if needed.
