### ISSUE TITLE
Minor type mismatch for HTTP.Response.status

### ISSUE THREAD

**Issue by green-nsk** [JuliaWeb/HTTP.jl#734]
```Julia
r = HTTP.Response(123) # works fine
HTTP.Response(r.status)
# ERROR: BoundsError: attempt to access Int16 at index [2]
```
I think this is happening due to HTTP.Request constructor requiring Int64: https://github.com/JuliaWeb/HTTP.jl/blob/2a03ca76376162ffc3423ba7f15bd6d966edff9b/src/Messages.jl#L116

Julia 1.6.1 
HTTP.jl 0.9.2 
MbedTLS.jl 1.0.3 -- Please specify versions

**Comment by fredrikekre** [comment]
Seems like that could just be relaxed to `Integer`. Do you want to submit a PR?
