### ISSUE TITLE
Cookie type lacks support for `SameSite` attribute

### ISSUE THREAD

**Issue by essenciary** [JuliaWeb/HTTP.jl#735]
Attempting to set the `SameSite` cookie attribute results in a `type Cookie has no field samesite` exception. It looks like the improper setting of the `SameSite` attribute causes a warning (in Genie apps) with a possible future failure to set the cookie in Firefox and Chrome.

![image](https://user-images.githubusercontent.com/11292378/126651090-c2ecac59-a599-4460-b179-430e80a6ba05.png)

(similar to https://github.com/rails/rails/issues/39190). 

Additional info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Should I add it? 

Julia 1.6.2 
HTTP.jl 0.9.10
MbedTLS.jl 1.0.3

**Comment by Rashaine** [comment]
I agree that Cookie needs to be updated to support SameSite. Browsers treat the absence of the SameSite attribute differently and developers need to be able to explitcly specify the value. In addition to supporting SameSite as a named keyword argument, it would also be good to add support for adding arbitrary attributes.

**Comment by fonsp** [comment]
@essenciary perhaps you could start a PR for this?

**Comment by quinnj** [comment]
Support for SameSite is implemented in https://github.com/JuliaWeb/HTTP.jl/pull/836
