### ISSUE TITLE
Add a `gcp_authorization` flag to API methods

### ISSUE THREAD

**Issue by jaketothepast** [JuliaWeb/HTTP.jl#736]
Julia 1.5.0
HTTP.jl 0.9.12
MbedTLS.jl 1.0.3

I work for a company that uses GCP and Julia extensively. There currently is an `aws_authorization` flag, would anyone be open to adding GCP auth if possible? GCP is Oauth2-based authentication so I don't know if it is worth adding, it might be too much magic behind the scenes

**Comment by fredrikekre** [comment]
That functionality is beeing phased out (https://github.com/JuliaWeb/HTTP.jl/pull/486). You can probably use the same method that the AWS package now use for your usecase.

**Comment by jaketothepast** [comment]
Thank you for your reply, I figured that it would be removed in the near future,
