### ISSUE TITLE
HTTP PUT Multi-part request headers issue

### ISSUE THREAD

**Issue by camilovelezr** [JuliaWeb/HTTP.jl#740]
Julia 1.6.1
HTTP.jl 0.9.13
MbedTLS.jl 1.0.3

 ---

Hello, I have found what I think is a bug in HTTP.put() when making a multi-part request.
POST multi-part requests work fine, I will provide an example to illustrate my point.

I am using HTTP.jl to interact with the REST API of [Cordra](https://www.cordra.org/index.html). [REST API Documentation](https://www.cordra.org/documentation/api/rest-api.html#update-object-by-id). **But I think this is a general issue.**

### My code

```
port = "http://localhost:8000"
open("hw.txt") do io
    headers = []
    data = [
        "content" => JSON.json(Dict("This is a" => "test")),
        "File1" =>  HTTP.Multipart("MyFile", io)
    ]
    body = HTTP.Form(data)
    HTTP.post(port, headers, body; require_ssl_verification = false, status_exception = false)
end
```
### Request
![post](https://user-images.githubusercontent.com/67070956/128614547-c6036466-e6da-4428-9c4b-b57b6b63b51d.png)

Notice how the _content-type_ is automatically defined.

### My code

```
port = "http://localhost:8000"
open("hw.txt") do io
    headers = []
    data = [
        "content" => JSON.json(Dict("This is a" => "test")),
        "File1" =>  HTTP.Multipart("MyFile", io)
    ]
    body = HTTP.Form(data)
    HTTP.put(port, headers, body; require_ssl_verification = false, status_exception = false)
end
```
### Request
![put](https://user-images.githubusercontent.com/67070956/128614674-c51a798f-b254-4a0c-86c5-4c1a06ef0e9e.png)

Notice how _content-type_ is missing.
In this specific case, if I try to pass this request to Cordra, Cordra will be unable to parse the content of the request. My guess is that the issue is the missing content-type (and therefore, the missing "boundary" argument) in the headers.

## Manual Fix
This problem can be fixed by manually specifying the content-type header (including manually choosing a boundary):

```
port = "http://localhost:8000"
open("hw.txt") do io
    headers = ["Content-type" => "multipart/form-data; boundary=myboundary"]
    data = [
        "content" => JSON.json(Dict("This is a" => "test")),
        "File1" =>  HTTP.Multipart("MyFile", io)
    ]
    body = HTTP.Form(data; boundary = "myboundary")
    HTTP.put(port, headers, body; require_ssl_verification = false, status_exception = false)
end
```
### Request
![myboundary](https://user-images.githubusercontent.com/67070956/128614821-361cdac3-ec6a-4cf6-a6bb-4a8c001b460f.png)

This request looks similar to the POST request. Cordra will accept it.

---
I think HTTP.put() needs some tuning to be able to generate the content-type headers when working with HTTP.Form _multi-part requests_.

Please let me know if any additional information is needed.
Thank you!

**Comment by fredrikekre** [comment]
See https://discourse.julialang.org/t/send-multipart-request-from-julia-using-http-jl/60148/9. Wan't to make a PR to enable this for `PUT` too?
