### ISSUE TITLE
Method of API/authentication in Deprecated/Closed Requests.jl Not Carried Over to HTTP.jl

### ISSUE THREAD

**Issue by tj10ai** [JuliaWeb/HTTP.jl#748]
Julia 0.6.2 
HTTP.jl 0.X.X 
MbedTLS.jl 0.X.X -- Please specify versions
API services still use this method of vector for authentication (with API Key passed with HTTP), instead of header containing API Key (from the deprecated Requests.jl that no longer works):   response = post("vcloud.vocitec.com"; data=Dict("apikey"=>"<APIkeyHere>", "file"=>FileParam(open(filename,"r"),"text/julia","file2","file2.jl",true)))
readall(response)  .  Do you support this and I missed it in your documentation, or do you plan to support this method in the future? Thx!

**Comment by quinnj** [comment]
Please be more specific in what kind of functionality/authentication support you'd like to see in HTTP.jl that Requests.jl had.

**Comment by tj10ai** [comment]
I am trying use the AWS service V-Transcribe, an AI voice recognition system, but must pass their API key in their format. Here is what Voci Technologies tells about their API: "You cannot use HTTP Headers for authentication with the V-Cloud API. As shown in the example above, you need to provide the V-Cloud token as a form parameter in the HTTP call.
You need to find a way to convert multipart form data into what Julia will use.
I found this on the page --> https://juliahub.com/docs/HTTP/zXWya/0.9.0/autodocs/#HTTP.request
Here is an example I found that sends multipart form data along with an image --> http://5.9.10.113/66268254/julia-http-post-request-with-image-attachment
Another way may be to use the Requests.jl library (see the bottom of this page --> https://groups.google.com/g/julia-users/c/9kLC9yA-PCs)"

What confuses me about their response, is that they refer to your header method that they say they cannot use: HTTP.request(method, url [, headers [, body]]; <keyword arguments>]) -> HTTP.Response

**Comment by tj10ai** [comment]
Hmm. I missed this in what they said above; have they shown HTTP.jl doing correctly it in this: "This should be the equivalent request using HTTP.jl:

import HTTP
url = "http://localhost:8080" # check request with e.g. netcat -lp 8080
open("cat.jpg") do io
    headers = []
    data = [
        "token" => "APP_TOKEN",
        "user" => "USER_KEY",
        "attachment" => io,
    ]
    body = HTTP.Form(data)
    HTTP.post(url, headers, body)
end"

**Comment by fonsp** [comment]
Not sure if it helps, but `wss://vcloud.vocitec.com` is a WebSocket ULR, not an HTTP URL. This means that you can't make a POST or GET request, (but you can establish a websocket connection with `HTTP.WebSockets`). It sounds like you might have the wrong URL?

**Comment by quinnj** [comment]
Closing for staleness; there is a plan to do a thorough documentation update for HTTP.Form and multipart data.
