### ISSUE TITLE
Cookies not saved because case-sensitive Set-Cookie header?

### ISSUE THREAD

**Issue by RuiRojo** [JuliaWeb/HTTP.jl#765]
Julia 1.6.2 
HTTP.jl 0.9.14
MbedTLS.jl 1.0.3

I make a POST request to a site (to start a session) but the returned cookie isn't saved. I don't know much about all this so, I may be making a dumb mistake. But, after debugging, I think the issue is that the function `setcookies` is expecting the `Response` header to be named "Set-Cookie" when what I'm getting is not capitalized, "set-cookie". Maybe this should be case-insensitive?

(If I'm off the mark but it's obvious to someone what I may be doing wrong, I appreciate)

**Comment by pfitzseb** [comment]
Yes, header names are supposed to be case insensitive. Wanna open a PR?

**Comment by RuiRojo** [comment]
Ok, I [gave it a shot](https://github.com/JuliaWeb/HTTP.jl/pull/766)
