### ISSUE TITLE
Streaming through HTTP.open() with a POST

### ISSUE THREAD

**Issue by katorade8** [JuliaWeb/HTTP.jl#777]
Julia 1.4.1
Just a question - for use with `HTTP.open()`, I want to specify a post request to send data to my server and then receive data back as a stream, and operate on the response as I receive. I had something like this in mind:
```julia
datareq = HTTP.open("POST", url, postdata) do io
    while !eof(io)
        # do meaningful work on current stream element
    end
end
```
However, it seems like `HTTP.open()` doesn't support this kind of behavior. Is there a way to get this streaming behavior using `HTTP.request`?

**Comment by fredrikekre** [comment]
I believe you need something like this
```julia
HTTP.open("POST", "https://httpbingo.julialang.org/post") do io
    # Write data
    HTTP.write(io, "hello, world")
    # Done writing
    HTTP.closewrite(io)
    # Start reading
    HTTP.startread(io)
    write(stdout, io)
end
```

**Comment by quinnj** [comment]
Alternatively, you could have an `io = IOBuffer()` and pass `HTTP.post(url; response_stream=io)` if you don't care about writing the post body yourself and just want to stream read the response body.
