### ISSUE TITLE
`parse_multipart_form` does not parse "Content-Type" correctly.

### ISSUE THREAD

**Issue by rgankema** [JuliaWeb/HTTP.jl#782]
Julia 1.6.4

Forms with fields with content types other than `"text/plain"` don't seem to get parsed correctly. Here's an MRE:

```julia
julia> form = HTTP.Form(["foo" => HTTP.Multipart("", IOBuffer("foo"), "application/octet-stream")])
julia> headers = [HTTP.content_type(form)]
julia> request = HTTP.Request("GET", "foo.nl", headers, read(form))
julia> HTTP.parse_multipart_form(request)
1-element Vector{HTTP.Multipart}:
 HTTP.Multipart(filename="", data=::Base.GenericIOBuffer{SubArray{UInt8, 1, Vector{UInt8}, Tuple{UnitRange{Int64}}, true}}, contenttype="text/plain", contenttransferencoding=""))
```

Note that the parsed `Multipart` has `contenttype="text/plain"` instead of `"application/octet-stream"`

**Comment by NHDaly** [comment]
Okay, after investigating in #815, I've found that the failure to match comes from the `x` at the end of the regex, which from what i've read online, puts the regex into "comment mode." I'm still not exactly clear on what regex comment mode means.. this is what it says in the julia docs from `?r""`:
```julia
    •  `x` enables "comment mode": whitespace is enabled except when escaped with `\`, and `#`
       is treated as starting a comment.
```
Somehow that makes this regex fail to match:

```julia
infil> re_ct.re
r"(?i)Content-Type: (\S*[^;\s])"x

infil> header
"Content-Disposition: form-data; name=\"namevalue\"; filename=\"multipart.txt\"\r\nContent-Type: text/plain\r\n\r\n"

infil> occursin(r"(?i)Content-Type: (\S*[^;\s])"x, header)
false

infil> occursin(r"(?i)Content-Type: (\S*[^;\s])", header)
true
```

Do you know what that `x` is there for? What is it meant to do in this case? Can we safely get rid of it? Thanks!

**Comment by quinnj** [comment]
PR up: https://github.com/JuliaWeb/HTTP.jl/pull/832. I imagine the original code probably just copied the regex usage from places like [here](https://github.com/JuliaWeb/HTTP.jl/blob/72aceefb6530bc83ce38ebae591ec64d204a50b6/src/Parsers.jl#L63) where we _do_ include comments in the regex string that we'd like to ignore. I think in general this isn't necessary though.

**Comment by NHDaly** [comment]
Thanks!
