### ISSUE TITLE
Question: proxy configuration

### ISSUE THREAD

**Issue by gitboy16** [JuliaWeb/HTTP.jl#799]
Hi,
I need to setup the following in my startup.jl file to be able to install packages:
```julia
ENV["HTTP_PROXY"] = "http://<user>:<password>@proxy:8080"
ENV["HTTPS_PROXY"] = "https://<user>:<password>@proxy:8080"
```
However I need to use HTTP.jl with these proxy setting or environment variable bwing ignored. The R package `httr` allows me to do. Is there a way to do that with HTTP.jl? I am translating R code to Julia.
If it is not possible, is it possible to make it a feature request?
Thank you

**Comment by fredrikekre** [comment]
I believe you can pass `proxy = nothing`, or use the `no_proxy` environment variable for the URLs where you don't want a proxy.

**Comment by gitboy16** [comment]
Thanks @fredrikekre 
I'll try it.
Would something like this do it as well?
```julia
withenv("https_proxy" => nothing) do
HTTP.post(....)
end
```
Thank you

**Comment by fredrikekre** [comment]
Yes

**Comment by gitboy16** [comment]
Thanks a million
