### ISSUE TITLE
WebSocket connection failure: Incorrect 'Sec-WebSocket-Accept' value

### ISSUE THREAD

**Issue by fonsp** [JuliaWeb/HTTP.jl#807]
See https://github.com/fonsp/Pluto.jl/issues/1965#issuecomment-1059194797, still waiting on additional debugging information.

**Comment by fredrikekre** [comment]
@fonsp do you know if your PR solved this issue?

**Comment by fonsp** [comment]
I don't think so. After I opened the PR, the discussion on the original issue seemed to show that this is an issue with the Sockets stdlib, because ZMQ_jll was also not working on their system.

Summary here, https://github.com/fonsp/Pluto.jl/issues/1965#issuecomment-1065958988, @fredrikekre maybe you could take a look and advice which (debugging) steps to take next?

**Comment by quinnj** [comment]
Let's keep the discussion/debugging in https://github.com/fonsp/Pluto.jl/issues/1965, as I don't think there's enough information/reproducibility yet to pinpoint HTTP.jl.
