### ISSUE TITLE
Question about sniffing mime types

### ISSUE THREAD

**Issue by tlienart** [JuliaWeb/HTTP.jl#811]
Hello,

In LiveServer up to now we had been using an extension-based mime type discovery based on this list: https://github.com/JuliaWeb/HttpServer.jl/blob/master/src/mimetypes.jl 

Recently a user told me that this didn't render plain text with utf8 characters so I started looking a little bit and experienced with `sniff` but the behaviour is not exactly what I would have expected. For instance for a `.css` file I'd expect the mime to be `text/css`, for `.js` file `application/javascript` etc. The `sniff` function only seems to look at the first few bytes of a file to check whether there are markers like `<!doctype html>`. 

So if for a given file I want to return the best MIME possible, should I stick with an extension based approach, adjust the `text/plain` to `"text/plain; charset=utf-8"` and fallback to `sniff(content)`? i.e. something like this:

```julia
ext = lstrip(last(splitext(path)), '.')
mime = get(mimetypes, ext, HTTP.sniff(read(path)))
```

(for reference: https://github.com/tlienart/LiveServer.jl/blob/91e9e9ead216bb08c5a5bf9e85e555f1b5f0f641/src/server.jl#L265-L270)

**Comment by quinnj** [comment]
We could perhaps enhance the `ContentTypeRequest` module/layer to also consider filename extensions. I think `sniff` has its own stand-alone purpose in just trying to detect the format from the data itself, but I think we could also be intelligent beyond just relying on `sniff`. Mind making a PR?

**Comment by tlienart** [comment]
happy to, just to confirm I understood the suggestion: replacement of

https://github.com/JuliaWeb/HTTP.jl/blob/8743671f8e208b856defb17110ce2cd6705213c4/src/ContentTypeRequest.jl#L15-L28

to take the extension of `url` into account? 

maybe something like 

```
mime = sniff(bodybytes(body))
if mime == "application/octet-stream"
    # get extension of url
    # try to find extension in const mimetypes dictionary
    # set mime accordingly, otherwise leave to octet-stream
end

setkv(...)
```

and have the mimetypes dictionary brought here, possibly with a few additions like the charset utf8?

**Comment by fonsp** [comment]
@tlienart take a look at https://github.com/fonsp/MIMEs.jl, which has the filetype-mime mapping and a function to get the content-type header :)

**Comment by fonsp** [comment]
I made the package because I noticed that many Julia packages have a partial implementation of it (and `charset` is hard to implement correctly), but reliable mime databases exist. 

I decided not to make this part of HTTP.jl because I think it would benefit from independent development and update cycle, also alleviating maintainer work from HTTP.jl. (Moving forward, there is the idea to only have a 'core' HTTP server in HTTP.jl, with higher-level features in separate packages, for this same reason. #658)

**Comment by tlienart** [comment]
Nice work @fonsp ! And I'm supportive of the other idea of having a core lean and robust HTTP and move the rest in dedicated additional packages that can be updated more easily.

Small note:

Would it not be easier to have your update Mime thing to be a Julia script that gets executed by CI on pushes and produces a serialised Julia dict? (This would remove the dep on Artifact and JSON (JSON is not light last I checked but maybe I'm confusing with 2 or 3))

**Comment by fonsp** [comment]
@tlienart i was thinking about these two things too, but wow yes, those can be combined into a single script, nice! let's continue in MIMEs.jl

**Comment by quinnj** [comment]
Going to close this as I think the solution(s) are all in MIMEs.jl?
