### ISSUE TITLE
Simple usage examples from README not in docs

### ISSUE THREAD

**Issue by fonsp** [JuliaWeb/HTTP.jl#813]
> I lost time because the simple/effective examples shown in the `README.jl` are not found in the actual documentation.

_Originally posted by @clarkevans in https://github.com/JuliaWeb/HTTP.jl/issues/556#issuecomment-698102333_

**Comment by quinnj** [comment]
These are in the `docs/examples` directory now and end up on the "Examples" page in the docs.
