### ISSUE TITLE
UndefVarError: libmbedtls not defined

### ISSUE THREAD

**Issue by SastaDev** [JuliaWeb/HTTP.jl#814]
ERROR: LoadError: LoadError: UndefVarError: libmbedtls not defined
in expression starting at /data/data/com.termux/files/home/.julia/packages/HTTP/aTjcj/src/ConnectionPool.jl:707
in expression starting at /data/data/com.termux/files/home/.julia/packages/HTTP/aTjcj/src/HTTP.jl:39
ERROR: LoadError: Failed to precompile HTTP [cd3eb016-35fb-5094-929b-558a96fad6f3] to /data/data/com.termux/files/home/.julia/compiled/v1.5/HTTP/zXWya_SSS1j.ji.
in expression starting at /storage/emulated/0/julia/bot/TgBot/JLTgBotAPI/main.jl:1

**Comment by fonsp** [comment]
What version of HTTP.jl are you using? Run `import Pkg; Pkg.status(mode=Pkg.PKGMODE_MANIFEST)` to find out.

Try updating with `import Pkg; Pkg.update()`.

**Comment by fonsp** [comment]
@SastaDev ?
