### ISSUE TITLE
Question on defaultheader!(headers, "Accept" => "*/*")

### ISSUE THREAD

**Issue by GregorMatheis** [JuliaWeb/HTTP.jl#828]
Maybe someone can help me with this.
I need to send a post request to an API without having the header "Accept" => "*/*". 
I think that isn't very common, any ideas how I could work around this? Or would it be possible to create a keyword argument that skips the adding of the default headers?

Version:
 - Julia 1.7
 - HTTP.jl 0.9.17
 - MbedTLS.jl 1.0.3

**Comment by quinnj** [comment]
Can you explain more about the scenario you're running into? i.e. what's the issue by including `Accept: */*` by default? That should just signal that any response content-type is fine from the server.

There currently isn't a way to avoid having this header set by default, but you can of course include it manually to avoid it being set to `*/*` by default. i.e. by doing `HTTP.get(url, ["Accept" => "application/json"])`.

I just want to understand the use-case as this hasn't come up before, but ultimately it wouldn't be very hard to have some kind of keyword arg to avoid adding default headers or maybe specifically this header.

**Comment by GregorMatheis** [comment]
I want to use an api and while the python call to this api works as expected (returning 200) the julia call like returns 403. When setting up a local server and comparing the incoming request I noticed that `Accept: */*` is only there for the julia version.

Testing the API in Postman showed that including/excluding `Accept: */*` makes the difference between 200 and 403

I don't know why this was implemented into the api like this and I have no idea how many similar cases there are at other companies with their apis.

Python Code:
```
import requests
s = requests.session()
s.headers = {
            "user-agent": 'Your User Agent',
            "accept-language": 'en-UK',
            "Accept-Encoding": "gzip",
            "Content-Type": "application/json"
        }
s.post(
    "http://127.0.0.1:8080/api/v1/test",
    json={
        "device_type": "ANDROID",
        "email": "my_address@mail.com",
    }
)
```
This create the following on the test api:
```
POST /api/v1/test HTTP/1.1
Host: 127.0.0.1:8080
user-agent: Your User Agent
accept-language: en-UK
Accept-Encoding: gzip
Content-Type: application/json
Content-Length: 55

{"device_type": "ANDROID", "email": "my_address@mail.com"}
```



Julia Code:
```
import HTTP

 HTTP.request("POST",
    "http://127.0.0.1:8080/api/v1/test",
    Dict(
        "user-agent"=>"Your User Agent", 
        "accept-language"=>"en-UK", 
        "Accept-Encoding"=>"gzip", 
        "Content-Type"=> "application/json") ,
    "{\"device_type\": \"ANDROID\", \"email\": \"my_address@mail.com\"}";
    cookies = true
    )
```
This created the following on the test api:
```
POST /api/v1/test HTTP/1.1
user-agent: Your User Agent
accept-language: en-UK
Content-Type: application/json
Accept-Encoding: gzip
Host: 127.0.0.1:8080
Accept: */*
Content-Length: 55

{"device_type": "ANDROID", "email": "my_address@mail.com"}
```

**Comment by quinnj** [comment]
Interesting, first time I've ever seen this! We're following curl's behavior here of including the `Accept: */*` header by default. Curl also supports, however, the ability to set an "empty" header which won't be included in the final headers, which I'm inclined to copy as well for the solution here. So it would be something like `HTTP.request("POST", url, Dict("Accept" => nothing), ...)` and because the header value is `nothing`, we'll know to _exclude_ it when actually writing the request.

Does that sound ok?

**Comment by quinnj** [comment]
PR is up: https://github.com/JuliaWeb/HTTP.jl/pull/831
