### ISSUE TITLE
Building the docs modifies source files

### ISSUE THREAD

**Issue by fredrikekre** [JuliaWeb/HTTP.jl#856]
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

$ julia --project=docs docs/make.jl &> /dev/null

$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   docs/src/examples.md                                       <-----------------

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by quinnj** [comment]
This is done [on purpose](https://github.com/JuliaWeb/HTTP.jl/blob/6ec44e203977f4abee28fd80adfbf351a1c6629b/docs/make.jl#L7). Is there another way we should be handling that?

**Comment by fredrikekre** [comment]
Right, but then I guess that file shouldn't be commited? What is the point of having https://github.com/JuliaWeb/HTTP.jl/blob/master/docs/src/examples.md which is not even current?

**Comment by quinnj** [comment]
Oh, I see. Yes, I guess we don't need to be changing the local file then? I'm not entirely sure how that's working TBH.
