### ISSUE TITLE
Routing: path containing underscore "_" in path path variable fails to route

### ISSUE THREAD

**Issue by BoZenKhaa** [JuliaWeb/HTTP.jl#871]
Using a path variable with an underscore registers a path successfully, but then fails to match the path to a request. For example, consider the [simple server example](https://github.com/JuliaWeb/HTTP.jl/blob/master/docs/examples/simple_server.jl):

Changing the path variable from `id` to `animal_id`:
![image](https://user-images.githubusercontent.com/1710518/177041351-ab70b054-5897-4b1e-9619-f88761ce1b8f.png)

leads to the following error:
![image](https://user-images.githubusercontent.com/1710518/177041362-5915b223-1bb0-447f-8f31-371c2e93f038.png)

I can try to prepare a PR, but I am not sure what should actually happen. In my opinion, either

1. underscores and other allowed Julia variable names should work,
2. there should be a mention of allowed characters in the docstring,
3. `register!` should throw an error when trying to register a path with not allowed characters path variables,
4. trying to fetch a route with a path using the incorrect characters in path variables should show some warning

Versions:
 - Julia 1.7.2
 - HTTP.jl 1.0.5
 - MbedTLS.jl 1.1.0

**Comment by fredrikekre** [comment]
Since they are just strings it doesn't seem necessary to limit to valid identifiers. Perhaps something like
```diff
diff --git a/src/Handlers.jl b/src/Handlers.jl
index bcb8bc8..cc24e67 100644
--- a/src/Handlers.jl
+++ b/src/Handlers.jl
@@ -145,7 +145,7 @@ mutable struct Variable
     pattern::Union{Nothing, Regex}
 end

-const VARREGEX = r"^{([[:alnum:]]+):?(.*)}$"
+const VARREGEX = r"^{([^:]+)(?::(.*))}$"

 function Variable(pattern)
     re = Base.match(VARREGEX, pattern)
@@ -178,7 +178,7 @@ end
 Base.show(io::IO, x::Node) = print(io, "Node($(x.segment))")

 isvariable(x) = startswith(x, "{") && endswith(x, "}")
-segment(x) = segment == "*" ? String(segment) : isvariable(x) ? Variable(x) : String(x)
+segment(x) = x == "*" ? String(x) : isvariable(x) ? Variable(x) : String(x)

 Node(x) = Node(x, Node[], Node[], nothing, nothing, Leaf[])
 Node() = Node("*")
```
would work?

**Comment by BoZenKhaa** [comment]
Is there no reason for limiting the string to `:alnum:`?

**Comment by quinnj** [comment]
I think I ended up coping the `:alnum:` restriction from some other implementation I came across, but I agree that we don't really need to limit it at all, except maybe to ensure we can still find the closing `}` properly. I'd rather say curly brackets are not allowed than deal w/ some kind of escaping scheme.

@fredrikekre, mind making a PR w/ your patch?
