### ISSUE TITLE
The CRT/CRL/CSR format is invalid

### ISSUE THREAD

**Issue by MahanBi** [JuliaWeb/HTTP.jl#879]
- Julia 1.7.2
 - HTTP.jl 1.0.5
 - MbedTLS.jl 1.1.0

Hello, I have a problem using HTTP.
At first, the problem was the cert.pem file, and I created it manually, but I don't know what to make in it, and it still gives this error.

```julia
  url = "https://insights.stackoverflow.com/survey";
  res = HTTP.get(url; insecure=true)
```
>>> HTTP.Exceptions.ConnectError("https://insights.stackoverflow.com/survey", MbedTLS error code -8576: X509 - The CRT/CRL/CSR format is invalid, e.g. different type expected)

**Comment by quinnj** [comment]
I think you're looking for `HTTP.get(url; require_ssl_verification=false)`
