### ISSUE TITLE
CI jobs fail since 1.0.5

### ISSUE THREAD

**Issue by cserteGT3** [JuliaWeb/HTTP.jl#902]
I noticed that the latest available documentation is for v1.0.5, but the latest tag is 1.2.1. The issue seems to be at [this line](https://github.com/JuliaWeb/HTTP.jl/blob/master/.github/workflows/ci.yml#L14):
`The workflow is not valid. .github/workflows/ci.yml (Line: 14, Col: 10): Unexpected type of value '', expected type: String.`
But that part is the same as in the [concurrency documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency), so I don't have any idea how to solve this.

**Comment by fonsp** [comment]
Thanks! Fixed in https://github.com/JuliaWeb/HTTP.jl/commit/b309fe3fcc06625507fb7387978b5effb315854d
