### ISSUE TITLE
Downloading an EXCEL file using HTTP.jl

### ISSUE THREAD

**Issue by shayandavoodii** [JuliaWeb/HTTP.jl#917]
- Julia 1.8.0
 - HTTP.jl 0.9.17
 - MbedTLS.jl 1.1.4

I want to download a `.xlsx` file using HTTP like this:

```julia
julia> using HTTP, XLSX

julia> res = HTTP.get("http://www.tsetmc.com/tsev2/excel/IntraDayPrice.aspx?i=35425587644337450&m=30");

julia> write("c:/users/shayan/desktop/file.xlsx", res.body);
```

But it leads to an error when I want to read it using `XLSX.jl`:

```julia
julia> a = XLSX.readxlsx("c:/users/shayan/desktop/file.xlsx")
ERROR: c:/users/shayan/desktop/file.xlsx is not a valid XLSX file.
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:35
 [2] check_for_xlsx_file_format(filepath::String)
   @ XLSX C:\Users\Shayan\.julia\packages\XLSX\FFzH0\src\read.jl:24
 [3] XLSX.XLSXFile(filepath::String, use_cache::Bool, is_writable::Bool)
   @ XLSX C:\Users\Shayan\.julia\packages\XLSX\FFzH0\src\types.jl:255
 [4] open_or_read_xlsx(filepath::String, read_files::Bool, enable_cache::Bool, read_as_template::Bool)
   @ XLSX C:\Users\Shayan\.julia\packages\XLSX\FFzH0\src\read.jl:190
 [5] readxlsx(filepath::String)
   @ XLSX C:\Users\Shayan\.julia\packages\XLSX\FFzH0\src\read.jl:37
 [6] top-level scope
   @ REPL[6]:1
```

Additional information:  
In the comments on [this question in StackOverFlow](https://stackoverflow.com/questions/73555625/error-http-1-1-403-forbidden-in-downloads-jl?noredirect=1#comment129893761_73555625), There is more explanation.

My friend, [Elias](https://github.com/eliascarv), did the same thing but it was successful for him:
![image](https://user-images.githubusercontent.com/52105833/187693790-6f189707-ed82-44b4-819c-326998bef6af.png)

**Comment by fredrikekre** [comment]
Works for me too. Did
```
res = HTTP.get("http://www.tsetmc.com/tsev2/excel/IntraDayPrice.aspx?i=35425587644337450&m=30");
```
return an OK response such that `res.status` is 200?

The 403 error you mention on StackOverflow suggests otherwise. Perhaps your IP is blocked or something.

**Comment by shayandavoodii** [comment]
> 

Yes, it returns 200. But afterward, I couldn't read it correctly using Julia.

**Comment by fredrikekre** [comment]
Isn't this an issue for the XLSX package then if you are saying the download was OK?

**Comment by shayandavoodii** [comment]
> Isn't this an issue for the XLSX package then if you are saying the download was OK?

Maybe. But if it is downloaded correctly, I should be able to open it.
