### ISSUE TITLE
[feature] allow specification of the CA bundle via environment variable

### ISSUE THREAD

**Issue by racinmat** [JuliaWeb/HTTP.jl#925]
It would be useful to support global settings for the CA bundle in similar manner as e.g. python requests have it https://requests.readthedocs.io/en/latest/user/advanced/?highlight=REQUESTS_CA_BUNDLE#ssl-cert-verification using also the `CURL_CA_BUNDLE` env var would make it easier for other people who are dealing with CA bundles in other systems or languages.

I know now it can be done using
```julia
conf = SSLConfig()
MbedTLS.ca_chain!(conf, MbedTLS.crt_parse(cert_file))
```
or 
```julia
HTTP.ConnectionPool.default_sslconfig = SSLConfig(...)
```

but it would be useful to have option which would not need code change.

**Comment by quinnj** [comment]
Sorry for the slowness; implemented in https://github.com/JuliaWeb/HTTP.jl/pull/933
