### ISSUE TITLE
WebSockets client error

### ISSUE THREAD

**Issue by jvo203** [JuliaWeb/HTTP.jl#948]
The HTTP.WebSockets client occasionally produces the following error:

```
ERROR: LoadError: MethodError: no method matching listen(::var"#15#16", ::String, ::Int64)
Closest candidates are:
  listen(::Function, ::String) at ~/.julia/packages/HTTP/aTjcj/src/WebSockets.jl:131
  listen(::Function, ::String, ::UInt16; binary, verbose, kw...) at ~/.julia/packages/HTTP/aTjcj/src/WebSockets.jl:131
  listen(::Function) at ~/.julia/packages/HTTP/aTjcj/src/WebSockets.jl:131
Stacktrace:
 [1] top-level scope
   @ /mnt/data/chris/Phi/FX/Polygon/physworx.jl:127
in expression starting at /mnt/data/chris/Phi/FX/Polygon/physworx.jl:127
```

Here is my Julia WebSocket client code:
```
using HTTP.WebSockets

WebSockets.open("wss://physworx.com/websocket") do ws_client
        while true
            s = receive(ws_client)

            # check if s is a String
            if !isa(s, String)
                continue
            end

            # ignore empty strings
            if s != ""
                # println(stderr, " received:", s)

etc...
```

The PhysWorx WebSockets server uses Golang "github.com/gorilla/mux".

 - Julia 1.8.2
 - HTTP.jl 1.5.1
 - MbedTLS.jl: status MbedTLS: "No Matches"

**Comment by quinnj** [comment]
Hmmmm........I'm a little confused. The ERROR you shared seems to deal with running a server? But the code is client code? But then you mention something about the server being golang?

**Comment by jvo203** [comment]
Well yes, there is a Julia WS client as well as a Julia WS server and a separate Golang WS server.

1. The Julia WebSockets client (contained in the file physworx.jl) connects to the Golang WebSocket server located at "wss://physworx.com/websocket"
```
function event_loop(models, messages)
    WebSockets.open("wss://physworx.com/websocket") do ws_client
        for s in ws_client

            # check if s is a String
            if !isa(s, String)
                continue
            end

            # ignore empty strings
            if s != ""
                # println(stderr, " received:", s)
...
```
2. The same Julia code (in the same file physworx.jl) also contains a WebSocket server part further down the line:
```
# WebSockets Server
server = WebSockets.listen("127.0.0.1", 8081) do ws
    global message_queue

    while true
        msg = take!(message_queue)
        @info "Received: $msg"
        send(ws, msg)
    end
end
```

The Julia WS server part takes messages from the Julia WS client via the "message_queue" Channel and serves them locally. The error reported in this message quite likely originates in the WS client part. It happens even if there are no local WS clients connecting to the Julia WS server at ws://127.0.0.1:8081. So yes, it is a bit complicated.

**Comment by jvo203** [comment]
In other words, the error reported in this issue occurs even if the Julia server code
```
# WebSockets Server
server = WebSockets.listen("127.0.0.1", 8081) do ws
    global message_queue

    while true
        msg = take!(message_queue)
        @info "Received: $msg"
        send(ws, msg)
    end
end
```

is completely removed. So I am 100% confident the problem lies in the Julia WS client.

**Comment by jvo203** [comment]
Extra information, I also had a Python WebSocket client connecting without any errors to the Golang WebSocket server located at "wss://physworx.com/websocket". So I don't think the Golang WebSocket server is at fault. Something is going wrong inside the Julia WebSocket client.

**Comment by jvo203** [comment]
Moreover, the stack trace
```
Stacktrace:
 [1] top-level scope
   @ /mnt/data/chris/Phi/FX/Polygon/physworx.jl:127
in expression starting at /mnt/data/chris/Phi/FX/Polygon/physworx.jl:127
```
explicitly refers to the line where the Julia WS client is launched (```function event_loop(models, messages)```), *NOT* the WS server further down the line.

**Comment by jvo203** [comment]
I cannot reproduce the conditions that led to the error reported in this issue so for now I am closing it. If the issue resurfaces I will re-open it.

Below are simple Golang and Julia programs that I used to try to reproduce the issue on a local PC (without using OpenSSL so it's "ws" instead of "wss").

Julia WS client/server:
```
using HTTP.WebSockets

@async WebSockets.open("ws://localhost:8080/ws") do ws_client
    for s in ws_client
        # check if s is a String
        if !isa(s, String)
            continue
        end

        # ignore empty strings
        if s != ""
            println(" received:", s)

            # sleep for some time
            sleep(11)

            # send a message
            send(ws_client, "hello from Julia")
        end
    end
end

# WebSockets Server
server = WebSockets.listen("127.0.0.1", 8081) do ws
    for msg in ws
        @info "WS Server Received: $msg"
        send(ws, msg)
    end
end
```

Golang WS server:
```
// Copyright 2015 The Gorilla WebSocket Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build ignore
// +build ignore

package main

import (
	"flag"
	"log"
	"net/http"

	"github.com/gorilla/websocket"
)

var addr = flag.String("addr", "localhost:8080", "http service address")

var upgrader = websocket.Upgrader{} // use default options

func ws(w http.ResponseWriter, r *http.Request) {
	c, err := upgrader.Upgrade(w, r, nil)

	if err != nil {
		log.Print("upgrade:", err)
		return
	}
	defer c.Close()

	msg := []byte("Let's start talking.")
	err = c.WriteMessage(websocket.TextMessage, msg)

	if err != nil {
		log.Println(err)
	}

	for {
		mt, message, err := c.ReadMessage()

		if err != nil {
			log.Println("read:", err)
			break
		}

		log.Printf("recv: %s", message)

		err = c.WriteMessage(mt, message)

		if err != nil {
			log.Println("write:", err)
			break
		}
	}
}

func main() {
	flag.Parse()
	log.SetFlags(0)
	http.HandleFunc("/ws", ws)
	log.Fatal(http.ListenAndServe(*addr, nil))
}
```
