### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by deahhh** [JuliaWeb/HTTP.jl#952]
- Julia 1.8.2
 - HTTP.jl 1.5.1

[source and test](https://discourse.julialang.org/t/how-to-make-it-be-a-memory-leak-program-without-lower-function-such-as-gc-xxx-used/89347/9)

**Comment by quinnj** [comment]
I can't reproduce a memory leak by running the following:
```julia
using HTTP

function run_n(n)
    x = Int[]
    y = Int[]
    for i = 1:1000
        resp = HTTP.get("https://google.com")
        push!(x, i)
        push!(y, Int(Sys.free_memory()))
    end
    return (x, y)
end

x, y = run_n(1000)
using UnicodePlots
scatterplot(x, y, height=:auto, width=:auto)
```

**Comment by deahhh** [comment]
> 

Thanks!
I find something wrong in my code:
     for the version 1, it's creating Task for each url, for the version 2, it's with no lock while using Task with global variable and io ops.
There is sorry for no body point them out.

**Comment by deahhh** [comment]
I fixed the program, but, memory leak still
