### ISSUE TITLE
unincode not handled properly 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [JuliaWeb/HTTP.jl#954]
versioninfo

```
Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
Environment:
  JULIA_EDITOR = vim
```

http.jl = `HTTP v1.4.0`

```julia
using HTTP, JSON3, StructTypes, Sockets

mutable struct Animal
    id::Int
    userId::Base.UUID
    type::String
    name::String
    Animal() = new()
end

StructTypes.StructType(::Type{Animal}) = StructTypes.Mutable()

const ANIMALS = Dict{Int, Animal}()
const NEXT_ID = Ref(0)
function getNextId()
    id = NEXT_ID[]
    NEXT_ID[] += 1
    return id
end

# "service" functions to actually do the work
function createAnimal(req::HTTP.Request)
    animal = JSON3.read(req.body, Animal)
    animal.id = getNextId()
    ANIMALS[animal.id] = animal
    return HTTP.Response(200, JSON3.write(animal))
end

function getAnimal(req::HTTP.Request)
    animalId = HTTP.getparams(req)["id"]
    animal = ANIMALS[parse(Int, animalId)]
    return HTTP.Response(200, JSON3.write(animal))
end

function updateAnimal(req::HTTP.Request)
    animal = JSON3.read(req.body, Animal)
    ANIMALS[animal.id] = animal
    return HTTP.Response(200, JSON3.write(animal))
end

function deleteAnimal(req::HTTP.Request)
    animalId = HTTP.getparams(req)["id"]
    delete!(ANIMALS, animalId)
    return HTTP.Response(200)
end

# define REST endpoints to dispatch to "service" functions
const ANIMAL_ROUTER = HTTP.Router()
HTTP.register!(ANIMAL_ROUTER, "POST", "/api/zoo/v1/réception", createAnimal)
# note the use of `*` to capture the path segment "variable" animal id
HTTP.register!(ANIMAL_ROUTER, "GET", "/api/zoo/v1/réception/{id}", getAnimal)
HTTP.register!(ANIMAL_ROUTER, "PUT", "/api/zoo/v1/réception", updateAnimal)
HTTP.register!(ANIMAL_ROUTER, "DELETE", "/api/zoo/v1/réception/{id}", deleteAnimal)
HTTP.register!(ANIMAL_ROUTER, "GET", "/api/zoo/v1/animal/{id}", getAnimal)


server = HTTP.serve!(ANIMAL_ROUTER, Sockets.localhost, 8080)


# using our server
x = Animal()
x.type = "cat"
x.name = "pete"

resp = HTTP.post("http://localhost:8080/api/zoo/v1/réception", [], JSON3.write(x))
x2 = JSON3.read(resp.body, Animal)

resp = HTTP.get("http://localhost:8080/api/zoo/v1/réception/$(x2.id)")

x3 = JSON3.read(resp.body, Animal)
```

![http](https://user-images.githubusercontent.com/8083613/199635368-8654f999-a08c-441e-8d51-f979ee18faeb.gif)

possible solution could be 

unescaping HTTP.URIs.unescapeuri`req.target` but I don't know exactly where this should be done. Not familiar with the package's code base

**Comment by clarkevans** [comment]
Perhaps  `register!` that should be raising an error if a fragment contains Unicode, lower case hex digit characters, or other invalid URI characters?  I'd be hesitant on trying to automatically escape anything at this level of the stack.

You should probably register your router by encoding `é` as `%C3%A9`, e.g.

```
HTTP.register!(ANIMAL_ROUTER, "GET", "/api/zoo/v1/r%C3%A9ception/{id}", getAnimal)
```

**Comment by AbhimanyuAryan** [comment]
@clarkevans well my workflow was just creating `.jl` and `include("http_animal.jl")` no errors/exceptions in that case atleast

**Comment by AbhimanyuAryan** [comment]
but you are right this about `level of the stack` part

**Comment by AbhimanyuAryan** [comment]
actually took care of it inside Genie where this issue was initially reported https://github.com/GenieFramework/Genie.jl/issues/549 yes let's keep http.jl minimal :)

**Comment by AbhimanyuAryan** [comment]
Yes took care of this in https://github.com/GenieFramework/Genie.jl/issues/549 where this issue was initially reported. Makes sense to not take such things at http level.  Rails taking care of it as well

**Comment by clarkevans** [comment]
Escaping Unicode characters, since they should never be in a URL anyway, is also a reasonable design choice. Since the HTTP package added routing feature, perhaps it should take care of this case.

**Comment by AbhimanyuAryan** [comment]
in general http lib(what I have seen in other languages) shouldn't take care of routing and keep the implementation slim/solid/minimum
