### ISSUE TITLE
Extract case-insensitive headers

### ISSUE THREAD

**Issue by KristofferC** [JuliaWeb/HTTP.jl#97]
HTTP headers are case-insensitive and I am getting different capitalizations with HTTPServer.jl and HTTP.jl. 

In Github.jl, there is a check that is equivalent to `haskey(HTTP.headers(request), "X-GitHub-Event")`, which fails when I don't get the "correct" casing in the header key (from HTTP.jl I get `Github`instead of `GitHub`).
What is the correct way to extract the value for a key if the casing cannot be used, and the headers are stored in a dictionary (which is case-sensitive).

**Comment by quinnj** [comment]
Header keys are always canonicalized to proper-casing, w/ capitalization after dashes. So in your case, you can consistently use `X-Github-Event` and the header key will _always_ be that value, no matter what a server sends you in response. This is obviously less useful in a case like this, where you're only ever expecting a single casing of a header key from a unique service, but for keys like `Location` (for redirection) or `Content-type`, it's drastically simpler for users to only ever need to check a single casing, regardless of how the server sends the data.

**Comment by KristofferC** [comment]
> Header keys are always canonicalized to proper-casing

Thanks, that answers the question.
