### ISSUE TITLE
Need option to force use of Content-Length header (disable Transfer-Encoding: chunked)

### ISSUE THREAD

**Issue by samoconnor** [JuliaWeb/HTTP.jl#98]
RFC2616 forbids use of Content-Length with Transfer-Encoding:
["If a message is received with both a Transfer-Encoding header field and a Content-Length header field, the latter must be ignored."](
http://greenbytes.de/tech/webdav/rfc2616.html#rfc.section.4.4)

But AWS S3 PUT (Object) [requires a Content-Length header](
https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html); and so by implication does not support Transfer-Encoding: chunked.

So we need an option to disable Transfer-Encoding: chunked for uploads. 

```
HTTP/1.1 501 Not Implemented
Transfer-Encoding: chunked
Connection: close
Content-Length: 333
x-amz-request-id: EF2A94CBAA73ACF3
Content-Type: application/xml
Date: Tue, 17 Oct 2017 23:06:10 GMT
Server: AmazonS3
x-amz-id-2: oOGp1TWT1oxhR5FMrLJoLNRkjuF54HyIJW/OsixUe5L8BU2SusthYsFeRqACYaSKW1jbaHraFco=

<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>NotImplemented</Code>
<Message>A header you provided implies functionality that is not implemented</Message>
<Header>Transfer-Encoding</Header>
<RequestId>EF2A94CBAA73ACF3</RequestId>
<HostId>oOGp1TWT1oxhR5FMrLJoLNRkjuF54HyIJW/OsixUe5L8BU2SusthYsFeRqACYaSKW1jbaHraFco=</HostId>
</Error>
```

**Comment by quinnj** [comment]
Can you provide a little more info on the object you're putting? We have only a few cases where we default to chunked transfer
* object size is over the request option `chunksize`, in this case passing a larger `chunksize` (in bytes) avoids chunking
* the object is not given completely at the time of the request; i.e. the user passes an `HTTP.FIFOBuffer` and uploads asynchronously, chunks at a time (in which case each consecutive read from the buffer is sent as a chunk)

In fact, as far as I can tell, there shouldn't be a case where HTTP sets both headers on a request: is there some way the header is getting set for the request manually?

**Comment by samoconnor** [comment]
I apologise for the confusion, HTTP.jl is not setting both headers.
The problem is simply that chunked encoding is used for large objects (I guess for objects larger than whatever the default chunk size is?)

I just need a way to disable chunked encoding completely.

From what you are saying, the way to do this is to set chunksize to the size of the data + 1.
Options:
 - documentation update to explain setting chunksize > data size to disable chunked mode, or
 - change to remove use of chunked mode in cases where data size is known at start of transmission, or
 - new boolean config option "enable_transfer_encoding".

Is there any benefit to chunked uploads in cases where content-length is known?

**Comment by quinnj** [comment]
I mean, it can certainly lead to more robust uploads, since the client & server don't have to rely on having a single, no-interruptions connection for an entire upload. We can certainly bump up the default chunk_size to like 1GB or something (currently, I think it's at 1MB).

I think your 2nd point is also probably a good default; if we know the size at initial request time, just upload the entire object as is, unless the user provides a chunk_size arg.

**Comment by samoconnor** [comment]
> bump up the default chunk_size to like 1GB or something

This seems a bit dangerous, as it just makes the potential pitfall less likely (more likely to show up later in production rather than sooner in testing).

> if we know the size at initial request time, just upload the entire object as is

I think this is the right choice. As far a I understand it, the only time that `Transfer-Encoding: chunked` is useful is when Content-Length is not known at transmission start time.

> ... more robust uploads, since the client & server don't have to rely on having a single, no-interruptions connection for an entire upload.

How does an upload get restarted after an interrupted connection?
Do you know of a standard mechanism for restarting a PUT? (my knowledge of this stuff is a few years out of date)

I expect that some servers might accept multiple seperate PUTs with Content-Range as a way to upload a file part by part. But if the connection for a chunked PUT was interrupted, I wouldn't expect the server to persist the partially uploaded data, (i.e. allowing GET for an object where PUT has not completed doesn't seem right).

I have some experience of making remote uploads of large medical data files efficient/reliable. The best way seems to be to upload individual small objects and have the server-side handle re-combining the parts (or, using a service-specific feature like [S3 Multipart Upload](http://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html)). This allows for some concurrency in uploading the parts; it works with a multinode/replicated server (behind a load-balancer); and it works around ISP throttling of long-running uploads (some home and mobile ISPs seem to do this in Australia).

**Comment by quinnj** [comment]
Alright, just pushed code so that we only do chunked transfer when the size of the body isn't know at request time.
